### ISSUE TITLE
imtoken1.0中AKC图标不显示，imtoken2.0搜索不到AKC

### ISSUE THREAD

**Issue by hldzlk** [consenlabs/token-profile#1003]
AKC代币信息已提交合并，[profile页面](https://aws-token-profile.token.im/token/0x1ca43a170bad619322e6f54d46b57e504db663aa?locale=zh-CN)已经有信息显示，但是imtoken1.0中AKC图标不显示，imtoken2.0搜索不到AKC。代币合约地址```0x1Ca43a170BaD619322e6f54d46b57e504dB663aA``` ，这种问题该如何解决？谢谢

**Comment by plusor** [comment]
https://github.com/consenlabs/token-profile/issues/741
https://github.com/consenlabs/token-profile/issues/135

全给我关闭了，  就是不给解决

**Comment by tstt** [comment]
你好,
稍等，我们会进行检查。
