### ISSUE TITLE
#1009 修改了合约地址，合并报错的是别人的json代码

### ISSUE THREAD

**Issue by gsgsupport** [consenlabs/token-profile#1011]
Pull requests ID：#1009 
合并请求时看到提示的错误为
ERROR! json file 0xfaaf0Ecfb3246902de6A2C77c5B114DA555695A3.json's links every field must be an url，但这个json文件不是我提交的文件，望核实，感谢。

**Comment by tstt** [comment]
你好,
我们会进行检查。
