### ISSUE TITLE
咨询“请提供更多代币信息，并在评论区补充相关区块链媒体报道”问题？

### ISSUE THREAD

**Issue by Benson2016** [consenlabs/token-profile#1012]
![image](https://user-images.githubusercontent.com/18086295/42741534-cda0da90-88e5-11e8-8b36-64aaecc58190.png)
@makoshan 你好！在下愚钝，未能明白先生所言，能否具体些？例如：更多？评论区所指哪个？（请看截图）

**Comment by tstt** [comment]
你好,
这样说也许会清楚些“请提供贵方代币相关的更多资料”，关于评论区，咨询贵方技术人员即可。
