### ISSUE TITLE
有两个合约没有提供图片，导致后面所以提交的 pull request 无法 travis-ci 通过

### ISSUE THREAD

**Issue by netkiller** [consenlabs/token-profile#1018]
我的合约：

https://travis-ci.org/consenlabs/token-profile/builds/404308141?utm_source=github_status&utm_medium=notification

提示错误：

Warning! dose not have 0x5f3fe72d30868c2BFaBeFf9c32cF2414abaA0581.png in images dir, please check first
Warning! dose not have 0xF3b6FA35C2cD0dbB640f03da07cE7e397c66939a.png in images dir, please check first
ERROR! json file 0xfaaf0Ecfb3246902de6A2C77c5B114DA555695A3.json's links every field must be an url
npm ERR! Test failed.  See above for more details.

那两张图片根本不是我的。 从 #1010 opened 3 hours ago by ITEChainAdmin   开始，后面的 token 都提交不了。

请管理员速解决。

**Comment by Eiminyang** [comment]
我也是这个问题，请管理员尽快解决

**Comment by Eiminyang** [comment]
自己修改下文件

**Comment by wenyanwang** [comment]
重新按照要求提交即可。
