### ISSUE TITLE
为啥合并了还搜索不到？

### ISSUE THREAD

**Issue by ybcchain** [consenlabs/token-profile#1047]

**Comment by ybcchain** [comment]
在imtoken钱包里面怎么搜索不到

**Comment by ybcchain** [comment]
@wenyanwang 为啥合并了但是imtoken里面搜索不到？

**Comment by timetreatychain** [comment]
我的也是  这个审核通过之后还有什么操作吗？

**Comment by plusor** [comment]
https://github.com/consenlabs/token-profile/issues/741
https://github.com/consenlabs/token-profile/issues/135

全给我关闭了，  就是不给解决

**Comment by tstt** [comment]
你好,
请稍等，我们会进行检查。
