### ISSUE TITLE
ERROR! json file 0xfaaf0Ecfb3246902de6A2C77c5B114DA555695A3.json's links every field must be an url

### ISSUE THREAD

**Issue by galfen** [consenlabs/token-profile#1050]
ERROR! json file 0xfaaf0Ecfb3246902de6A2C77c5B114DA555695A3.json's links every field must be an url    提交失败,因为这个json文件

**Comment by jarifee** [comment]
please check the source code the error with "ERROR! json file 0xfaaf0Ecfb3246902de6A2C77c5B114DA555695A3.json's links every field must be an url"
This is a source exits issue. waiting for you guy fixed.

**Comment by jarifee** [comment]
almost requests failed because  of source code 0xfaaf0Ecfb3246902de6A2C77c5B114DA555695A3.json, it exists issue

**Comment by tstt** [comment]
你好,
请按照教程自查。
