### ISSUE TITLE
需要更新代币地址和logo

### ISSUE THREAD

**Issue by songserver** [consenlabs/token-profile#1051]
您好：
      PDX由于业务需要，现需修改原有的代币地址和logo，github提交机器人审核自动报错，还烦请帮忙解决一下
PDX原代币地址：0x4375380D11a0A8971F053aebA0629a61392Ec0e7
PDX新代币地址：0x5F33d158CA7275848F70A3f149b421190DF85B32

**Comment by zhen6939** [comment]
done
