### ISSUE TITLE
imtoken 1.0 ARP 图标显示不对

### ISSUE THREAD

**Issue by wellsqiu** [consenlabs/token-profile#1083]
PR地址：[https://github.com/consenlabs/token-profile/pull/206](https://github.com/consenlabs/token-profile/pull/206)
合约地址：0xbeb6fdf4ef6ceb975157be43cbe0047b248a8922

![1988113634](https://user-images.githubusercontent.com/17876618/42803771-8fc31860-89d9-11e8-867d-e217156cd73e.jpg)

**Comment by tstt** [comment]
你好,
我们工作人员会进行检查。
