### ISSUE TITLE
#938官方不看提交就close。

### ISSUE THREAD

**Issue by lindong58** [consenlabs/token-profile#1102]
请看清楚938已经删除了错误的0x378903a03FB2C3AC76BB52773e3CE11340377A32 
还提醒我删除，官方到底有没有认真做事的人？等了多久了白等了？

**Comment by eosochain** [comment]
我也遇到了，不知道什么状况... 明明提交里已经删除了错误文件

**Comment by tstt** [comment]
你好,
请按照我们提供的教程自查，感谢配合。按照教程操作即可。
