### ISSUE TITLE
我已经提交了githtub,并且json文件也提供了，为什么感觉还是报错不行

### ISSUE THREAD

**Issue by helloellis** [consenlabs/token-profile#1105]
我是们是基本erc20代币协议发行的一个代币，希望能在imtoken钱包能够收录我们，我们数字钱包的名称为  ellistoken   简称：elis 慈善链

发行量:5.8亿枚
智能合约地址：0x6c1796d1c17d9361314770d357dc7b6aa03b3a5d
推荐用户转账所使用的 Gas 数量：暂时没有，默认为imtoken即可
是否需要空投推广：可能需要空投推广
我们白皮书，这些我们都以着附件的形式发给您，

**Comment by helloellis** [comment]
为什么没有人回复啊

**Comment by tstt** [comment]
你好,
请按照我们提供的教程自行检查。
