### ISSUE TITLE
关闭#1099

### ISSUE THREAD

**Issue by ForBTM** [consenlabs/token-profile#1144]
#1099 我写了评论，整理下
"github": "https://github.com/dmsggg/token-profile",
github地址竟然是这个，代码就是提交imtoken改图标的代码吗，空气币害人，官网也就一个home page 
而且区块链浏览器上合约地址都没有名字， 还好意思写上"state": "NORMAL"
PR里写都没上交易所，initial price不知 怎么来的，写有210亿，合约里都还没添加，还0.02ETH
看了白皮书，更是不正经的东西

搞不懂为何这些人热衷于来发假币来坑人骗钱，国家要是不监管，这个区块链被这些老鼠屎搞坏了

**Comment by ForBTM** [comment]
这些人怎么不被抓起来

**Comment by ForBTM** [comment]
。。。。。。

**Comment by ForBTM** [comment]
byebye

**Comment by wenyanwang** [comment]
你好，我们并未通过此代币信息，谢谢。
