### ISSUE TITLE
请求合并#1099 ，谢谢

### ISSUE THREAD

**Issue by dmsggg** [consenlabs/token-profile#1145]
请求合并 #1099 

PS：遭到冒充管理员的诈骗的信息，识破后他们在GITHUB上进行恶意言论攻击。有微信聊天记录作为证据，可邮件或微信联系我们提供。谢谢工作人员！

**Comment by Eiminyang** [comment]
卧槽，本来就是装装B ，想让你消失，问你要钱了吗，你这个币上次找我发币我就没同意，17年末就瞎几把编了白皮书，我现在电脑里可能还有你之前的白皮书，现在就是改了个封面而已，你们后来不是想去做矿厂，怎么，还想来发个空气币割韭菜吗，你能ICO，我第一个举报，看怎么抓你，ASSET也是你有资源随便上链，国家搞这个也就会是无币区块链，白皮书麻烦下次多花点钱。。。。

**Comment by tstt** [comment]
你好,
我们工作人员会尽快处理。
