### ISSUE TITLE
pull request #1142已经显示成功了，为什么imToken2.0上我还是搜索不到这个合约？

### ISSUE THREAD

**Issue by yan253319066** [consenlabs/token-profile#1159]
您好，如题，请帮忙看下。

**Comment by yan253319066** [comment]
多久在token profile上能看到啊？

**Comment by plusor** [comment]
https://github.com/consenlabs/token-profile/blob/master/erc20/0xaab29ecc3783acb436a6679919f22d30932e93f2.json

这个提交了一个多月过去了， 2.0都搜不到， 邮件也发了， issue关了我好几个

**Comment by tstt** [comment]
你好,
请稍等，我们会进行检查。
