### ISSUE TITLE
imToken中关于HER的图标在列表中无法正常显示，在详情页面可以正常显示，外部列表logo不能显示

### ISSUE THREAD

**Issue by kedavra** [consenlabs/token-profile#1169]
请不要回复固定格式的回答然后直接close，这边需要的是真正的解决方法。

**Comment by plusor** [comment]
https://github.com/consenlabs/token-profile/issues/741
https://github.com/consenlabs/token-profile/issues/135

全给我关闭了，  就是不给解决
