### ISSUE TITLE
麻烦合并一下#1198

### ISSUE THREAD

**Issue by wzqnpu33** [consenlabs/token-profile#1199]
多谢审核的人员 @ashchan

**Comment by wenyanwang** [comment]
请提供PR链接。

**Comment by wzqnpu33** [comment]
https://github.com/wzqnpu33/token-profile/tree/FYC @wenyanwang

**Comment by wzqnpu33** [comment]
https://github.com/consenlabs/token-profile/pull/1198 @wenyanwang  多谢

**Comment by tstt** [comment]
你好,
已收到，稍等。
