### ISSUE TITLE
大佬们 请求合并 #1253 拜托！

### ISSUE THREAD

**Issue by liuzhen888** [consenlabs/token-profile#1286]

**Comment by jywilhn** [comment]
由于以太坊代币种类多，添加代币工作量大，请耐心等待，感谢你的支持和理解，谢谢。

**Comment by tstt** [comment]
你好,
稍等，正在处理。

**Comment by liuzhen888** [comment]
这边是出什么问题了么 还没合并

在 2018-07-26 10:55:48，"tstt" <notifications@github.com> 写道：


你好,
稍等，正在处理。
