### ISSUE TITLE
代币KEC（合约：0xD089966FFDe882D7955375898443f0fFC7FA06A1）信息已提交，烦请处理一下

### ISSUE THREAD

**Issue by kingecvip** [consenlabs/token-profile#1289]
代币KEC信息已成功上传提交github，合约地址是：0xD089966FFDe882D7955375898443f0fFC7FA06A1。目前Imtoken上面还是搜索不到，烦请审核处理，谢谢

**Comment by jywilhn** [comment]
由于以太坊代币种类多，添加代币工作量大，请耐心等待，感谢你的支持和理解，谢谢。

**Comment by tstt** [comment]
你好,
稍等，正在处理。
