### ISSUE TITLE
烦请通过审核

### ISSUE THREAD

**Issue by siutung** [consenlabs/token-profile#1292]
你好，我们的代币合约地址为：0xD4bDBBB9c3d221Ef59624Eb25F3eE84970E713e2
币种名称：LCR
信息已经提交。
不知道现在审核到哪一步了，提交的信息是否存在错误？
烦请回复，若没有错误的信息，还请尽快通过审核为感！
多谢了！

**Comment by jywilhn** [comment]
由于以太坊代币种类多，添加代币工作量大，请耐心等待，感谢你的支持和理解，谢谢。

**Comment by tstt** [comment]
你好,
请稍等，正在处理。
