### ISSUE TITLE
申请合并#1125

### ISSUE THREAD

**Issue by smart-gear** [consenlabs/token-profile#1298]
已经有些天了

**Comment by smart-gear** [comment]
[https://github.com/consenlabs/token-profile/pull/1125](PR链接)

**Comment by smart-gear** [comment]
[PR链接#1125](https://github.com/consenlabs/token-profile/pull/1125)

**Comment by jywilhn** [comment]
由于以太坊代币种类多，添加代币工作量大，请耐心等待，感谢你的支持和理解，谢谢。

**Comment by tstt** [comment]
你好,
请稍等，工作人员正在处理。
