### ISSUE TITLE
hx 的代币显示有问题

### ISSUE THREAD

**Issue by lege** [consenlabs/token-profile#1300]
你好，hx的代币在 imtoken1.0 软件里面显示是hx6 , 在imtoken2.0里面显示是hx, 可以统一显示为 hx 吗？

合约地址为：
0x9888e6f8fcf52a21d3d78f66cc20af5d046d83d7

**Comment by jywilhn** [comment]
你好，请仔细阅读该文章，会对imToken 代币收录、重名及修改名称等问题有清晰的理解哦 
https://help-center.token.im/hc/article/360007261813

**Comment by tstt** [comment]
你好,
请稍等，工作人员正在处理。
