### ISSUE TITLE
请求合并#1322

### ISSUE THREAD

**Issue by dsyang1** [consenlabs/token-profile#1327]
辛苦了，帮忙合并一下#1322

**Comment by jywilhn** [comment]
由于以太坊代币种类多，添加代币工作量大，请耐心等待，感谢你的支持和理解，谢谢。

**Comment by jywilhn** [comment]
由于以太坊代币种类多，添加代币工作量大，请耐心等待，感谢你的支持和理解，谢谢。

**Comment by tstt** [comment]
你好,
请稍等，工作人员正在处理。
