### ISSUE TITLE
imtoken1.0的logo不显示，默认logo也消失了

### ISSUE THREAD

**Issue by admin-celeschain** [consenlabs/token-profile#1367]
Hi，

PR #1110 合并后，发现在imtoken 2.0上可以显示logo， 但imtokne 1.0 的logo消失了，默认logo也不显示了。 请帮忙将logo也显示在imtokne1.0吧

谢谢

**Comment by tstt** [comment]
你好,
请稍等，我们会检查的

**Comment by admin-celeschain** [comment]
你好，

imtoken1.0版的图标还是没有显示！！ 麻烦帮忙再检查一下吧。 谢谢！！
