### ISSUE TITLE
麻烦合并

### ISSUE THREAD

**Issue by ValPromise** [consenlabs/token-profile#1375]
你好，我们的代币合约地址为：0x4d2c05109a1309c6de0d3b7f06f397c9c41b8fae
币种名称：VPP
信息已经提交。
不知道现在审核到哪一步了，提交的信息是否存在错误？
烦请回复，若没有错误的信息，还请尽快通过审核为感！
多谢了！

**Comment by tstt** [comment]
你好,
请稍等，如有问题，我们会有通知。
