### ISSUE TITLE
token已经添加logo不显示

### ISSUE THREAD

**Issue by aiecology** [consenlabs/token-profile#1427]
#1227 请帮忙查看一下 非常感谢

**Comment by wenyanwang** [comment]
由于以太坊代币种类多，添加代币工作量大，同时为了避免误导部分 imToken 用户，我们暂时只添加社区内相对流行（有交易所收录，比如币安）的代币 logo 。但是我们暂时不添加贵团队的代币 logo 完全不影响代币的转账，只要贵方的代币是基于以太坊的 ERC 20标准代币，imToken 都是支持的。
