### ISSUE TITLE
imtoken2.0为什么添加token后，无法显示logo

### ISSUE THREAD

**Issue by pskykingit** [consenlabs/token-profile#145]
添加token后，页面没有显示token的logo图片，但是进入详情页可以看到token的logo

![img_0007](https://user-images.githubusercontent.com/35945946/41226726-f4fc5256-6da4-11e8-8aea-ccd0acefa8f9.PNG)
![img_0008](https://user-images.githubusercontent.com/35945946/41226780-1dab02ba-6da5-11e8-9d2c-1fc8dc836763.PNG)

**Comment by netpi** [comment]
同问

**Comment by likeqin86** [comment]
同问啊，公司的代币LOGO不显示，这是怎么回事？？

**Comment by plusor** [comment]
@kaichen logo 没显示会影响到国际版？我按照国际版添加 token 的方式向贵公司发送了一封邮件，但给我的反馈是往这个 repo 提交 token 信息，我已经在这提交过，真不知道应该是以谁说的为准！

**Comment by MrLiuYong** [comment]
我已经往repo里面提交了信息，也给我回复，已经添加代币了，为什么我在imtoken上面还是搜索不到，代币名称是ex,合约地址是：0xA5a15631Eb0aa1D178cf2D2C6BEc7732A80eAB03
