### ISSUE TITLE
请求增加币种

### ISSUE THREAD

**Issue by siutung** [consenlabs/token-profile#1505]
您好！
请求增加币种LCR（希望能在IMTOKEN的APP里面可以搜到LCR）。
代币名称：LCR
合约地址：0xD4bDBBB9c3d221Ef59624Eb25F3eE84970E713e2
已将币种信息按要求（json文件上传至erc20目录，png文件上传至images目录）提交（第一次整，不知道有没有错误）。
而且看到有下列提示：

**Merged**	wenyanwang merged 5 commits into consenlabs:master from siutung:LCR 4 days ago

Pull request successfully merged and closed
You’re all set—the siutung:LCR branch can be safely deleted.

如果有错误，请及时告之，如果没有，有时间的话，烦请尽快通过审核。
多谢啦！
在线等结果....

**Comment by siutung** [comment]
在这里发贴子，到底官方管理员能看到么？
无论我的问题对不对，如果官方管理员看到了，请给个回复。

**Comment by wenyanwang** [comment]
你好，按照操作教程提交资料，并在提交的PR链接下向我们留言，谢谢。
