### ISSUE TITLE
logo不显示

### ISSUE THREAD

**Issue by lindong58** [consenlabs/token-profile#1516]
合约地址0x5403d3AC289322C482cD558014ea3888EF1B1d44
代币名称SUPT

问题：logo不显示，空白的

**Comment by hldzlk** [comment]
## 建议项目方不要直接把issue全部关闭
可以留一个描述相对全面的issue，把其余重复的issue关闭并指引到这个issue上
这样有相同问题的开发者都可以在这个issue下留言
不仅能根据讨论数量看出issue的影响面，也可以适当避免同一个问题出现一堆issue的局面

### imtoken1.0 logo不显示，imtoken2.0代币搜索不到
相同问题 #1003

**Comment by himyway2018** [comment]
这个问题我能解决，加微信duanchenrhi

**Comment by wenyanwang** [comment]
0xb9f84239fdbc4043824b268ba7508139a16757ae

**Comment by wenyanwang** [comment]
请查看提交的PR链接下的回复。
由于以太坊代币种类多，添加代币工作量大，同时为了避免误导部分 imToken 用户，我们暂时只添加社区内相对流行（有交易所收录，比如币安）的代币 logo 。但是我们暂时不添加贵团队的代币 logo 完全不影响代币的转账，只要贵方的代币是基于以太坊的 ERC 20标准代币，imToken 都是支持的。

**Comment by alpharothschild** [comment]
请问一下，代币合约的地址如何查询？
