### ISSUE TITLE
token名称显示错误

### ISSUE THREAD

**Issue by cathy33** [consenlabs/token-profile#1520]
你好，我们是gamecell团队我们的token名称是GCC
合约地址为0x500565e098d98a273224ec8fb33d98dc8946f8b9
相关报道:金色财经-https://m.jinse.com/bitcoin/219320.html

代币在钱包中显示为GCC16,给我们的用户带来了很大困扰，请尽快帮我们解决，谢谢

**Comment by wenyanwang** [comment]
你好，按照操作教程提交资料，并在提交的PR链接下向我们留言，谢谢。
