### ISSUE TITLE
ITEC Token已合并，存在几个问题希望可以帮忙解决

### ISSUE THREAD

**Issue by ITEChainAdmin** [consenlabs/token-profile#1551]
Add ITEC Token [#1446](!https://github.com/consenlabs/token-profile/pull/1446)已合并，存在几个问题如下：
1.imtoken2.0搜索ITEC搜索不到token；
2.根据合约地址可以搜索到token，但是不显示logo图标；但发现Token Profile里已显示图标及相关信息；
3.imtoken1.0也未显示logo图标，并希望将token名称ITEC(Travel)改为ITEC。

希望可以帮忙解决上述问题，谢谢！

**Comment by himyway2018** [comment]
这个问题我能解决，加微信duanchenrhi

**Comment by wenyanwang** [comment]
你好，按照操作教程提交资料，并在提交的PR链接下向我们留言，谢谢。
