### ISSUE TITLE
PR已经merge，代币显示问题

### ISSUE THREAD

**Issue by ITEChainAdmin** [consenlabs/token-profile#1561]
你好，已经按照教程操作提交资料，提交的Add ITEC Token #1446  PR已经显示merge，仍存在几个问题如下：
1.imtoken1.0也未显示logo图标，并希望将token名称ITEC(Travel)改为ITEC；
2.imtoken2.0搜索ITEC搜索不到token；
3.根据合约地址可以搜索到token，但是不显示logo图标；但发现Token Profile里已显示图标及相关信息。

希望可以帮忙解决上述问题，谢谢！

**Comment by siutung** [comment]
我的也是这个问题，不知道该怎么解决。

**Comment by wenyanwang** [comment]
@ITEChainAdmin 同事正在检查系统，请耐心等待，感谢你的支持，谢谢。
