### ISSUE TITLE
jouann token 代币提交

### ISSUE THREAD

**Issue by asce123** [consenlabs/token-profile#1562]
你好 jouann代币 已经通过github提交 请问什么时候会有结果？

**Comment by makoshan** [comment]
请提供完整的代币资料，为了加速显示进度，请尽可能向我们提供完善的项目资料，以及知名区块链媒体报道，包括但不限于以下内容，以便 imToken 团队更了解你们的项目。

团队背景：
项目基本情况:
媒体报道：
推荐用户转账所使用的 Gas 数量（没有提供，我们默认值 60000）
PR 示例：
https://github.com/consenlabs/token-profile/pull/1636
