### ISSUE TITLE
ios版imtoken1.0不显示token图标

### ISSUE THREAD

**Issue by admin-celeschain** [consenlabs/token-profile#1564]
Hi，

PR #1110 合并后，发现在imtoken 2.0上可以显示logo， 但ios的imtokne 1.0 的cchn token的logo消失了，默认logo也不显示了。 请帮忙将logo也显示在imtokne1.0吧

**Comment by hldzlk** [comment]
imtoken1.0 图标不显示，imtoken2.0代币搜索不到  #1516  #1003

**Comment by wenyanwang** [comment]
请查看提交的PR链接下的回复，谢谢。
