### ISSUE TITLE
更新INVE token信息 

### ISSUE THREAD

**Issue by ClareLau61803** [consenlabs/token-profile#1591]
https://github.com/consenlabs/token-profile/pull/1590

1. 在imtoken2.0中可以用合约地址搜索添加，但是无法用INVE搜索到结果，请求更新
2. 麻烦更新下imtoken2.0手机端INVE token图标

谢谢。 @ashchan @kaichen @beenhero @sorccu @guanqun

**Comment by ClareLau61803** [comment]
[20180807 imtoken InterValue项目介绍.docx](https://github.com/consenlabs/token-profile/files/2265178/20180807.imtoken.InterValue.docx)

**Comment by ClareLau61803** [comment]
[20180807 imtoken   @@InterValue项目介绍.docx](https://github.com/consenlabs/token-profile/files/2265180/20180807.imtoken.InterValue.docx)
这是我们项目的情况介绍，请查看，谢谢！
@ashchan @kaichen @beenhero @sorccu @guanqun

**Comment by ClareLau61803** [comment]
https://github.com/consenlabs/token-profile/issues/1590
团队背景：
InterValue项目团队当前共计近90人，开发人员约55人（博士25人）。项目创始人Barton Chao及核心成员多为中国著名高校计算机科学与技术专业博士和工业界核心架构师。大部分成员曾在中国著名高校从事科研工作，在区块链技术领域均有较深研究，包括分布式计算、P2P网络、分布式一致性达成、形式化验证、编译原理、网络安全、密码学、隐私保护等。部分团队成员在IBM、百度、新浪、腾讯等工作经历较为丰富。团队作为技术提供方曾开发并交付近20个区块链相关应用项目。
总之，团队在理论研究、关键技术攻关、核心算法实现，项目工程实现及交付等方面均有丰富经验，能够支撑InterValue的整个开发，当前项目进展情况也证明了团队各方面的实力。

项目基本情况：
InterValue是全球首个支撑并实现百万实测TPS的实用化区块链4.0项目，是以构建下一代全球价值互联网基石、构建行业公链底层基础设施为目标的高实用性去中心化分布式应用开发平台。
性能层面：通过自行设计并实现的基于DAG的HashNet共识机制实现单个分片TPS突破28万，全网实测TPS突破400万，在区块链公链技术领域处于顶尖水平（现阶段全球第一）。
可用性和易用性层面：跨链通信和多链融合、设计并实现行业支撑层、设计并实现智能合约的链下数据访问。
安全性层面：智能合约代码的形式化验证、加密算法和哈希函数的抗量子攻击、基于零知识证明和环签名的交易匿名技术、P2P网络节点通信匿名技术。后两个特性由于性能原因，作为可选功能。
	官网：http://www.inve.one/
	币用中文：https://0.plus/intervalue
	Telegram: https://t.me/InterValueProject
	Twitter: https://twitter.com/intervaluepro
	Facebook: https://www.facebook.com/InterValueofficial

媒体报道：
	36Kr
InterValue想利用DAG和双层网络结构，提高通用型公链性能
http://36kr.com/p/5134737.html

	金色财经
InterValue：打造支撑百万量级TPS的实用化区块链4.0基础设施https://www.jinse.com/bitcoin/220603.html
5000万INVE等你来拿！全球首个支撑百万量级TPS公链——InterValue启动糖果空投https://www.jinse.com/bitcoin/214247.html
InterValue 2.0测试链启动首次全球内测局部全节点、轻节点招募
https://www.jinse.com/bitcoin/207324.html
InterValue 2.0测试版携HashNet共识重装上线，矢志打造实用化区块链4.0基础设施
https://www.jinse.com/bitcoin/206947.html

	搜狐网
当大家都在谈论区块链3.0时，区块链4.0已悄然开启！
http://www.sohu.com/a/228531619_100111931

	新浪网
公有链将把区块链带入4.0时代？
http://finance.sina.com.cn/stock/t/2018-05-11/doc-ihamfahw4348850.shtml

	CSDN
InterValue互联价值：创造真正的区块链4.0时代
https://www.csdn.net/article/a/2018-05-09/15948037

	icodrops
InterValue (Blockchain)
https://icodrops.com/intervalue/

	Youtube—The Crypto Sphere
InterValue ICO Review - Blockchain 4.0 With 200,000+ Tx/s
https://www.youtube.com/watch?v=IwffFOn0Rm0

	icogens.com
InterValue (Blockchain)
https://icogens.com/intervalue?lang=en
[ICO REVIEW]- What is InterValue? What is blockchain 4.0? Is it the next seele again?
https://icogens.com/ico-review-what-is-intervalue-what-is-blockchain-4-0-is-it-the-next-seele-again?lang=en

	GlobeNewswire
InterValue’s TestNet 2.0 release: implementation of HashNet consensus, committed to building the practical infrastructure of the Blockchain 4.0 era
https://globenewswire.com/news-release/2018/06/28/1531189/0/en/InterValue-s-TestNet-2-0-release-implementation-of-HashNet-consensus-committed-to-building-the-practical-infrastructure-of-the-Blockchain-4-0-era.html

	Deer Park Tribune - Financial Content
InterValue v2.0 testnet launch - First global recruitment of local full node and light node alpha test
http://markets.financialcontent.com/dptribune/news/read/36546130/intervalue_v2.0_testnet_launch_

	KFMB-TV CBS-8
InterValue: Barton Chao - How to lead a group of PhDs to accelerate the switch to blockchain 4.0 era
http://www.cbs8.com/story/38803808/intervalue-barton-chao-how-to-lead-a-group-of-phds-to-accelerate-the-switch-to-blockchain-40-era

@ashchan @kaichen @beenhero @sorccu @guanqun

**Comment by sorccu** [comment]
Please stop mentioning me, I am not affiliated with the project.

**Comment by ClareLau61803** [comment]
更新到 https://github.com/consenlabs/token-profile/pull/1734  
麻烦处理下，谢谢。

**Comment by wenyanwang** [comment]
请在提交的PR链接下方留言，谢谢。
