### ISSUE TITLE
提交FairyCoin审核

### ISSUE THREAD

**Issue by wzqnpu33** [consenlabs/token-profile#1599]
https://github.com/consenlabs/token-profile/pull/1598
1、在imtoken2.0中可以用合约地址搜索添加，但是无法用FYC搜索到结果，请求更新
2、麻烦更新下imtoken2.0手机端FYC图标
@ashchan @kaichen @beenhero @sorccu @guanqun

**Comment by sorccu** [comment]
Please stop pinging me in new issues, I’m not affiliated with the project.

**Comment by wenyanwang** [comment]
公告 | imToken 代币收录、重名及修改名称等问题说明
https://support.token.im/hc/zh-cn/articles/360007261813-%E5%85%AC%E5%91%8A-imToken-%E4%BB%A3%E5%B8%81%E6%94%B6%E5%BD%95-%E9%87%8D%E5%90%8D%E5%8F%8A%E4%BF%AE%E6%94%B9%E5%90%8D%E7%A7%B0%E7%AD%89%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E
