### ISSUE TITLE
代币KEC信息已经提交，请问什么时候可以处理

### ISSUE THREAD

**Issue by kingecvip** [consenlabs/token-profile#1605]
代币KEC信息已经提交，合约地址是：0xD089966FFDe882D7955375898443f0fFC7FA06A1。

**Comment by nyuspc** [comment]
你这么着急没用的，他们好像一周才处理一次

**Comment by makoshan** [comment]
请参考我们的模版教程提交资料，为了加速显示进度，请尽可能向我们提供完善的项目资料，以及知名区块链媒体报道，包括但不限于以下内容，以便 imToken 团队更了解你们的项目。

团队背景：
项目基本情况:
媒体报道：
推荐用户转账所使用的 Gas 数量（没有提供，我们默认值 60000）
PR 示例：
https://github.com/consenlabs/token-profile/pull/1636
