### ISSUE TITLE
烦请管理员协助排解问题原因并合并

### ISSUE THREAD

**Issue by siutung** [consenlabs/token-profile#1629]
PR链接：
https://github.com/consenlabs/token-profile/pull/1601

请管理员协助解决为感！

**Comment by wenyanwang** [comment]
请按照操作教程提交信息，删除多余的文件，谢谢。

**Comment by siutung** [comment]
@wenyanwang 已删除多余的文件，烦请合并，多谢！

**Comment by yyy999** [comment]
请问多余文件指其它的json文件么

**Comment by siutung** [comment]
@wenyanwang 请帮忙看看，是否还有问题？如果有问题，请帮忙指出（本人小白）。如果没有问题的话，烦请帮忙合并，多谢了！

**Comment by makoshan** [comment]
请参考提交 PR 的教程：https://www.jianshu.com/p/d921828bf623
