### ISSUE TITLE
使用EOS平台，产生的Token，能接入到imtoken吗？

### ISSUE THREAD

**Issue by Mike2100** [consenlabs/token-profile#1633]
不是ERC20
不是ERC20
不是ERC20
在EOS上发行的Token，不是EOS币
在EOS上发行的Token，不是EOS币
在EOS上发行的Token，不是EOS币
能接入到imtoken钱包吗？

**Comment by wenyanwang** [comment]
imToken 支持EOS token

**Comment by makoshan** [comment]
自主提交的 EOS Token 的功能，我们已经在开发
