### ISSUE TITLE
代币HMT始终没有更新 

### ISSUE THREAD

**Issue by yyy999** [consenlabs/token-profile#1691]
0xa6fa96379b1cf3fe1f018e98ee57b418c56e74d3.json

**Comment by wenyanwang** [comment]
公告 | imToken 代币收录、重名及修改名称等问题说明
https://support.token.im/hc/zh-cn/articles/360007261813-%E5%85%AC%E5%91%8A-imToken-%E4%BB%A3%E5%B8%81%E6%94%B6%E5%BD%95-%E9%87%8D%E5%90%8D%E5%8F%8A%E4%BF%AE%E6%94%B9%E5%90%8D%E7%A7%B0%E7%AD%89%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E
