### ISSUE TITLE
请问如何更改代号的名称

### ISSUE THREAD

**Issue by dmsggg** [consenlabs/token-profile#1693]
我们添加token后，申请时候填写的代号是ASC, 合并后发现名字后面被添加了数字: ASC21, 可否去掉后面的数字呢？怎么操作？ #1570 
感谢管理员！

**Comment by wenyanwang** [comment]
公告 | imToken 代币收录、重名及修改名称等问题说明
https://support.token.im/hc/zh-cn/articles/360007261813-%E5%85%AC%E5%91%8A-imToken-%E4%BB%A3%E5%B8%81%E6%94%B6%E5%BD%95-%E9%87%8D%E5%90%8D%E5%8F%8A%E4%BF%AE%E6%94%B9%E5%90%8D%E7%A7%B0%E7%AD%89%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E
