### ISSUE TITLE
JOUANN代币名称显示问题

### ISSUE THREAD

**Issue by asce123** [consenlabs/token-profile#1709]
你好，已经按照教程操作提交资料，提交的PR提交并已经merge 现存在一个问题：

提交的token名称为 JOUANN 但是显示为$34 。

说明：目前我们的Token还没有进行发放，还没有使用的用户，我们也是希望等待贵公司的修改完成之后，才进行代币的正式流通。

希望可以解决上述问题，谢谢！

**Comment by wenyanwang** [comment]
你好，你们在etherscan显示是这样，系统自动抓取，谢谢。
