### ISSUE TITLE
initial_price的问题

### ISSUE THREAD

**Issue by eggacher** [consenlabs/token-profile#1745]
"initial_price":{
        "ETH":"0.00166666 ETH",
        "USD":"0.7 USD",
        "BTC":"0.00004137 BTC"
  }

在提交上币申请的时候，有这样一段配置。
请问：
1、目前我们没有上交易所，对这个值目前也没有概念，可以不填吗？或者直接填 0？
2、后期是否可以更改？

**Comment by wenyanwang** [comment]
没有的信息可以不填写，以后可以在补全。
