### ISSUE TITLE
第三方APP如何接入imToken支付功能？

### ISSUE THREAD

**Issue by joseshiang** [consenlabs/token-profile#1773]
最近有一个项目，需求是支持比特币、以太币支付，但在阅读imToken SDK后没有找到如何接入，谢谢!

**Comment by wenyanwang** [comment]
你好，

imToken 支持接入 DApp 进行支付，在官网已经提供了全部的 API。

如果要进行商务合作，请发送邮件到 bd@consenlabs.com 提供项目的详细资料。

**Comment by joseshiang** [comment]
[image: image.png]
麻烦问下，图中imToken这个对象怎么才能获取到？商务合作需要提供那些资料，能给个联系方式吗？微信或者QQ,昨天下午给已经给
bd@consenlabs.com 发过邮件了现在还没有回复。谢谢！

Weli <notifications@github.com> 于2018年8月9日周四 下午3:51写道：
