### ISSUE TITLE
关于DApp-SDK中“imToken”对象如何获取？

### ISSUE THREAD

**Issue by joseshiang** [consenlabs/token-profile#1787]
![image](https://user-images.githubusercontent.com/19600894/43887236-bda222f2-9bf0-11e8-8d60-2ba3d125d615.png)
图中“imToken”这个对象是怎么获取到的？我要引用什么才能在自己项目也可以使用imToken这个对象，并且通过调用API使用比特币支付、以太币支付这些功能？

**Comment by wenyanwang** [comment]
你好，

imToken 支持接入 DApp 进行支付，在官网已经提供了全部的 API。

如果要进行商务合作，请发送邮件到 bd@consenlabs.com 提供项目的详细资料。
