### ISSUE TITLE
在imtoken中不显示logo

### ISSUE THREAD

**Issue by wangtleric** [consenlabs/token-profile#1894]
已经提交了logo图片 ：  #1108 

但是在imtoken中不显示logo，请麻烦帮忙解决下，3Q

Token合约地址是：0xcbf011af08fadda5736bf5e645dbbfb149dc5d68

**Comment by makoshan** [comment]
你好，请提供更多项目信息，包括官网，并在这里向我们提供主流区块链媒体报道，谢谢。参考 #1636
