### ISSUE TITLE
0x0b6bc42cb9b89259a3aa986363fa37a9cbf03b8e.json文件里的address格式错误，导致其他文件传不上去

### ISSUE THREAD

**Issue by williamcarry** [consenlabs/token-profile#199]
Network availability confirmed.
git.checkout
0.96s$ git clone --depth=50 https://github.com/consenlabs/token-profile.git consenlabs/token-profile
Cloning into 'consenlabs/token-profile'...
remote: Counting objects: 2819, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 2819 (delta 12), reused 3 (delta 0), pack-reused 2799
Receiving objects: 100% (2819/2819), 3.62 MiB | 16.68 MiB/s, done.
Resolving deltas: 100% (2072/2072), done.
$ cd consenlabs/token-profile
0.46s$ git fetch origin +refs/pull/194/merge:
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 29 (delta 19), reused 12 (delta 7), pack-reused 0
Unpacking objects: 100% (29/29), done.
From https://github.com/consenlabs/token-profile
 * branch            refs/pull/194/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
$ export PATH=./node_modules/.bin:$PATH
Updating nvm
nvm.install
2.85s$ nvm install 9.3.0
Downloading and installing node v9.3.0...
Downloading https://nodejs.org/dist/v9.3.0/node-v9.3.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v9.3.0 (npm v5.5.1)
cache.1
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.14s$ Installing caching utilities
0.00s
5.72sattempting to download cache archive
fetching PR.194/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-9.3.0.tgz
fetching PR.194/cache--node-9.3.0.tgz
fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-9.3.0.tgz
fetching master/cache--node-9.3.0.tgz
could not download cache
0.00s
1.14sadding /home/travis/build/consenlabs/token-profile/node_modules to cache
creating directory /home/travis/build/consenlabs/token-profile/node_modules
$ node --version
v9.3.0
$ npm --version
5.5.1
$ nvm --version
0.33.11
install.npm
1.06s$ npm install 
npm notice created a lockfile as package-lock.json. You should commit this file.
added 8 packages in 0.658s
0.46s$ npm ls
token-profile@1.0.0 /home/travis/build/consenlabs/token-profile
├─┬ chalk@2.4.1
│ ├─┬ ansi-styles@3.2.1
│ │ └─┬ color-convert@1.9.2
│ │   └── color-name@1.1.1
│ ├── escape-string-regexp@1.0.5
│ └─┬ supports-color@5.4.0
│   └── has-flag@3.0.0
└── pngjs@3.3.3
0.35s$ npm test
> token-profile@1.0.0 test /home/travis/build/consenlabs/token-profile
> node ./test/index.js
ERROR! json file 0x0b6bc42cb9b89259a3aa986363fa37a9cbf03b8e.json address field must be an ethereum address
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache

**Comment by ArtChainGlobal** [comment]
same issue

**Comment by kaichen** [comment]
That's an invalid char there, fixed at https://github.com/consenlabs/token-profile/commit/fab8baeadf23b0a7f698ec34682ad34f33f65b73

**Comment by tocoffcial** [comment]
hello 我也遇到同样问题 我在github网页上直接修改了contract address 然后提交申请，结果测试失败。
我是直接复制address 新的地址替换的 是不是有什么问题
