### ISSUE TITLE
logo前几天能正常显示，最近发现不能显示

### ISSUE THREAD

**Issue by guoPengSong** [consenlabs/token-profile#1990]
已经提交了logo图片 [#1819](https://github.com/consenlabs/token-profile/pull/1819)：
但是在imtoken中不显示logo，请麻烦帮忙解决下，谢谢
Token合约地址是：0x9746953f5b1324a78132895cfd263f417b0faae3

**Comment by wenyanwang** [comment]
提交PR链接

**Comment by alpharothschild** [comment]
token合约地址应该如何查询？

**Comment by wenyanwang** [comment]
请提供提交的PR链接
