### ISSUE TITLE
如何提交申请时，设置token的名字

### ISSUE THREAD

**Issue by howeguo** [consenlabs/token-profile#2024]
我看erc20模板文件里只有一个symbol字段，比如我的symbol叫“ABC” 但是我的名字叫“ABChain”

**Comment by wenyanwang** [comment]
公告 | imToken 代币收录、重名及修改名称等问题说明
https://help-center.token.im/hc/article/360007261813

**Comment by howeguo** [comment]
我看您给的连接教程里是如何改symbol的，但我不是要改symbol，我想修改的是图中的红色部分，请问这种如何修改，多谢！
![image](https://user-images.githubusercontent.com/3302533/44451158-7b73fd80-a625-11e8-9470-1d79d5497140.png)

**Comment by wenyanwang** [comment]
系统自动发现etherscan，请检查etherscan上的信息
