### ISSUE TITLE
更改代币显示名称

### ISSUE THREAD

**Issue by calfcamel** [consenlabs/token-profile#2025]
您好，
    我是EOT代币的运营人员，现在我们想要修改EOT代币的显示名称，在填写github资料的时候，需要填写overview，我们想知道是否有字数限制？以及最佳的字数是多少？中文英文的字数要求都是一样的吗？

**Comment by wenyanwang** [comment]
公告 | imToken 代币收录、重名及修改名称等问题说明
https://help-center.token.im/hc/article/360007261813
