### ISSUE TITLE
添加JW

### ISSUE THREAD

**Issue by jwbcio** [consenlabs/token-profile#2034]
企业网站：jwbc.io 
电子邮件：info@jwbc.io
地址：0xbe184e10f8a64f5f540a0f98e5b58d3377d36a74 
token：JW
项目信息：
Jewelry Chain是通过区块链技术打造的一条开放主链，专注于解决珠宝爱好者手中藏品无法快速，有效变现的现状，收集全球珠宝存量的底层数据，创建开放的环境。整个生态以智能合约和自有链Jewelry Chain为核心，构建了所有者，购买者，生产者，服务提供者和技术开发者共同参与的分布式平台，
主流媒体报道：
凤凰网https://biz.ifeng.com/a/20180730/45091698_0.shtml
搜狐https://www.sohu.com/a/243852116_99995748
中华网的https：//m.tech.china的.com / redian / 2018/0728 / 172554.html
农历财经新闻网http://www.prcfe.com/finance/2018/0731/270485.html

**Comment by jwbcio** [comment]
文件我都做好了，不知道去哪里提交和拉新，请大神指导一些，万分感谢

**Comment by wenyanwang** [comment]
公告 | imToken 代币收录、重名及修改名称等问题说明
https://help-center.token.im/hc/article/360007261813
