### ISSUE TITLE
你好 这不是重复提交  这是我们另一个token   - ATC （区别于之前的ATP）

### ISSUE THREAD

**Issue by yueshenliyang** [consenlabs/token-profile#2098]
你好 这不是重复提交  这是我们另一个token   - ATC （区别于之前的ATP）
虽然ATP（#2011）已处理，但我们的另一个token - ATC #2019  还没有处理，您给close了，麻烦赶紧处理一下  已经一周了

===============

Weli （ConsenLabs）
8月23日 CST16:26

你好，

重复提交
https://github.com/consenlabs/token-profile/pull/2011
已经处理

你好 虽然ATP（#2011）已处理，但我们的另一个token - ATC #2019  还没有处理，您给close了，麻烦赶紧处理一下  已经三四天了

提交token - ATC #2019
https://github.com/consenlabs/token-profile/pull/2019

麻烦赶紧处理一下  已经三四天了
谢谢

**Comment by wenyanwang** [comment]
你好，重新提交一次PR，并在留言区说清楚，谢谢。
