### ISSUE TITLE
1.0版本logo不显示，2.0版本有显示

### ISSUE THREAD

**Issue by wsljmxs** [consenlabs/token-profile#2099]
你好，1.0版本的logo不显示，2.0的有显示，请问是什么问题，谢谢。
Token合约地址是：0x59953e3699c22ef9c4c4a97cec0b7c7dcb8143e8

**Comment by alpharothschild** [comment]
请问如何提交LOGO？比如下载完整的Gituhb信息以后，如何进行修改信息，然后如何上传LOGO信息？

**Comment by alpharothschild** [comment]
你们有没有及时通讯工具：qq号或者微信号之类的，可以聚集我们做长期imtoken的技术合作。

**Comment by victorymen** [comment]
你好，1.0版本的logo不显示，2.0的有显示，请问是什么问题，谢谢。
Token合约地址是：0x33bfd20660eeaf952e8d5bc3236e1918701f17d0

**Comment by zhangmaku** [comment]
您好，1.0版本不显示logo，2.0显示
合约地址：0xd8062c267dd196b5e500a99ead7f50592f323e51

**Comment by ogt-redknie** [comment]
您好，为什么1.0可以查询到代币，dragoncoin 简称DC，0x31ead6a10b5215321afa8bef2f05aa271508fa6c
2.0搜索不到？

**Comment by 02081993** [comment]
你好，1.0版本的logo不显示，2.0的有显示，请问是什么问题，谢谢。
Token合约地址是：
0x6dcC50aF7F75093AA9db94c56b857F02f7e4115F

**Comment by tstt** [comment]
@02081993 这个代币在 1.0 和 2.0 都没有 logo 显示，按照教程：https://github.com/consenlabs/token-profile#token-profile-guideline 提交 pr 即可。
