### ISSUE TITLE
etherscan已经更新我们合约信息，请imtoken也帮助更新一下！

### ISSUE THREAD

**Issue by walkidea** [consenlabs/token-profile#2142]
我们的合约已在etherscan提交并通过，但在imtoken1.0中symbol显示不对，我们提交的是PCC，但显示的是PCC15。

请麻烦帮我们处理一下，帮我们改成PCC。

我们的用户群很庞大，但因为这名字问题一直不能上线，这对我们十分重要，请一定帮忙处理，拜托了！

etherscan上信息：[https://etherscan.io/token/0x6b7e3c3ad124af008b61d0afe93437d0218a0cf8](url)

**Comment by wenyanwang** [comment]
你好，并不是我们显示错误的问题，代币名称重复就会有数字区别，请阅读此篇说明，谢谢

https://help-center.token.im/hc/article/360007261813
