### ISSUE TITLE
another issue in 0x0b6bc42cb9b89259a3aa986363fa37a9cbf03b8e.json

### ISSUE THREAD

**Issue by ArtChainGlobal** [consenlabs/token-profile#216]
ERROR! json file name 0x0b6bc42cb9b89259a3aa986363fa37a9cbf03b8e.json parse error, please check first (maybe has some unnecessary space or comma symbol like ",")
npm ERR! Test failed.  See above for more details.

这个问题导致 The Travis CI build failed

**Comment by kaichen** [comment]
Fixed
