### ISSUE TITLE
如何在github上上传资料？

### ISSUE THREAD

**Issue by alpharothschild** [consenlabs/token-profile#2207]
团队背景：
FREECOIN整合来自国内顶尖的CDN技术服务人员、大数据行业领先人物，以及WEB前端专业开发等多种技术人才、于2018年8月在上海成立，致力于帮助中小企业发行token，以帮助更多企业快速进入区块链化的时代，让企业的token发行成本，配置成本，运营成本降低到做微信公众平台一样的成本，提高企业的发币效率。

项目基本情况：
FREECOIN是一款基于以太坊智能合约，集成挖矿，token发行，智能合约结算、分布式存储服务。依托于以太坊公链，
FREECOIN的系统帮助中小企业发行token，做币币交易的运营商，轻松解决了行业内的多个棘手问题。

关于更多FREECOIN的信息：
http://www.youxiaozichan.com 

合约地址：
0xd9b5b47ba7cb9115f18639d48015ee370bdfcf09

钱包地址：
0x343c678628ab50B747AcC3e6bCc53dC824a42420

**Comment by wenyanwang** [comment]
https://github.com/consenlabs/token-profile/blob/master/README.zh-CN.md
