### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Adpower1** [consenlabs/token-profile#2320]
where is my logo error? so it's always rejected, help me

![0x957c7090c1e2bbaae73780d657df8132d6f3da9d](https://user-images.githubusercontent.com/43059805/45261965-c7e97680-b436-11e8-9883-d26730d82ec6.png)

**Comment by wenyanwang** [comment]
We added it already, try it again. imToken support all ERC20 tokens, even if the token is not shown on the list, you will be able to receive and send also.

As for the token logos, we have only added tokens which are more popular among the community. If you would like to change the contract address of a specific token, please show us some official announcement.

**Comment by wenyanwang** [comment]
We added it already, try it again. imToken support all ERC20 tokens, even if the token is not shown on the list, you will be able to receive and send also.
