### ISSUE TITLE
BTU token 请管理员审核，感谢！  #3665 passed

### ISSUE THREAD

**Issue by sbuxmmm** [consenlabs/token-profile#2382]
团队背景：
联合创始人具有广泛人币图资源及行业经验，深耕于交易数据分析。 
有多年金融及数据货币交易数据分析经验。
媒体报道： 
https://www.coinex.com/announcement/detail?id=128&lang=zh_Hans_CN 

项目基本情况:
Bitsou(比特搜)是基于区块链、人工智能、大数据技术的数字货币投资决策工具。
区别于其他投资服务平台，Bitsou(比特搜)依托核心数据处理技术和自有核心算法，
为用户提供智能的数字货币投资服务和全面、便捷的信息交流渠道。 

BTU 合约：
0x3c76EF53be46ed2E9bE224e8f0b92e8ACBc24ea0

**Comment by wenyanwang** [comment]
请把相关信息提交在PR留言区，谢谢。
