### ISSUE TITLE
ERROR! json file name 0x0d152b9ee87ebae179f64c067a966dd716c50742.json must be utf-8 encoding npmERR!

### ISSUE THREAD

**Issue by meng-x** [consenlabs/token-profile#2416]
The travic ci is failed due to some json utf-8 encode error:

ERROR! json file name 0x0d152b9ee87ebae179f64c067a966dd716c50742.json must be utf-8 encoding
npmERR! Test failed.  See above for more details.

**Comment by meng-x** [comment]
Multiple PRa seem to be influenced by this stupid error, pls fix it ASAP

**Comment by silverstandard** [comment]
你也是报这个错误了 啊

**Comment by silverstandard** [comment]
me too

**Comment by silverstandard** [comment]
I have the same err

**Comment by wenyanwang** [comment]
请 fork master 分支，重新提交
