### ISSUE TITLE
i cant push my commit,because"0xF41861F194e7Ba8dE95144a89E0C6ed16EE0B3A0.png"

### ISSUE THREAD

**Issue by hardyqin** [consenlabs/token-profile#2450]
error!!! https://travis-ci.org/consenlabs/token-profile/builds/430019069?utm_source=github_status&utm_medium=notification

0xF41861F194e7Ba8dE95144a89E0C6ed16EE0B3A0.png in images dir, that capital and small letter isn't quite the same with 0xF41861F194e7Ba8dE95144a89E0C6ed16EE0B3A0
npmERR! Test failed.  See above for more details.

**Comment by hellochengzhezhixing** [comment]
https://github.com/consenlabs/token-profile/pull/2460
相同的问题，麻烦尽快处理下啊

**Comment by wenyanwang** [comment]
你好，github出现故障，已经修复，请重新提交信息，谢谢。

**Comment by wenyanwang** [comment]
请 fork master 分支，重新提交

**Comment by xwartz** [comment]
Hi, @hardyqin 
We have fixed this issue. Please resubmit it.
