### ISSUE TITLE
安卓版app  新增的token 外层不能显示图标

### ISSUE THREAD

**Issue by hellochengzhezhixing** [consenlabs/token-profile#2470]
![image](https://user-images.githubusercontent.com/43331621/45735799-b6b11e80-bc1b-11e8-8345-a3f447c01527.png)
 
为什么新增的图标外层不能显示提交的图标？
点进去是可以看到的。

**Comment by hellochengzhezhixing** [comment]
@xwartz 你好，在imtoken中已经查到，但是外层的图标还是没有显示出来，点进去是可以看到的，这个能帮忙看下么？png格式的图片大小是120x120的

**Comment by wenyanwang** [comment]
重新提交更新，谢谢。
