### ISSUE TITLE
你好 ，提交老被Closed

### ISSUE THREAD

**Issue by kevinfox163** [consenlabs/token-profile#2476]
你好 ，提交老被打回 
我们卡牌项目的 TCW1，TCW2，TCW3.。。TCWn
这种不能一次提交吗？因为除了地址不同，其他都一样的

#2398. 本身没什么问题吧，能否一次通过一下
ps：能否给个微信 qq 等方式 沟通一下 

谢谢

在 2018-09-15 14:24:12，"Weli" <notifications@github.com> 写道：
Closed #2398.

**Comment by wenyanwang** [comment]
你好，请查看closed掉的PR链接底部回复，我们关闭都会有相应的回复，谢谢。
