### ISSUE TITLE
你好，请提交升级合约公告，说明使用imToken钱包的用户代币改名将会消失，需要重新搜索添加代币，谢谢。

### ISSUE THREAD

**Issue by hanyannan** [consenlabs/token-profile#2526]
_Originally posted by @wenyanwang in https://github.com/consenlabs/token-profile/pull/2487#issuecomment-423478372_

管理员你好，imtoken1.0旧的SE已经消失，而新合约的SE显示不对。IMTOKEN内显示为SE(SwiftExpress),
请管理员把去除(SwiftExpress),，直接显示SE。IMTOKEN2.0不显示LOGO。

**Comment by wenyanwang** [comment]
你好，已经处理。
