### ISSUE TITLE
请求管理员处理代币名称。

### ISSUE THREAD

**Issue by hanyannan** [consenlabs/token-profile#2657]
_Originally posted by @wenyanwang in https://github.com/consenlabs/token-profile/pull/2487#issuecomment-423478372_
管理员你好，SE名称在imtoken1.0显示错误，请求管理员修改。
imtoken1.0显示为SE(SwiftExpress)，实际应该显示为：SE
请求管理员修改。
我们是旧合约更替，旧合约已经更替了old名称。而新合约显示错误。

**Comment by wenyanwang** [comment]
你好，就合约升级，目前贵司持用用户较多，修改后容易引起用户恐慌，请让用户使用2.0版本，不存在代币重名问题，
