### ISSUE TITLE
请管理员帮助看一下HCP提交信息

### ISSUE THREAD

**Issue by wangl271** [consenlabs/token-profile#2660]
已经提交成功，在imtoken2.0里面还是查询不到，不知道还需要什么原因，请帮助看一下

**Comment by wenyanwang** [comment]
你好，留言时请提供提交的PR链接，谢谢

**Comment by wangl271** [comment]
https://github.com/consenlabs/token-profile/pull/2653   这个提交连接

**Comment by wangl271** [comment]
团队背景：
PPStar 团队分布在上海、重庆和贵阳，核心成员有多年的互联网产品开发经验和创投经验，连续创业者。
莫皓宇在 2018年在中国重庆创建PPStar，同时在贵阳建有研发中心，PPStar在国内拥有丰富的媒体资源和矿圈资源。
2018年10月PPStar正式上线，未来PPStar将会成为最新的挖矿方式

项目基本情况:
HCP是社区型分布式云计算平台PPStar算力星球基金会下算力积分，通过购买PPStar算力星球平台合约进行赠送，算力合约平台已于2018年10月上线运行，
PPStar算力星球旗下算力运营平台，致力于为区块链挖矿的从业者提供云
算力服务，现推出购买挖矿合约的方式进行挖矿投资，从而解决挖矿行业
个人投资门槛高（挖矿设备、机房、矿池、挖矿项目等事务的对接、采购、建设、安装、运
维、电力等）的问题。云算力合约即为将传统渠道的挖矿行为线上化，省去用户下单，部署
，维护这些繁琐的步骤，用户直接购买云算力合约即为购买了矿机。PPStar通过构建大规模
矿机集群、统筹管理电力供应和矿机运营维护，来提供简单、弹性、高效、低起点的挖矿服
务。用户只需要购买一份算力合约即可享受持续的营收，不用担心矿机损坏维修，电力不稳
定等问题，专注为全球客户提供各种优质的区块链产品服务，让挖矿更简单，并通过持有HCP积分获取奖励。


更多关于PPStar的信息
官网：https://www.ppstar.info
Telegram: https://t.me/joinchat/GB_Oxg2dhcdCUagBpE8anQ

媒体报道：
http://www.chidaolian.com/article-14548-1

https://www.shenliancaijing.com/portal/activity/activedetail.html?id=2030

https://www.shenliancaijing.com/portal/activity/activedetail.html?id=2030

https://kknews.cc/finance/yekk3kk.html

https://read01.com/NydO0x7.html#.W8hCBBMzZ-U
