### ISSUE TITLE
ChainBookBS提交成功但是搜索不到麻烦看下

### ISSUE THREAD

**Issue by HelloWorldsir** [consenlabs/token-profile#2664]
我的合约地址 是0x6b8f7eaf32b7476d099ee68e1a03863b52aa5f78
不是您发的0x954b890704693af242613edef1b603825afcd708
我用Trust钱包可以添加的
区块链查询地址 https://etherscan.io/address/0x6b8f7eaf32b7476d099ee68e1a03863b52aa5f78

**Comment by wenyanwang** [comment]
你好，提交成功，还需要系统收录后，请查询提交的PR链接下留言回复

**Comment by HelloWorldsir** [comment]
合约地址可以查询 搜索BS不行
