### ISSUE TITLE
关于重名代币问题

### ISSUE THREAD

**Issue by cl-lc** [consenlabs/token-profile#2680]
1. 你好，我看了https://help-center.token.im/hc/article/360007261813 这个连接，里面提到的关于修改重名的symbol问题的时候，只提到说“如果你希望去掉数字，我们首先声明***”，然后呢？我该怎么操作才能去掉imToken 1.0 里面，symbol后面的数字呢？ 发PR申请么？
2. 我们的代币目前刚提交Token信息的PR，贵方还没有收录我们的代币（交易数，持币地址数不满足条件），但是因为我们目前已经有部分同学持有了我们的代币，而且显示的是“{SYMBOL}1”，在贵方未收录的情况下，怎么操作才能去掉后面的数字1呢？

谢谢~

**Comment by wenyanwang** [comment]
你好，这个是针对合约升级的项目方，其他情况暂不修改，请使用2.0版本即可，不存储代币重名问题，谢谢。

**Comment by cl-lc** [comment]
1. 如果已经存在一个代币叫NNB，然后我们提交了一个PR，代币的SYMBOL也叫NNB，那么imToken 1.0里面，看到我们的代币名称，应该是叫NNB1对吧？  那针对这种情况，有办法修改imToken 1.0里面的代币名称么？（去掉后面的数字）
2. 上述的第二个问题呢？ 我们现在的代币名称叫NNB（还没有被贵方收录），有持有我们代币的用户使用im token的时候，代币名称显示的是NNB1。按照你的答复，相当于这种情况暂时不能修改，对吧？
