### ISSUE TITLE
请管理员帮忙添加JLL的货币价格

### ISSUE THREAD

**Issue by Albert-li007** [consenlabs/token-profile#2702]
管理员，

你好，我可以从IM里面添加JLL到币管理中，但是没有显示JLL的价格，可否添加JLL价格到钱包中，多谢！

JLL的合约地址: 0x5661c46e366570360064ae1a50a17a7a1a8f3236

**Comment by wenyanwang** [comment]
你好，imToken显示block.cc行情的价格，请检查是否在上面有。
