### ISSUE TITLE
你好，已经有别的项目叫SE，1.0的名字修改一次，就会造成用户代币消失，容易引起恐慌，暂不做1.0的修改，请理解，谢谢。

### ISSUE THREAD

**Issue by hanyannan** [consenlabs/token-profile#2720]
_Originally posted by @wenyanwang in https://github.com/consenlabs/token-profile/pull/2658#issuecomment-429518265_

你好，现在的问题是你们不修改成SE才会造成用户恐慌。请修改。很多人还在使用1.0

**Comment by wenyanwang** [comment]
请不要重复提交信息，谢谢。
