### ISSUE TITLE
你好，提交代币信息出错，原因是logo没有通过test，报错是旧文件引起的和我提交的无关，请看报错

### ISSUE THREAD

**Issue by iamtoken** [consenlabs/token-profile#2855]
报错如下，请尽快修复，麻烦通过下[#2853](https://github.com/consenlabs/token-profile/pull/2853)
Warning! dose not have 0x5f3fe72d30868c2BFaBeFf9c32cF2414abaA0581.png in images dir, please check first
Warning! dose not have 0x6c9a55be8f7aaf934a5779a63c8194d039e14a9f.png in images dir, please check first
Warning! dose not have 0x818a6f5515e18a94ada2d6e30bf7748d8e45cc48.png in images dir, please check first
Warning! 0x957C7090C1e2bBAAE73780d657df8132D6f3dA9D.png in images dir, that capital  @and small letter isn't quite the same with 0x957c7090c1e2bbaae73780d657df8132d6f3da9d
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.

**Comment by wenyanwang** [comment]
请参考成功的文件，谢谢
PR 示例：
 [https://github.com/consenlabs/token-profile/pull/1636](https://github.com/consenlabs/token-profile/pull/1636)
