### ISSUE TITLE
有个master上有人的json编码格式不对,导致其他人提交过不了check

### ISSUE THREAD

**Issue by wchrt** [consenlabs/token-profile#312]
错误内容: ERROR! json file name 0xabc1280a0187a2020cc675437aed400185f86db6.json must be utf-8 encoding

**Comment by JimmyStudio** [comment]
0xabc1280a0187a2020cc675437aed400185f86db6.json must be utf-8 encoding
这个人格式不对导致其他人都提交不了
{
  "symbol": "SAC",
  "address": "0xabc1280a0187a2020cc675437aed400185f86db6",
  "overview":{
        "en": "Smart Application Chain: Build a developer-friendly public chain accessed to the system in order to provide whole KYC tools, user system and application management suite��combining blockchain and artificial intelligence to create a self-evolving decentralized application ecosystem.",
        "zh": "SACּ�ڴ��쿪�����ѺõĹ�������ϵͳ��Ϊ�������ṩ������KYC���ߣ��û���ϵ���Լ�Ӧ�ù����׼���ͨ�����û����ݵĴ����Լ����ѧϰ��Ϊ�������ṩ��׼������ģ�飬�����������˹��������ϣ��������ҽ�����ȥ���Ļ�Ӧ����̬��"
  },
  "email": "sachainservice@gmail.com",
  "website": "http://sachain.net/",
  "whitepaper": "http://sachain.net/static/v_1.1_en.pdf",
  "state": "NORMAL",
  "published_on": "2018-05-07",
  "initial_price":{
        "ETH":"0.004 ETH",
        "USD":"2.4 USD",
        "BTC":"0.00035 BTC"
  },
  "links": {
    "twitter": "https://twitter.com/SACchain",
    "telegram": "https://t.me/SACgroup",
    "facebook": "https://www.facebook.com/SACchain"
    }
}

**Comment by makoshan** [comment]
你好，
感谢，已经修改。

Mako
