### ISSUE TITLE
项目方提交资料之前必看

### ISSUE THREAD

**Issue by wenyanwang** [consenlabs/token-profile#3191]
为了规避双方时间上的耗费，建议项目方提交信息时认真阅读提交资料的流程与要求。

常见资料问题：
提交信息过少：只有代币名称与合约地址，
logo问题：背景不透明，大小有问题
文件本身格式有问题：
文件命名合约大小不一致等问题
提交文件报错
合约升级：
未提供相关社区公告说明

诚恳的希望项目方提交是认真阅读一下提交文件相关说明。

公告 | imToken 代币收录、重名及修改名称等问题说明
https://help-center.token.im/hc/article/360007261813

为了加速显示进度，请尽可能向我们提供完善的项目资料，以及知名区块链媒体报道，包括但不限于以下内容，以便 imToken 团队更了解你们的项目。

团队背景：
项目基本情况:
媒体报道：
推荐用户转账所使用的 Gas 数量（没有提供，我们默认值 60000）
PR 示例：
#1636

**Comment by SM668** [comment]
团队背景:食源链FSCB(食品来源链)
是通过区块链技术搭建的溯源公链，利用区块链独特的不可篡改的分布式账本记录特性，构建溯源云平台，通过落地项目的子链及对应dapp应用来解决企业在商品生产、流转、分销、终端消费过程中的信息溯源、防伪验真、精准营销难题为技术开发者提供快捷高效的开发云服务集合，为品牌企业和消费者解决“可信任”难题.
项目基本情况:分配方案:食源链(FSCB)总量9900万枚
一：49%最大流通量
1：25%社区空投奖励，
2：24天使投资人
二：59%项目方持有令牌分配用途，(下面1：2：3：4：是剩下的59%令牌分配机制)
1：20%运营团队
2：15%市值管理
3：10%区块链应用技术开发
4：4%fscb俱乐部生态系统奖励
媒体报道：
推荐用户转账所使用的GAS数量(没有提供，我们默认值60000)
PR示例：
#1636
![565](https://user-images.githubusercontent.com/43012630/49957814-f26e3280-ff43-11e8-9698-97e4fc12ec26.png)
