### ISSUE TITLE
Bit-Fortune Blockchain 介绍及LOGO

### ISSUE THREAD

**Issue by 100Bitcoin** [consenlabs/token-profile#3198]
**团队背景：**
 
BFB（Bit-Fortune）团队来自于清华大学、北京邮电大学等名校，自2013年进入到比特币社区，一直致力于推动比特币及区块链技术和社区的发展。团队在数学建模、密码学技术、区块链开发以及社区运营方面有着丰富的经验，目前BFB已经获得Carving Captital、Bitnoah、比特财富网等多家机构的战略投资。
  
**项目基本情况：**
 
BFB（Bit-Fortune）是下一代区块链支付技术，是一种基于稳定币模型的点对点的支付网络。主要服务于微观支付场景，BFB重新定义了支付方式，是对日常支付（如法币）和跨境支付（如数字货币）的有效补充。BFB将成为区块链连接实体经济的入口，从而解决目前普通用户难以使用区块链产品的难题，提升区块链产品的可用性。

**官网：**
http://bfb.wiki

**etherscan浏览器：**
https://etherscan.io/address/0xdbcd6bd6ecaa36c8a6c554d70b7f39d6c0fd7ad2

**合约地址**
0xdbcd6bd6ecaa36c8a6c554d70b7f39d6c0fd7ad2

**媒体报道：**
https://www.toutiao.com/i6626985205884256775/
http://www.sohu.com/a/277353186_120002344

**建议gas limit：60000**

![bfb](https://user-images.githubusercontent.com/43564644/48936886-47231c80-ef47-11e8-8363-ed726d8ea655.png)

**Comment by DogethereumD** [comment]
不在这里提交
