### ISSUE TITLE
Interacting with a smart contract

### ISSUE THREAD

**Issue by igorya7v** [consenlabs/token-profile#3263]
Hi,
I was redirected from your support team to submit my request here.
My question was, how can I interact with a smart contract using the imToken app. This involves providing the address and ABI of the deployed smart contract and after that executing one of it's methods by signed transaction.

As a reference, it could be done by using MyEtherWallet:
https://www.myetherwallet.com/#contracts

Is it possible to have such a functionality with the imToken app?

**Comment by tstt** [comment]
Sorry, imToken not support this function as for now.
