### ISSUE TITLE
Some Bug on YQX Token

### ISSUE THREAD

**Issue by Romiel12191993** [consenlabs/token-profile#3310]

**Comment by Romiel12191993** [comment]
Hello Im Engr Romiel I want to report some bug on our YQX token, on etherscan it is correct but on our wallet on Imtoken it will add 8 zero and our Investors are confused about this problem please fix this.
Here is our Contract Address   0x62702dD813727dAC32965f1049781933b07bc0A7

**Comment by tstt** [comment]
it was fixed，please check it.
