### ISSUE TITLE
抱歉，你们的代币官网资料未通过，请确保资料真实性。

### ISSUE THREAD

**Issue by liushuai01a** [consenlabs/token-profile#3342]
_Originally posted by @tstt in https://github.com/consenlabs/token-profile/pull/3283#issuecomment-445735591_

**Comment by liushuai01a** [comment]
审核的回复我们，代币官网资料未通过，确保资料真实性。
这是我们的官网http://www.aphcoin.top/，请问我们哪块资料缺少真实性，我们好重新补充证明。

**Comment by tstt** [comment]
确认 Ariel Meilich 是你们的项目负责人吗？

![image](https://user-images.githubusercontent.com/16997688/49931761-8a4b2c80-ff02-11e8-8434-f6931fc85c6e.png)

可以参考下这个链接：https://medium.com/jur-io/an-interview-with-jur-advisor-ariel-mielich-of-decentraland-5a97bb8dc7c4

**Comment by liushuai01a** [comment]
> 
> 
> 确认 Ariel Meilich 是你们的项目负责人吗？
> 
> ![image](https://user-images.githubusercontent.com/16997688/49931761-8a4b2c80-ff02-11e8-8434-f6931fc85c6e.png)
> 
> 可以参考下这个链接：https://medium.com/jur-io/an-interview-with-jur-advisor-ariel-mielich-of-decentraland-5a97bb8dc7c4

你好,我们官网的团队资料已经修改，请审核http://www.aphcoin.top/

**Comment by tstt** [comment]
真实性是第一要求，抱歉你们的 pr 不会再被通过。

**Comment by SM668** [comment]
Teacher, help me with it, okay?

**Comment by SM668** [comment]
Teacher, help me with it, okay?
