### ISSUE TITLE
你好，为什么申请通过了的代币，没显示价格呢

### ISSUE THREAD

**Issue by cdcctoken** [consenlabs/token-profile#3489]
你好，为什么申请通过了的代币，没显示价格呢。我在 代币.json 文件中是有按照规定填写了 USD,ETH,BTC 价格的。代码的地址是：0xb5160a825295a31b168482808c2c752f7479c4a7

@tstt

**Comment by cdcctoken** [comment]
@tstt

**Comment by tstt** [comment]
Token Profile 页面已有「发行成本」显示。
如果你指的是实时价格，请提供 ADD 在 blockcc 的价格链接。

**Comment by phpcolt** [comment]
@tstt 这边代币多久整理收录一次

**Comment by tstt** [comment]
至少一周一次
