### ISSUE TITLE
SUT申请显示价格

### ISSUE THREAD

**Issue by sumtoken** [consenlabs/token-profile#3496]
你好！

我们是SUM TOKEN（SUT）的项目方，SUT目前已经上线多个交易所，申请在im token，显示SUT的价格。

FCOIN：https://exchange.fcoin.com/ex/spot/oncloundfund/sut/eth    （显示这个交易所的价格）
ZZEX：https://www.zzexvip.com/#/tradecenter

谢谢！

**Comment by tstt** [comment]
已添加，请确认。
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。
附 imToken 品牌资料：https://projects.invisionapp.com/boards/GE3L46DWK2C
