### ISSUE TITLE
您好，我添加了新的token,为什么一直没通过呢？

### ISSUE THREAD

**Issue by MrLiuYong** [consenlabs/token-profile#352]
我已经上传了好几次，都没通过，请问是什么情况？代币名称是ex，合约地址是：0xA5a15631Eb0aa1D178cf2D2C6BEc7732A80eAB03

**Comment by makoshan** [comment]
已经添加你的代币

**Comment by MrLiuYong** [comment]
你好，为什么我在imtoken的app上面还搜索不到呢？
