### ISSUE TITLE
我的合约地址无法进行checksum校验，检查了大小写都没问题

### ISSUE THREAD

**Issue by oechain** [consenlabs/token-profile#3579]

**Comment by tstt** [comment]
这个问题和地址 checksum 应该无关。建议重提一个 pr, 如果还有问题，我们会帮你检查

**Comment by oechain** [comment]
好的，谢谢您！发自我的iPhone------------------ 原始邮件 ------------------发件人: peijie  <notifications@github.com>发送时间: 2019年1月22日 14:21收件人: consenlabs/token-profile <token-profile@noreply.github.com>抄送: OEChain <wautoken@gmail.com>, Author <author@noreply.github.com>主题: 回复：[consenlabs/token-profile] 我的合约地址无法进行checksum校验，检查了大小写都没问题 (#3579)这个问题和地址 checksum 应该无关。建议重提一个 pr, 如果还有问题，我们会帮你检查

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/consenlabs/token-profile","title":"consenlabs/token-profile","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/consenlabs/token-profile"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tstt in #3579: 这个问题和地址 checksum 应该无关。建议重提一个 pr, 如果还有问题，我们会帮你检查"}],"action":{"name":"View Issue","url":"https://github.com/consenlabs/token-profile/issues/3579#issuecomment-456284331"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/consenlabs/token-profile/issues/3579#issuecomment-456284331",
"url": "https://github.com/consenlabs/token-profile/issues/3579#issuecomment-456284331",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
