### ISSUE TITLE
Price for token doesn’t show on your app 

### ISSUE THREAD

**Issue by Belance** [consenlabs/token-profile#3585]
Hello,

Wanted to ask about our token from pull request #3443 , price on your app does not show (( what to do for price to show thank you ?

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/issues/3595
you can refer to this template

**Comment by tstt** [comment]
How to display token price:
In imToken, the current displayed token prices are provided by the block.cc API. If you want your project’s token price to be displayed in imToken, your token price must be supported on block.cc and you have to provide us the corresponding link in your Github submission.
