### ISSUE TITLE
Add token price display for ERC20

### ISSUE THREAD

**Issue by Belance** [consenlabs/token-profile#3603]
block.cc Link: https://mifengcha.com/q/Erc20
Token Symbol: ERC20
Token Contract Address: 0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea
Etherscan Link: https://etherscan.io/token/0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea

Thank you!

**Comment by tstt** [comment]
added, if there is no problem, you can close the issue.
