### ISSUE TITLE
Add token price display for OEC

### ISSUE THREAD

**Issue by lingjiuzhe** [consenlabs/token-profile#3615]
block.cc Link: https://mifengcha.com/q/oec
Token Symbol: OEC
Token Contract Address: 0x31ed1bc96fa75ee33d513a0cef4b65c2500b320b
Etherscan Link: https://etherscan.io/token/0x31ed1bc96fa75ee33d513a0cef4b65c2500b320b

Thank you!

**Comment by tstt** [comment]
已添加，确认下，没有问题就可以把这个 issue 关了。
