### ISSUE TITLE
add OEC token

### ISSUE THREAD

**Issue by oechain** [consenlabs/token-profile#3622]
团队背景：OEC项目团队由新加坡OEC基金会发起组成，项目负责人唐伯虎，是原苹果大中华区首席团队经理，苹果iTunes Store 反欺诈团队负责人，企业服务领域专 家，新加坡比特股社区创始人，东南亚首家区块链服务公司BITSG Block Chain Service 创始人，连续创业者，比特币早期的狂热投资者。团队还与BVI公司ONE CHAIN CAPITAL建立战略合作关系，由ONE CHAIN CAPITAL向项目赞助者提供持币兑换黄花梨树的保值增值服务。
项目基本情况：OEC黄花梨生态链，为世界最为珍贵的海南黄花梨建立了区块链溯源系统。所有种植、流转信息全部上链存证，为海南黄花梨的防伪保真、交易流转和生态保护提供认证和确权。项目代币OEC，也称为花梨币，实现了一币双能，既是黄花梨生态链的溯源通证，也是兑换黄花梨树的交易凭证。在空气币归零潮中，建立了永不归零的保值增值机制。持币者即使无法在交易市场中获得代币价值收益，也可以通过持币兑换黄花梨树，获得价值保全，甚至是投资增值。
媒体报道：
https://www.jinse.com/blockchain/233736.html
区块链电商 OEC全商链如何再造通证经济
https://www.admin5.com/article/20180907/875216.shtml
os风在扼杀区块链！全国区块链专项赛大奖得主OEC强调加强应用实务
https://www.admin5.com/article/20180829/873601.shtml
20年溯源仍旧空中楼阁，OEC的区块链技术能让它真的落地吗？
收录的交易所：
1月29日上线HUBI，www.hubi.com
官网：https：//www.oechain.io/
代币合约地址：0x6ad95E5CD97b080E8d30ce6C25016777E0fEfD7a
建议 gas limit：60000

**Comment by tstt** [comment]
已在 pr 中回复

**Comment by oechain** [comment]
请问现在格式可以了吗

**Comment by oechain** [comment]
我已经重新提交了申请，请您看看是否可以了发自我的iPhone------------------ Original ------------------From: peijie  <notifications@github.com>Date: Fri,Jan 25,2019 2:56 PMTo: consenlabs/token-profile <token-profile@noreply.github.com>Cc: OEChain <wautoken@gmail.com>, Author <author@noreply.github.com>Subject: Re: [consenlabs/token-profile] add OEC token (#3622)已在 pr 中回复

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/consenlabs/token-profile","title":"consenlabs/token-profile","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/consenlabs/token-profile"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tstt in #3622: 已在 pr 中回复"}],"action":{"name":"View Issue","url":"https://github.com/consenlabs/token-profile/issues/3622#issuecomment-457474948"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/consenlabs/token-profile/issues/3622#issuecomment-457474948",
"url": "https://github.com/consenlabs/token-profile/issues/3622#issuecomment-457474948",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by oechain** [comment]
没有看到您在PR中最新的回复
