### ISSUE TITLE
无法收录代币，是不什么原因？

### ISSUE THREAD

**Issue by lusina50551** [consenlabs/token-profile#3678]
无法收录代币，是不什么原因？ 请求地址https://github.com/consenlabs/token-profile/pull/3669

**Comment by tstt** [comment]
你们的项目介绍（金钱币）和代币提交（HTHC, JQB）没有关联，且项目介绍虚浮。
和 imToken 价值观存在明显分歧，所以贵方代币 Token Profile 无法通过。
