### ISSUE TITLE
在imtoken中FCS合约logo之前正常，最近发现不能显示

### ISSUE THREAD

**Issue by fcscolorstone** [consenlabs/token-profile#3682]
合约地址： 0xd56c90a1b12C93bB48E9a0904a2a1E1D9DCB5161， 最新logo突然不能正常显示了，年前还是正常的。

**Comment by tstt** [comment]
刷新看看，刚试了正常的，如果没有问题，直接关掉这个 issue 就可以。

**Comment by fcscolorstone** [comment]
该合约在2018年更换过地址，现在显示的是旧地址对应的logo， 新地址对应logo无法显示。 春节前是没有这个现象的。

**Comment by fcscolorstone** [comment]
具体过程可以查看下PR，谢谢。

**Comment by tstt** [comment]
再确认下：
在春节前，新旧两个代币在 imToken 2.0 都可以搜索添加；且 logo 正确；symbol 正确：旧的为 FCS_OLD, 新的为 FCS。节后这段时间发现异常是吗？

**Comment by fcscolorstone** [comment]
是的，是这个情况。

**Comment by fcscolorstone** [comment]
是的， 2019.2.13日白天还是正确的（新旧两个代币在 imToken 2.0 都可以搜索添加；且 logo 正确；symbol 正确：旧的为 FCS_OLD, 新的为 FCS），从2019.2.14开始就不行了。

**Comment by tstt** [comment]
嗯，了解。我们正在检查。

**Comment by tstt** [comment]
@fcscolorstone 已恢复，请确认。

**Comment by fcscolorstone** [comment]
已经可以了，谢谢。
