### ISSUE TITLE
ERC-20: 请添加FCS价格显示

### ISSUE THREAD

**Issue by fcscolorstone** [consenlabs/token-profile#3683]
block.cc 链接：https://mifengcha.com/q/fcs
代币简称：FCS
合约地址：0xd56c90a1b12C93bB48E9a0904a2a1E1D9DCB5161
Etherscan 链接：https://etherscan.io/token/0xd56c90a1b12c93bb48e9a0904a2a1e1d9dcb5161

**Comment by tstt** [comment]
已经添加，确认下。

**Comment by fcscolorstone** [comment]
已OK，谢谢。
