### ISSUE TITLE
Add token price display for QCH

### ISSUE THREAD

**Issue by qch-qchi** [consenlabs/token-profile#3687]
Block.cc Link: https://mifengcha.com/coin/qch
Token Symbol: QCH
Token Contract Address: 0x687bfc3e73f6af55f0ccca8450114d107e781a0e
Etherscan Link: https://etherscan.io/token/0x687bfc3e73f6af55f0ccca8450114d107e781a0e

Kindly add token price for QCH.
Thank you!

**Comment by tstt** [comment]
We've added, please check it.

**Comment by 02081993** [comment]
i'm added 
please check it
thanks

**Comment by 02081993** [comment]
thanks for reply

**Comment by qch-qchi** [comment]
Yes, the price is showing now.
Thanks for the update!

**Comment by 02081993** [comment]
check

**Comment by 02081993** [comment]
I've added you to my whitelist on BitBounce!
[image: BitBounce]



Hello!

I’ve signed up for a cryptocurrency spam solution called BitBounce and I
added you to my “whitelist”. That means you can email me and your emails
will come through.

For people who aren’t on my whilelist, I’m charging $0.05 in Credo for
their email to get to my inbox. A cleaner inbox and more money? Win! You
should check it out!

*Sign up for BitBounce and earn 1 complimentary Credo.*
<https://bitbounce.com?ref=bitbounce>

Unsubscribe
<https://bitbounce.com/unsubscribe_from_whitelist_email_notifications/755171396>
from Surya Ari Pandi's whitelist notification emails.



*BitBounce* <https://bitbounce.com?ref=bitbounce> is powered by the *Credo*
<https://bitbounce.com/credo> cryptocurrency

*I’m from a business* —  what are my *delivery options*
<https://business.bitbounce.com>

BitBounce and Credo are transacted through *CredoEx*
<https://credoex.com?ref=bitbounce>
Made by Turing Technology Inc. in San Mateo, California *Sign Up for
BitBounce* <https://bitbounce.com?ref=bitbounce>
