### ISSUE TITLE
imtoken2.0无法通过名称搜索到LGCC

### ISSUE THREAD

**Issue by lgcctokenk** [consenlabs/token-profile#3707]
imtoken2.0无法通过名称搜索到LGCC,也不显示ogo，imtoken1.0可以搜索也可以看到logo，麻烦看下，我们才好推荐用户使用imtoken2.0.

**Comment by tstt** [comment]
已经同步，请确认。

**Comment by lgcctokenk** [comment]
好的，谢谢，辛苦了
