### ISSUE TITLE
Update Token Logo

### ISSUE THREAD

**Issue by BCTVFoundation1** [consenlabs/token-profile#3709]
I'm unable to apply via Github, I'm BCTV Foundation, PFU 0x888108116dad3f62faa2a70b7a75f3ba44a0e8ac
it is now listing in www.bqex.hk and www.exshell.com

Best Regards
www.bctv.world

**Comment by tstt** [comment]
It's suggested that to ask your coder to apply a pr.
Refer to the following link: 
https://github.com/consenlabs/token-profile/blob/master/README.md
