### ISSUE TITLE
合约升级PR合并后，名称已修改但图标未更换

### ISSUE THREAD

**Issue by bcachain** [consenlabs/token-profile#3710]
合约升级PR
https://github.com/consenlabs/token-profile/pull/3698

现在imtoken2.0内，DAEC_OLD显示图标，而DAEC未显示图标

**Comment by tstt** [comment]
问题已解决，请确认。

**Comment by bcachain** [comment]
谢谢，现在两个图标都显示。

可能是缓存把。不过关系不大。
