### ISSUE TITLE
合约更换后在imtoken1.0 上变成了ARM16 imtoken2.0正常

### ISSUE THREAD

**Issue by hoseadevops** [consenlabs/token-profile#3711]
https://github.com/consenlabs/token-profile/commit/7e1c4879f64968586a1563f29a570e277eab7507

旧的合约已经更名为ARM_OLD了

**Comment by tstt** [comment]
如果你下载了以太坊全量数据，可以看到目前至少有其他 15 个和名为 arm 的代币，有些虽然在 imToken 搜索不到，但是那些代币的持有者，他们的钱包中显示的代币名就是：arm1，或 arm2/3/4...。因此我们不能简单的在 1.0 中修改你们的代币简称。
