### ISSUE TITLE
ERC-20 ： 添加 LEMO 价格显示

### ISSUE THREAD

**Issue by lnkyan** [consenlabs/token-profile#3727]
block.cc 链接：https://mifengcha.com/q/lemo
代币简称：LEMO
合约地址：0x60C24407d01782C2175D32fe7C8921ed732371D1
Etherscan 链接：https://etherscan.io/token/0x60c24407d01782c2175d32fe7c8921ed732371d1

**Comment by tstt** [comment]
已添加，请确认。

**Comment by lnkyan** [comment]
看到了，谢谢
