### ISSUE TITLE
Bitcoin Card (VD) Update

### ISSUE THREAD

**Issue by bitcoincardvd** [consenlabs/token-profile#3741]
Token : Bitcoin Card
Symbol : VD
Contract :0x9a9bB9b4b11BF8eccff84B58a6CCCCD4058A7f0D 
Logo Link : https://bitcoincard.me/vd.png
Logo Update

**Comment by tstt** [comment]
hi, you are suggested to follow this tutorial: https://github.com/consenlabs/token-profile#token-profile-guideline 
to provide your token profile.
