### ISSUE TITLE
Bankcoin Cash (BKC) Add Wallet

### ISSUE THREAD

**Issue by bankcoincash** [consenlabs/token-profile#3742]
Token : Bankcoin Cash
Symbol : BKC
Contract :0xc88Be04c809856B75E3DfE19eB4dCf0a3B15317a 
Logo Link : https://bankcoin-cash.com/bankcoincash.png
Logo Update

**Comment by tstt** [comment]
hi, you are suggested to follow this tutorial: https://github.com/consenlabs/token-profile#token-profile-guideline 
to provide your token profile.
