### ISSUE TITLE
MBCASH Token adding Your wallet

### ISSUE THREAD

**Issue by mbcashme** [consenlabs/token-profile#3743]
Token : MBCash
Symbol : MBCAH
Contract :0xEfbB3F1058fd8E0C9d7204f532E17d7572AFfc3e 
Logo : https://mbcash.me/mbcash.png
Logo Update

**Comment by tstt** [comment]
hi, you are suggested to follow this tutorial: https://github.com/consenlabs/token-profile#token-profile-guideline 
to provide your token profile.
