### ISSUE TITLE
Bankcoin (BCASH ) Listing With Logo

### ISSUE THREAD

**Issue by bcashbankcoin** [consenlabs/token-profile#3744]
Token : Bankcoin
Symbol : BCASH
Contract : 0xb5BB48567BfD0bFE9e4B08EF8b7f91556CC2a112
Logo Link : https://bankcoinbcash.com/bcash.png
Logo Update

**Comment by bcashbankcoin** [comment]
![bcash](https://user-images.githubusercontent.com/46301303/53829433-55eb8780-3faa-11e9-9e1a-bd1e6cc2a70f.png)

**Comment by tstt** [comment]
hi, you are suggested to follow this tutorial: https://github.com/consenlabs/token-profile#token-profile-guideline 
to provide your token profile.
