### ISSUE TITLE
提交资料后，imtoken的首页不显示代币的logo

### ISSUE THREAD

**Issue by iwaygan** [consenlabs/token-profile#3774]
提交资料后，imtoken的首页不显示代币的logo

**Comment by tstt** [comment]
可否贴一下 pr 链接，我们会尽快检查

**Comment by iwaygan** [comment]
什么是pr链接？不知道怎么上传截图。。。

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/pull/3775
类似这种，可以咨询下你们的技术同事
