### ISSUE TITLE
0x727443713e3fF01411Feaae52dae5d142A3c7b29.png

### ISSUE THREAD

**Issue by clubglobalfoundation** [consenlabs/token-profile#3785]
upload logo 
![LOGO GF](https://user-images.githubusercontent.com/47704586/54367948-38a37100-46ae-11e9-93e6-462852a91a60.png)

GLOBALFOUNDATION ( GF )

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md 
参考教程
