### ISSUE TITLE
TRAVIS CI CHECKS CRASHED AFTER LAST ./test/index.ts update

### ISSUE THREAD

**Issue by lavimalik** [consenlabs/token-profile#3816]
Why is Travis Ci checks taking into account already merged files and running tests on them too? Is it normal? Because before 24 hours when the checks were not updated the travis-ci checks were successful and now that the ./test/index.ts updated and already successful checked PRs has been merged - it is not letting any new PRs be successfully tested.

Please fix this issue ASAP.

**Comment by Andysaputr4** [comment]
Ok
