### ISSUE TITLE
ERC-20 ： 添加 TBTZ 价格显示

### ISSUE THREAD

**Issue by a13720943940** [consenlabs/token-profile#3876]
block.cc 链接：https://mifengcha.com/coin/tbtz
代币简称：tbtz
合约地址：0x27525a26a2fc5bec00e1bf82a73abebcd91c4a42
Etherscan 链接：https://etherscan.io/token/0x27525a26a2fc5bec00e1bf82a73abebcd91c4a42

**Comment by tstt** [comment]
已添加，请确认。

**Comment by a13720943940** [comment]
tbtz今天突然不显示价格了，是什么原因呢！

**Comment by tstt** [comment]
再刷新看看，我们这边显示正常。
