### ISSUE TITLE
ERC-20 ： 添加 SPC 价格显示

### ISSUE THREAD

**Issue by buster719** [consenlabs/token-profile#3915]
block.cc 链接：https://mifengcha.com/coin/spacechain
代币简称：SPC
合约地址：0x8069080a922834460C3A092FB2c1510224dc066b
Etherscan 链接：https://etherscan.io/token/0x8069080a922834460c3a092fb2c1510224dc066b

**Comment by tstt** [comment]
已添加，请确认。
