### ISSUE TITLE
Add CCD token

### ISSUE THREAD

**Issue by 55UROC** [consenlabs/token-profile#3916]
Please Add Cancri Diamond Coin - Currently held on 69 IMTOKEN wallets.

Contract Address
0x1fbc97d3455c6db83448a33d47822dc15a963d6f

**Comment by 55UROC** [comment]
CCD IMAGE

![CCD-img-728-555x555](https://user-images.githubusercontent.com/34796950/55595509-09a27d00-56f9-11e9-84c7-be2a3b577a40.png)

**Comment by tstt** [comment]
hi, please refer to the tutorial:
 https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md
