### ISSUE TITLE
ERC-20 ： 添加 WRB价格显示

### ISSUE THREAD

**Issue by wrglobal** [consenlabs/token-profile#3988]
block.cc 链接：https://mifengcha.com/coin/wrb
代币简称：WRB
合约地址：0x765a01875136455f4986269404d73eb4142d6873
Etherscan 链接：https://etherscan.io/token/0x765a01875136455f4986269404d73eb4142d6873

**Comment by tstt** [comment]
已添加，请确认

**Comment by wrglobal** [comment]
imtoken  1.0不能显示吗？

**Comment by tstt** [comment]
是的，imToken 1.0 的价格机制不同，不支持显示。推荐用户使用 imToken 2.0 即可。
