### ISSUE TITLE
ADD ERC20 TOKEN FUT

### ISSUE THREAD

**Issue by githubxiaocai** [consenlabs/token-profile#4010]
Link: www.llsmt.com
Token Symbol: FUT
Token Contract Address: 0xdF390596B8Dc360cb55C5062B45eBAe3a411D2a3 
Etherscan Link: https://etherscan.io/token/0xdF390596B8Dc360cb55C5062B45eBAe3a411D2a3

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md
