### ISSUE TITLE
ERC-20 ： 添加 INE价格显示

### ISSUE THREAD

**Issue by intellishare** [consenlabs/token-profile#4018]
block.cc 链接：https://mifengcha.com/q/INE
代币简称：INE
合约地址：0x86e6A4F512b1290c043970B04E0b570D4FC98291
Etherscan 链接：https://etherscan.io/token/0x86e6a4f512b1290c043970b04e0b570d4fc98291

**Comment by tstt** [comment]
已添加，请确认。
