### ISSUE TITLE
ERC-20 ： 添加 FZ价格显示

### ISSUE THREAD

**Issue by fzcoinProtocol** [consenlabs/token-profile#4028]
ERC-20 ： 添加 FZ 价格显示
block.cc 链接：https://mifengcha.com/coin/fz
代币简称：Fzcoin
合约地址：0xe5aee163513119f4f750376c718766b40fa37a5f
Etherscan 链接：https://etherscan.io/token/0xe5aee163513119f4f750376c718766b40fa37a5f

**Comment by tstt** [comment]
已添加，请确认
