### ISSUE TITLE
ERC-20: Add token price display for VJC

### ISSUE THREAD

**Issue by venjocoin** [consenlabs/token-profile#4059]
block.cc Link: **https://mifengcha.com/q/VJC**
Token Symbol: **VJC**
Token Contract Address: **0x5c62da804298d5972a323c80b539b8e7517a0dde**
Etherscan Link: **https://etherscan.io/token/0x5c62da804298d5972a323c80b539b8e7517a0dde**

**Comment by tstt** [comment]
已添加，请确认。

**Comment by venjocoin** [comment]
价格和照片都没显示出来

**Comment by tstt** [comment]
logo 已同步，请再确认

**Comment by venjocoin** [comment]
确认

**Comment by Andysaputr4** [comment]
Yes

Pada tanggal Kam, 2 Mei 2019 09.03, venjocoin <notifications@github.com>
menulis:
