### ISSUE TITLE
ERC-20 ： 添加 CAD 价格显示

### ISSUE THREAD

**Issue by wrglobal** [consenlabs/token-profile#4062]
block.cc 链接：https://mifengcha.com/coin/cad
代币简称：CAD
合约地址：0x7963c8c3429b9e3ab655f13b7272106ab815787f
Etherscan 链接：https://etherscan.io/token/0x7963c8c3429b9e3ab655f13b7272106ab815787f

**Comment by tstt** [comment]
已添加，请确认
