### ISSUE TITLE
some pics have executive permission

### ISSUE THREAD

**Issue by starit** [consenlabs/token-profile#4078]
When I clone the repo on cloud server, some pics have default executive permission. For example:
* TITT@riskyrisky14.png
* 0x8722063aafa466c3176567c7a912898e92446ec4.png
* 0x7c5bec2c6c006d488549edfa141bcd5c38098964.png

I'm not sure if this is a security problem and please check. Thanks!

**Comment by tstt** [comment]
Hi, thanks for your reminder. It should be that the projects'official set the wrong file permissions when submitting, and there is no malicious code. But we'll let the projects'official to modify it.
