### ISSUE TITLE
ERC-20 ： 添加 HAI 价格显示

### ISSUE THREAD

**Issue by HAIchain** [consenlabs/token-profile#4102]
block.cc 链接：https://mifengcha.com/coin/hangkei-ai-chain
代币简称：HAI
合约地址：0x136723300aef2aAB4b7cF52c3Eaac6F997e12a68
Etherscan 链接：https://etherscan.io/token/0x136723300aef2aAB4b7cF52c3Eaac6F997e12a68

**Comment by tstt** [comment]
已添加，请确认
