### ISSUE TITLE
ERC-20 ： 添加WB价格显示

### ISSUE THREAD

**Issue by WiseBlock** [consenlabs/token-profile#4117]
ERC-20 ： 添加WB价格显示
block.cc 链接：https://mifengcha.com/coin/wb
代币简称：WB
合约地址：0xda2e0aa8f697db190c32034894cf9731f6619960
Etherscan 链接：https://etherscan.io/token/0xda2e0aa8f697db190c32034894cf9731f6619960

**Comment by tstt** [comment]
已添加，请确认。
