### ISSUE TITLE
ERC-20 ： 添加WRB价格显示(更换合约地址)

### ISSUE THREAD

**Issue by wrglobal** [consenlabs/token-profile#4125]
ERC-20 ： 添加WRB价格显示(更换合约地址)
block.cc 链接：https://mifengcha.com/coin/wrb
代币简称：WRB
合约地址：0xdd72a22b2229fcf2a93fe0ec1328244d76d6afc9
Etherscan 链接：https://etherscan.io/token/0xdd72a22b2229fcf2a93fe0ec1328244d76d6afc9

**Comment by tstt** [comment]
已添加，请确认
