### ISSUE TITLE
ERC-20 ： 添加 OSC价格显示

### ISSUE THREAD

**Issue by Knightshi** [consenlabs/token-profile#4128]
ERC-20 ： 添加 OSC 价格显示
block.cc 链接：https://mifengcha.com/coin/ioscar
代币简称：OSC
合约地址：0x60a640e2D10E020fee94217707bfa9543c8b59E0
Etherscan 链接：https://etherscan.io/token/0x60a640e2D10E020fee94217707bfa9543c8b59E0#balances

**Comment by tstt** [comment]
已添加，请确认。
