### ISSUE TITLE
项目test失败

### ISSUE THREAD

**Issue by hldzlk** [consenlabs/token-profile#4158]
7282473ffb016feaac65faf9ffccfee7d20f8578 这个commit导致项目 `npm test`报错
导致所有新提交的PR都无法通过测试

**Comment by MarsBlockchainMedia** [comment]
现在任然存在这个问题，项目中很多人提交都检测不通过

**Comment by tstt** [comment]
抱歉，自动检查报错是由于我们这边的失误，目前已经修复问题。请重新提交 pr, 我们会尽快处理。
hi, we've fixed the CI autocheck issue. And you need to re-pr so that will be ok.
