### ISSUE TITLE
ERC-20：添加ZB价格显示

### ISSUE THREAD

**Issue by a13720943940** [consenlabs/token-profile#4176]
block.cc链接：https://mifengcha.com/coin/zb-blockchain 
代币简称：ZB 
合约地址：0xbd0793332e9fb844a52a205a233ef27a5b34b927 
Etherscan链接：https://etherscan.io/token/0xbd0793332e9fb844a52a205a233ef27a5b34b927

**Comment by tstt** [comment]
已添加，请确认。

**Comment by a13720943940** [comment]
好的，谢谢


 
---原始邮件---
发件人: "peijie"<notifications@github.com>
发送时间: 2019年5月24日(星期五) 下午4:16
收件人: "consenlabs/token-profile"<token-profile@noreply.github.com>;
抄送: "a13720943940"<249981793@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [consenlabs/token-profile] ERC-20：添加ZB价格显示 (#4176)



已添加，请确认。
