### ISSUE TITLE
Profile token

### ISSUE THREAD

**Issue by jackloho** [consenlabs/token-profile#4220]
How to make token profile for my CNNS coin? And display to you?
![Screenshot_2019-05-30-12-55-32-20](https://user-images.githubusercontent.com/51187871/58612970-8c514e00-82de-11e9-85c2-0ce90ecb99dd.png)

**Comment by tstt** [comment]
refer to this tutorial:
https://github.com/consenlabs/token-profile#token-profile-guideline
