### ISSUE TITLE
你好，为什么代币名称后面多了一个“4”

### ISSUE THREAD

**Issue by sunnycn2013** [consenlabs/token-profile#4233]
你好，为什么代币名字后面多了一个“4”，我们提交的代币名称是“CER”，添加成功后如图：
![WechatIMG61](https://user-images.githubusercontent.com/3810388/58789999-099ffa00-8622-11e9-9fd8-3b863930f8c8.jpeg)

**Comment by tstt** [comment]
imToken 1.0 通过在代币名称后添加数字区分重名代币。使用 imToken 2.0，imToken 2.0 通过代币合约地址来区分代币，所以不会有代币名称后添加数字的情况。

**Comment by sunnycn2013** [comment]
好的
