### ISSUE TITLE
token contract已经可以被imtoken钱包搜索到， 但是logo显示不正确

### ISSUE THREAD

**Issue by ArtChainGlobal** [consenlabs/token-profile#424]
如题， 

contract 地址： 0x984c134a8809571993fd1573fb99f06dc61e216f

0x984c134a8809571993fd1573fb99f06dc61e216f.png 正确保存于 images 文件夹内

麻烦修复，  感谢

**Comment by mcc-github** [comment]
区分大小写么?

**Comment by yanzhenluan** [comment]
这个图片文件怎么保存啊

**Comment by wenyanwang** [comment]
你好，请提供PR链接，谢谢。

**Comment by ArtChainGlobal** [comment]
您好， 请问 pr 链接是？

**Comment by ArtChainGlobal** [comment]
commit cc84a7f7da9c289e2a04914cdb9a85b7402c6829  是这个吗？

**Comment by ArtChainGlobal** [comment]
@makoshan 不好意思， 我这边还是 显示不出来 token 的 logo??

为什么就 close 了？
