### ISSUE TITLE
ERC-20 ： 添加 INC 价格显示

### ISSUE THREAD

**Issue by loser1046** [consenlabs/token-profile#4305]
ERC-20 ： 添加 INC 价格显示
block.cc 链接：https://mifengcha.com/coin/influence-chain
代币简称：INC
合约地址：0x4BFFC9B4d4DcF730820a2EdCAD48Ff5D7E0Ae807
Etherscan 链接：https://etherscan.io/address/0x4bffc9b4d4dcf730820a2edcad48ff5d7e0ae807

**Comment by tstt** [comment]
已添加，请确认。

**Comment by loser1046** [comment]
显示了，谢谢
