### ISSUE TITLE
ERC-20 添加BPRO价格显示

### ISSUE THREAD

**Issue by dappsclub** [consenlabs/token-profile#4324]
block.cc 链接：https://mifengcha.com/q/BPRO
代币简称：BPRO
合约地址：0x197e6bca6bc2f488ec760a6ce46b1399cd2954b0
Etherscan 链接：https://etherscan.io/token/0x197e6bca6bc2f488ec760a6ce46b1399cd2954b0

**Comment by tstt** [comment]
已添加，请确认
