### ISSUE TITLE
ERC-20 添加 LSC 价格显示

### ISSUE THREAD

**Issue by crasker** [consenlabs/token-profile#4367]
block.cc 链接：https://mifengcha.com/coin/littlesesame
代币简称：LSC
合约地址：0xc77d7e0dd7b2a01b990e866feb21d031f1418c2e
Etherscan 链接：https://etherscan.io/token/0xc77d7e0dd7b2a01b990e866feb21d031f1418c2e

**Comment by tstt** [comment]
已添加，请确认
