### ISSUE TITLE
ERC-20 ： 添加 JAR 价格显示

### ISSUE THREAD

**Issue by cheneyszp** [consenlabs/token-profile#4370]
ERC-20 ： 添加 JAR 价格显示
block.cc 链接：https://mifengcha.com/coin/jarvis
代币简称：JAR
合约地址：0xa249DE6948022783765Fee4850d7b85E43118FCc
Etherscan 链接：https://etherscan.io/token/0xa249de6948022783765fee4850d7b85e43118fcc

**Comment by tstt** [comment]
已添加，请确认

**Comment by cheneyszp** [comment]
@tstt block.cc地址发生了变化：https://block.cc/coin/jarvis+

**Comment by tstt** [comment]
> @tstt block.cc地址发生了变化：https://block.cc/coin/jarvis+

收到，了解。

**Comment by cheneyszp** [comment]
> > @tstt block.cc地址发生了变化：https://block.cc/coin/jarvis+
> 
> 收到，了解。

imtoken上还是没有显示价格呢，请帮忙。感谢。 @tstt

**Comment by tstt** [comment]
imToken 2.0 中添加后，在「钱包」首页会显示价格，但是转账页面的价格显示暂时不支持显示，同时imToken 1.0 中不再添加新的代币价格。

**Comment by cheneyszp** [comment]
> imToken 2.0 中添加后，在「钱包」首页会显示价格，但是转账页面的价格显示暂时不支持显示，同时imToken 1.0 中不再添加新的代币价格。

现在首页显示价格为0，有问题，需要修改为真实的价格。 @tstt

**Comment by tstt** [comment]
imToken 配置的价格取自 blockcc，是动态的，建议咨询下 blockcc 关于更新贵方代币价格的问题。

**Comment by cheneyszp** [comment]
> imToken 配置的价格取自 blockcc，是动态的，建议咨询下 blockcc 关于更新贵方代币价格的问题。

不是，blockcc的链接后来变了，你们update了吗？正确的应该是：https://block.cc/coin/jarvis+

**Comment by tstt** [comment]
> > imToken 配置的价格取自 blockcc，是动态的，建议咨询下 blockcc 关于更新贵方代币价格的问题。
> 
> 不是，blockcc的链接后来变了，你们update了吗？正确的应该是：https://block.cc/coin/jarvis+

我们并非直接使用此链接，仅从此链接获取一些必要信息，链接变化不影响在 imToken 中的代币价格显示
