### ISSUE TITLE
ERC-20 ： 添加 NKC 价格显示

### ISSUE THREAD

**Issue by iamzhao** [consenlabs/token-profile#4371]
block.cc 链接：https://mifengcha.com/coin/nework
代币简称：NKC
合约地址：0x5a1a29dbb6ad6153db764568c1289076bc876df6
Etherscan 链接：https://etherscan.io/token/0x5a1a29dbb6ad6153db764568c1289076bc876df6

**Comment by tstt** [comment]
已添加，请确认
