### ISSUE TITLE
ERC-20 ： 添加 BNL 价格显示

### ISSUE THREAD

**Issue by SoloKaze** [consenlabs/token-profile#4382]
block.cc 链接：https://mifengcha.com/q/BNL
代币简称：BNL
合约地址：0x7109ECA95Daa8F04ddEEF3a941fC9bd85BD1510F
Etherscan 链接：https://etherscan.io/token/0x7109ECA95Daa8F04ddEEF3a941fC9bd85BD1510F

**Comment by tstt** [comment]
https://mifengcha.com/coin/bnl
网站中未见到 BNL 上线的交易所，无法添加。请检查。
