### ISSUE TITLE
关于提交ERC20 Token Profile 中logo 图片名称问题

### ISSUE THREAD

**Issue by hgbc-io** [consenlabs/token-profile#4448]
我的合约地址是：0x286f0322164f532f388dac8bce2a5101d92a3475
经过Checksum 转化工具转换后是：0x286f0322164F532f388dac8bce2a5101D92A3475
我的logo命名为0x286f0322164F532f388dac8bce2a5101D92A3475.png时Travis-CI 会构建失败，错误是：

> Warning! 0x286f0322164F532f388dac8bce2a5101D92A3475.png in images dir, that capital and small letter isn't quite the same with 0x286f0322164f532f388dac8bce2a5101d92a3475

构建的错误地址：https://travis-ci.org/consenlabs/token-profile/builds/555236004?utm_source=github_status&utm_medium=notification

后来我将logo图片名称改为0x286f0322164f532f388dac8bce2a5101d92a3475.png就可以了。

教程里边是不是有错误？

**Comment by tstt** [comment]
教程无误。要求 json 文件名及其中合约地址和 png 文件名中的合约地址一致且有 checksum。
