### ISSUE TITLE
ERC-20 ： 添加 SEAL 价格显示

### ISSUE THREAD

**Issue by sealproject** [consenlabs/token-profile#4450]
block.cc 链接：https://mifengcha.com/coin/sealchain
代币简称：SEAL
合约地址：0x07bf5f95851ef2b2996f192569e406a6fea2a95a
Etherscan 链接：https://etherscan.io/token/0x07bf5f95851ef2b2996f192569e406a6fea2a95a

**Comment by tstt** [comment]
已添加，请确认

**Comment by sealproject** [comment]
> 已添加，请确认

@tstt 

资产列表里已经看到了，非常感谢！

但点击SEAL进入资产页的顶部，还没有显示。帮忙确认一下谢谢！

**Comment by tstt** [comment]
> > 已添加，请确认
> 
> @tstt
> 
> 资产列表里已经看到了，非常感谢！
> 
> 但点击SEAL进入资产页的顶部，还没有显示。帮忙确认一下谢谢！

这部分暂时还不支持，请见谅。
