### ISSUE TITLE
ERC-20:添加代币：EC  增加：logo  取消数字  仅显示EC

### ISSUE THREAD

**Issue by Echoinsys** [consenlabs/token-profile#4465]
Echoin链接
Echoin合约地址https://etherscan.io/address/0x12fd19dac0fab61bed5e0f09091b470c452d4d61#contracts
LOGO：
![LOGO](https://user-images.githubusercontent.com/52410392/60860603-e46a6100-a249-11e9-900b-43983b164c9c.png)

**Comment by tstt** [comment]
按教程提交 pr 后，经判断无误即可合并更新 logo。

教程链接：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Comment by beyond1122** [comment]
erc20如何添加logo
