### ISSUE TITLE
ERC-20 ： 添加CFC价格显示

### ISSUE THREAD

**Issue by chainfinance** [consenlabs/token-profile#4474]
block.cc链接：https://mifengcha.com/q/CFC
代币简称：CFC 
合约地址：0x7f288ff5a8055f5f6103a80dd806cf8415e035c7
Etherscan链接：https://etherscan.io/token/0x7f288ff5a8055f5f6103a80dd806cf8415e035c7

**Comment by chainfinance** [comment]
请尽快处理一下，谢谢。

**Comment by tstt** [comment]
已添加，请确认。

**Comment by chainfinance** [comment]
老大您好！再请教下，现在imtoken 2.0版本的以太坊钱包资产中心价格显示了，但CFC资产详情页面价格不显示。另外imtoken1.0版本，也不显示CFC价格，请问是否能给进一步处理一下呢？
https://github.com/consenlabs/token-profile/issues/4474
谢谢，添麻烦了

**Comment by tstt** [comment]
是这样的，目前只支持 2.0 资产首页的价格显示，2.0 资产详情页和 1.0 暂不支持进一步处理。
