### ISSUE TITLE
ERC-20：请添加NPXS

### ISSUE THREAD

**Issue by hongbinzuo** [consenlabs/token-profile#4494]
ERC-20 ： 添加 NPXS 价格显示
Pundi X 链接：https://pundix.com/
block.cc: http://block.cc/coin/pundi-x
代币简称：NPXS
合约地址：0xa15c7ebe1f07caf6bff097d8a589fb8ac49ae5b3
Etherscan 链接：https://etherscan.io/token/0xa15c7ebe1f07caf6bff097d8a589fb8ac49ae5b3

**Comment by tstt** [comment]
已有价格显示。

**Comment by RADICAL63825** [comment]
0xa15c7ebe1f07caf6bff097d8a589fb8ac49ae5b3
