### ISSUE TITLE
ERC-20: 请添加CardStack

### ISSUE THREAD

**Issue by hongbinzuo** [consenlabs/token-profile#4495]
ERC-20 ： 添加 CARD 价格显示
CardStack 链接：https://cardstack.com/overview 
block.cc: http://block.cc/coin/cardstack
代币简称：CARD
合约地址：0x954b890704693af242613edef1b603825afcd708
Etherscan 链接：https://etherscan.io/token/0x954b890704693af242613edef1b603825afcd708

**Comment by tstt** [comment]
已添加，请确认。
