### ISSUE TITLE
Add token price display for OGO

### ISSUE THREAD

**Issue by frank-origo** [consenlabs/token-profile#4509]
block.cc Link: https://mifengcha.com/coin/origo
Token Symbol: OGO
Token Contract Address: 0xFF0E5e014cf97e0615cb50F6f39Da6388E2FaE6E
Etherscan Link: https://etherscan.io/token/0xff0e5e014cf97e0615cb50f6f39da6388e2fae6e

**Comment by tstt** [comment]
已添加，请确认。
