### ISSUE TITLE
Whether ethereum QRCode supports extended data fields

### ISSUE THREAD

**Issue by jimmy-1988** [consenlabs/token-profile#4514]
sometime, developers need to use QRCodes to help users fill out extended data.
construct a transaction with hex to make the protocol work.

example:
```
ethereum:0x671D453365A83bC014a9eEF72988fe490B24A76e?decimal=18&value=0&extendeddata=0xa9059cbb00000000000000000000000085f22109eb32fef905e9bc8a22cf2a4e02b89b4800000000000000000000000000000000000000000000003b95c53d74269b0000
```
I'm not trying to do the job of sending tokens, this is just one example.

maybe `extendeddata` is not A good name

**Comment by zhen6939** [comment]
Hey,
I really like your idea and will talk to our PM to consider it as a new feature or not.
Thanks for your suggestion!

BTW: this issue will be closed.
