### ISSUE TITLE
ERC-20: Add token price display for BCAC

### ISSUE THREAD

**Issue by bcachain** [consenlabs/token-profile#4530]
block.cc Link: https://mifengcha.com/q/BCAC
Token Symbol: BCAC
Token Contract Address: 0x1aBdb309aa592f00a101c545168BFDF9a6Ec61CE
Etherscan Link: https://etherscan.io/token/0x1aBdb309aa592f00a101c545168BFDF9a6Ec61CE

**Comment by tstt** [comment]
> block.cc Link: https://mifengcha.com/q/BCAC

请确保此链接可正常打开。
