### ISSUE TITLE
ERC-20 ： 添加 EKT 价格显示

### ISSUE THREAD

**Issue by jason-zuo** [consenlabs/token-profile#4536]
ERC-20 ： 添加 EKT 价格显示
block.cc 链接：https://block.cc/coin/educare
代币简称：EKT
合约地址：0x4EcDB6385f3Db3847F9C4A9bf3F9917bb27A5452
Etherscan 链接:https://etherscan.io/address/0x4EcDB6385f3Db3847F9C4A9bf3F9917bb27A5452

**Comment by tstt** [comment]
已添加，请确认。
