### ISSUE TITLE
Template for my MATIC coin 

### ISSUE THREAD

**Issue by kelelbrainz** [consenlabs/token-profile#4539]
I need a template for my MATIC coin..I don't have a profile for it either .Help plsss

**Comment by tstt** [comment]
Token Profile is required to be provided by the project's official, you can contact the project's official and ask them to do this.

**Comment by kelelbrainz** [comment]
And how do I contact my project officials?

**Comment by tstt** [comment]
> And how do I contact my project officials?

Generally, you can find the contact information in their official website.

**Comment by kelelbrainz** [comment]
Please can you send me a link to their website ?

**Comment by tstt** [comment]
Sorry, we cannot provide this kind of information.

**Comment by kelelbrainz** [comment]
So how am I going to get in touch with my them ?

**Comment by tstt** [comment]
You are suggested to do it by your own. imToken have no relation with the team.

**Comment by kelelbrainz** [comment]
Oh ok ...buh from your own experiences could you give me some directions?

**Comment by tstt** [comment]
Google it, then you should find their website usually.
