### ISSUE TITLE
ERC-20: Add token price display for BCAC

### ISSUE THREAD

**Issue by bcachain** [consenlabs/token-profile#4554]
block.cc Link: https://block.cc/coin/business-credit-alliance-chain
Token Symbol: BCAC
Token Contract Address: 0x1aBdb309aa592f00a101c545168BFDF9a6Ec61CE
Etherscan Link: https://etherscan.io/token/0x1aBdb309aa592f00a101c545168BFDF9a6Ec61CE

**Comment by tstt** [comment]
已添加，请确认。

**Comment by bcachain** [comment]
Thank you.

**Comment by bcachain** [comment]
Works
Thank you again.
