### ISSUE TITLE
ERC-20 ： 添加 IT 价格显示

### ISSUE THREAD

**Issue by idax-exchange** [consenlabs/token-profile#4560]
block.cc 链接：http://block.cc/coin/idax-token
代币简称：IT
合约地址：0xbf5f8bfcee9502a30018d91c63eca66980e6e9bb 
Etherscan 链接：https://etherscan.io/token/0xbf5f8bfcee9502a30018d91c63eca66980e6e9bb

请帮忙处理一下，谢谢了!

**Comment by tstt** [comment]
已添加，请确认。
