### ISSUE TITLE
添加UENC价格显示

### ISSUE THREAD

**Issue by phomespace** [consenlabs/token-profile#4584]
ERC-20 ： 添加 UENC 价格显示
block.cc 链接：https://mifengcha.com/coin/universalenergychain
代币简称：UENC
合约地址：0xb3dd5dce850dca7519e74a943568b69f958df52c
Etherscan 链接：https://etherscan.io/token/0xb3dd5dce850dca7519e74a943568b69f958df52c

**Comment by tstt** [comment]
已添加，请确认。
