### ISSUE TITLE
ERC-20: Add token price display for EST

### ISSUE THREAD

**Issue by ressefan** [consenlabs/token-profile#4598]
block.cc Link: http://block.cc/coin/event-sponsorship-token
Token Symbol: EST
Token Contract Address: 0xd427c628c5f72852965fadaf1231b618c0c82395
Etherscan Link: https://etherscan.io/token/0xd427c628c5f72852965fadaf1231b618c0c82395

**Comment by tstt** [comment]
已添加，请确认。
