### ISSUE TITLE
ERC-20 ： 添加 新HAI 价格显示

### ISSUE THREAD

**Issue by HAIchain** [consenlabs/token-profile#4611]
block.cc 链接：https://mifengcha.com/coin/hangkei-ai-chain
代币简称：HAI
合约地址：0xaa9b9db5c07d8f00a48d0eb52d73f9a48048d53d
Etherscan 链接：https://etherscan.io/token/0xaa9b9db5c07d8f00a48d0eb52d73f9a48048d53d

**Comment by tstt** [comment]
已添加，请确认
