### ISSUE TITLE
提交token资料

### ISSUE THREAD

**Issue by NORTHSTARCHAIN** [consenlabs/token-profile#4626]
我克隆了一个仓库在本地，然后更新资料，提交到本地就算是已经提交了吗，还有其他操作吗？

**Comment by tstt** [comment]
按教程操作即可：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Comment by zjp168** [comment]
Why can't the contract address be transferred out? 
0xb89215d9af9183aeb3f843c33e61683e42526e04
