### ISSUE TITLE
令牌符号NEA 为什么钱包里显示NEA_UNKNOWN

### ISSUE THREAD

**Issue by lusina50551** [consenlabs/token-profile#4675]
令牌地址0x9f6a785cac5ba3599f4d2e4bea22e90b7c8880e0
令牌符号NEA
为什么钱包里显示NEA_UNKNOWN

**Comment by tstt** [comment]
imToken 自 2019.8.8 开始，对于未提交 Token Profile 的同名代币会在其代币名后添加「_UNKNOWN」标记，以帮助用户区分代币。

项目方可向 imToken 提交其代币的 Token Profile，代币资料通过后，「_UNKNOWN」标记会自动去除。
