### ISSUE TITLE
Newly Listed Tokens

### ISSUE THREAD

**Issue by Ascii124** [consenlabs/token-profile#4678]
I have quite a few newly listed tokens not yet listed on Imtoken. Im sorry to submit it this way, Ive tried through the Imtoken App and battling slightly.
P2PX, ONE, HLOB, ETHPLO, DUSK, CNNS. 
These are only a few of the ERC 20 token Airdrops I am part of, still have over 200 tokens to be Submitted and Airdropped.

**Comment by tstt** [comment]
Token Profile is required to be pull request by the Tokens' official.
You can provide this tutorial to them: https://github.com/consenlabs/token-profile#token-profile-guideline
