### ISSUE TITLE
The SmartFund token has not been replaced with a new name

### ISSUE THREAD

**Issue by fergus789** [consenlabs/token-profile#4700]
We have updated the SmartFund related information, https://github.com/consenlabs/token-profile/pull/4653

Found that the relevant token has not been replaced with a new name, 

The old name begins with “$” and the new name begins with "S"

In the APP, it still shows "$", now it is confusing to the user, trouble to update, thanks!!

![TIM图片20190814102432](https://user-images.githubusercontent.com/50763141/62990248-d11c6800-be7d-11e9-8a9f-291c2bd1d797.png)
![TIM图片20190814102500](https://user-images.githubusercontent.com/50763141/62990270-eb564600-be7d-11e9-845d-763f3056dce9.png)

**Comment by fergus789** [comment]
The problem has been solved, thanks.

**Comment by tstt** [comment]
Welcome to recommend imToken 2.0 to your token holders to manage their token.
