### ISSUE TITLE
ERC-20: Add token price display for ARPA

### ISSUE THREAD

**Issue by alex-arpa** [consenlabs/token-profile#4735]
block.cc Link: https://mifengcha.com/coin/arpa-chain
Token Symbol: ARPA
Token Contract Address: 0xba50933c268f567bdc86elac131be072c6b0b71a
Etherscan Link: https://etherscan.io/token/0xba50933c268f567bdc86elac131be072c6b0b71a

**Comment by tstt** [comment]
https://etherscan.io/address/0xba50933c268f567bdc86elac131be072c6b0b71a
合约地址无效，请自查

**Comment by tstt** [comment]
已添加，请确认
