### ISSUE TITLE
参考教程，确保通过自动检查

### ISSUE THREAD

**Issue by godrights** [consenlabs/token-profile#4781]
参考教程，确保通过自动检查：
![image](https://user-images.githubusercontent.com/16997688/63679568-29f7e300-c824-11e9-993c-a40201f214a8.png)

教程链接：
https://github.com/consenlabs/token-profile#token-profile-guideline

_Originally posted by @tstt in https://github.com/consenlabs/token-profile/pull/4779#issuecomment-524785443_

**Comment by tstt** [comment]
merged
