### ISSUE TITLE
ERC-20: 添加 IFX 价格显示

### ISSUE THREAD

**Issue by qingshang8433** [consenlabs/token-profile#4812]
block.cc 链接：https://block.cc/coin/ifx
代币简称：ifx
合约地址：0x68dE11BC4B2623E352E92aDf0a2DaDB0dA9A18af
Etherscan 链接：https://etherscan.io/token/0x68dE11BC4B2623E352E92aDf0a2DaDB0dA9A18af

**Comment by tstt** [comment]
已添加，请确认。
