### ISSUE TITLE
ERC-20 ： 添加 EON 价格显示

### ISSUE THREAD

**Issue by mcwangluo** [consenlabs/token-profile#4834]
block.cc 链接：https://mifengcha.com/coin/dimension
代币简称：EON
合约地址：0x4CB10F4df4BF4F64D4797d00D468181EF731Be9A
Etherscan 链接：https://etherscan.io/token/0x4CB10F4df4BF4F64D4797d00D468181EF731Be9A

**Comment by sfsy520** [comment]
已添加，请确认。

**Comment by danielhy22** [comment]
已确认，EON上币ImToken，感谢！~
