### ISSUE TITLE
ERC-20 ： 添加 BQQQ 价格显示

### ISSUE THREAD

**Issue by suchangqin** [consenlabs/token-profile#4843]
block.cc 链接：https://mifengcha.com/coin/bitsdaq
代币简称：BQQQ
合约地址：0x1b80eeeadcc590f305945bcc258cfa770bbe1890
Etherscan 链接：https://etherscan.io/token/0x1b80eeeadcc590f305945bcc258cfa770bbe1890

**Comment by sfsy520** [comment]
已添加，请确认。
