### ISSUE TITLE
ERC-20：添加GE价格显示

### ISSUE THREAD

**Issue by censentech** [consenlabs/token-profile#4864]
block.cc 链接：https://www.zg.com/trade/ge_usdt
代币简称：GE
合约地址：0xE8f030D3a6e82C84c73460B46a28016f3d744954
Etherscan 链接：https://etherscan.io/address/0xE8f030D3a6e82C84c73460B46a28016f3d744954

**Comment by sfsy520** [comment]
已添加，请确认。
