### ISSUE TITLE
ERC-20 ： 添加 KPC8 价格显示

### ISSUE THREAD

**Issue by kpaycoin** [consenlabs/token-profile#4889]
block.cc 链接：https://mifengcha.com/coin/kpc8
代币简称：KPC8
合约地址：0xd8f93d967FA21A0A826a3BD4601adA4bB468823d
Etherscan 链接：https://etherscan.io/token/0xd8f93d967fa21a0a826a3bd4601ada4bb468823d

**Comment by sfsy520** [comment]
已添加，请确认。

**Comment by sfsy520** [comment]
已添加，请确认
