### ISSUE TITLE
Add MLC Token

### ISSUE THREAD

**Issue by saincehcy** [consenlabs/token-profile#4907]
### 团队背景：team backgournd 
MLC团队分布在新加坡、香港、硅谷和北京，核心成员由早期研究区块链领域的技术团队支持以及一批从事艺术品行业十年以上的资深专家。王江（Ray）和James于2019年在新加坡创建MLC ，希望通过MLC产业链平台可以实现艺术品真正价值的发现；艺术品的溯源和保真；大师、艺术家的发掘和培养；艺术品行业的资源整合；评估和鉴定的标准化和权威化；艺术品市场秩序的回归。最终实现艺术品市场的发展和壮大。
MLC team members spread around the world such as in Singapore, Hong Kong, Silicone Valley and Beijing. The core members include a tech team which prviously studied the field of block chain and a group of experts who are in the art industry for more than 10 years. Ray and James founded MLC in Singapore in 2019, and they hope to discover the true value of arts through MLC industry chain platform. For example, it can be used for the source tracing and fidelity of arts, the discovery and training of art gurus and artists, the resources integration of art industry, the standardization and authentication of art evaluation and inspection as well as the return for order in the art markets. Eventually, MLC will achieve the development and expansion of the art markets. 
### 项目基本情况：project basic information 
MLC由旗下艺术品新零售商城、艺术品交易市场、艺术品拍卖行等几个生态组成MLC品牌，目前仅由官方渠道发放，也通过艺术品的交易流通中同步释放，同时用户通过MLC交易平台可轻松实现币币兑换。目前在其DApp的尝试及探索中，并继续加强与第三方基于以太坊生态的连接共识。同样，MLC支持以区块链的模式介入各大艺术品商城和艺术品交易所，贯穿艺术大师作品、消费级艺术品、艺术衍生品和艺术品版权、产权等方面的收藏、购买、转让、交割的全节点。
The MLC brand is composed by its art retail stores, art trade markets and art auction companies. MLC coins are released from the official channel, and theybare also released synchronously while arts are trading. Users also can use the MLC trade platform to easily exchange electronic currencies. Currently we are researching and attempting to keep reinforcing the consensus of the connection with the third party based on the ethereum ecology. Also, MLC platform supports large art galleries and art auction companies with the form of block chain, so that all the information of collecting, purchse, transfer and delivery of the work of all art gurus,consumer arts, art derivatives, and art copy rights as well as intellectual rights will be put in all the nodes on the block chain. 
### 更多关于MLC的信息 more about MLC
官网official website：https：//www.mlcoin.top/
      https：//www.mlcgo/
微博Weibo：https：//weibo.com/mlcgo
电报Telegram：https：//t.me/mlcgoGroup
币用Beyong：https://0.plus/mlcgogroup
Twitter：https：//twitter.com/mlcgogroup
### 建议限气：
     60000
### 收录的交易所 
     MLC Exchange : www.mlcgo.co

**Comment by sfsy520** [comment]
请仔细阅读要求，并提供符合要求的PR
教程链接：
https://github.com/consenlabs/token-profile#token-profile-guideline
