### ISSUE TITLE
ERC-20 ： 添加 QQB价格显示

### ISSUE THREAD

**Issue by QQBChain** [consenlabs/token-profile#4966]
block.cc 链接：https://mifengcha.com/coin/qualified-quality-block
代币简称：QQB
合约地址：0x663085225320c7afae10f3f1982eaa7324ea55da
Etherscan 链接：https://etherscan.io/token/0x663085225320c7afae10f3f1982eaa7324ea55da

**Comment by sfsy520** [comment]
已添加，请确认。
