### ISSUE TITLE
ERC-20 ： 添加 TC 价格显示

### ISSUE THREAD

**Issue by TasteChain1** [consenlabs/token-profile#5020]
ERC-20 ： 添加TC价格显示
block.cc 链接：https://mifengcha.com/coin/tastechain
代币简称：TC
合约地址：0x2f7315dc40A7f1201b903d65dBD0eEC93cD14f37
Etherscan 链接：https://etherscan.io/token/0x2f7315dc40A7f1201b903d65dBD0eEC93cD14f37

**Comment by sfsy520** [comment]
已添加
