### ISSUE TITLE
ERC-20: Add token price display for BCS

### ISSUE THREAD

**Issue by bcachain** [consenlabs/token-profile#5048]
block.cc Link: https://mifengcha.com/coin/bcachain
Token Symbol: BCS
Token Contract Address: 0x31274db8b609Df99E5988ee527071643b5160Fc3
Etherscan Link: https://etherscan.io/token/0x31274db8b609df99e5988ee527071643b5160fc3

**Comment by sfsy520** [comment]
Done

**Comment by bcachain** [comment]
Thank you. @sfsy520
