### ISSUE TITLE
ERC-20 ： 添加 PGS 价格显示

### ISSUE THREAD

**Issue by jason-zuo** [consenlabs/token-profile#5080]
ERC-20 ： 添加 PGS 价格显示
block.cc 链接：https://mifengcha.com/coin/pegasus
代币简称：PGS
合约地址：0x931ad0628aa11791C26FF4d41ce23E40C31c5E4e
Etherscan 链接:https://etherscan.io/address/0x931ad0628aa11791C26FF4d41ce23E40C31c5E4e

**Comment by sfsy520** [comment]
已添加，请确认
