### ISSUE TITLE
NRC6 token logo change please

### ISSUE THREAD

**Issue by humairk** [consenlabs/token-profile#509]
Contract Address ; 0x7C0d150896C2e1082Ca7bb80E866a32cad4f8bBF  
https://etherscan.io/token/0x7c0d150896c2e1082ca7bb80e866a32cad4f8bbf

Logo set please
https://image.ibb.co/c9CWLJ/NRC_28X28_logo.PNG

https://image.ibb.co/c9CWLJ/NRC_32x32_logo.jpg

**Comment by wenyanwang** [comment]
你好，请阅读我们的教程，通过PR提交，谢谢。
