### ISSUE TITLE
ERC 20：增加XB价格显示

### ISSUE THREAD

**Issue by xinbipro** [consenlabs/token-profile#5109]
block.cc 链接：https://mifengcha.com/coin/xinbi-token
代币简称：XB
合约地址：0xce43921b2fbf3C7F4CF47E28b8261E8e31bc6106
Etherscan 链接：https://etherscan.io/token/0xce43921b2fbf3C7F4CF47E28b8261E8e31bc6106

**Comment by sfsy520** [comment]
已添加，请确认
