### ISSUE TITLE
添加CELR价格显示

### ISSUE THREAD

**Issue by Dominator008** [consenlabs/token-profile#5138]
block.cc 链接：https://mifengcha.com/coin/celer-network
代币简称：CELR
合约地址：0x4f9254c83eb525f9fcf346490bbb3ed28a81c667
Etherscan 链接：https://etherscan.io/token/0x4f9254c83eb525f9fcf346490bbb3ed28a81c667

**Comment by sfsy520** [comment]
已添加，请确认

**Comment by Dominator008** [comment]
已确认，谢谢
