### ISSUE TITLE
ERC-20: Add token price display for ESCX

### ISSUE THREAD

**Issue by Expertstudent** [consenlabs/token-profile#5153]
block.cc Link: https://mifengcha.com/coin/escx-token
Token Symbol: ESCX
Token Contract Address: 0xa1f18ba7a1fa1f2c15eae5c42e722278f1235b7a
Etherscan Link: https://etherscan.io/address/0xa1f18ba7a1fa1f2c15eae5c42e722278f1235b7a

**Comment by sfsy520** [comment]
Blockcc 上无交易数据
