### ISSUE TITLE
ERC-20 ： 添加 SKM 价格显示

### ISSUE THREAD

**Issue by lk2684753** [consenlabs/token-profile#5194]
ERC-20 ： 添加 SKM 价格显示
block.cc 链接：https://mifengcha.com/coin/skrumble-network
代币简称：SKM
合约地址：0x048fe49be32adfc9ed68c37d32b5ec9df17b3603
Etherscan 链接：https://etherscan.io/token/0x048fe49be32adfc9ed68c37d32b5ec9df17b3603

**Comment by sfsy520** [comment]
已添加，请确认
