### ISSUE TITLE
ERC20: 添加FCT价格显示

### ISSUE THREAD

**Issue by lindawei** [consenlabs/token-profile#5215]
蜜蜂查地址：https://mifengcha.com/coin/africa-chain-token
代币名称：FCT
合约地址：0x394594b06adb8f54e393bfaf13ca5786bcd3f9bb
Etherscan 链接：https://cn.etherscan.com/token/0x394594b06adb8f54e393bfaf13ca5786bcd3f9bb

**Comment by sfsy520** [comment]
已添加，请确认
