### ISSUE TITLE
ERC20: 添加ODY代币社区信息

### ISSUE THREAD

**Issue by Zsx6666** [consenlabs/token-profile#5286]
代币简称：ODY
合约地址：0x026f8d523d49f36db657e012c96488465d8d88f9
Etherscan 链接：https://etherscan.io/token/0x026f8d523d49f36db657e012c96488465d8d88f9
Twitter：https://twitter.com/OdyCommunity
facebook：https://www.facebook.com/Odyssey-Club-111383936975439/

**Comment by sfsy520** [comment]
添加社区信息请提交PR。
