### ISSUE TITLE
更改新老合约代币信息

### ISSUE THREAD

**Issue by bitstd** [consenlabs/token-profile#531]
请将0xeeeec8542dec1993c76873524aca8ea9af9e2447的代币符号改为bss4，将0x6fc22d1f6852af2bcea6cb749033ccb6b4d3177a的代币符号改为bss

**Comment by wenyanwang** [comment]
你好，旧合约已经更改为bss-old，新的合约已经修改，请向社区发出公告重新搜索添加代币，谢谢。
