### ISSUE TITLE
旧的合约能帮忙删除吗？

### ISSUE THREAD

**Issue by scsp1064** [consenlabs/token-profile#5329]
旧的合约FILT：0x21DBF2c44362b6113B25D4B125BBEDF4Df2Bef6a
删除搜索的信息和图标显示，之前提交替换了图标灰色，团队要求删除掉不要了，因为有新的在上面显示。

**Comment by sfsy520** [comment]
非常抱歉，更换合约将旧的Logo做退色处理即可，无需删除的。
