### ISSUE TITLE
关于如何更新imToken APP的 币种 Token profile

### ISSUE THREAD

**Issue by chelizissh** [consenlabs/token-profile#5359]
我需要修改币种的简介信息，是不是直接新建一个.json文件 提交合并到官方仓库即可？望给解答，谢谢

**Comment by sfsy520** [comment]
在原有PR上修改即可。

**Comment by chelizissh** [comment]
![pr](https://user-images.githubusercontent.com/58319718/70310908-a2226b80-184b-11ea-89a5-3763044c135f.jpg)  
我想改的是这个红框的内容
