### ISSUE TITLE
Show QEC Price

### ISSUE THREAD

**Issue by qec-eva** [consenlabs/token-profile#5381]
block.cc 链接：https://block.cc/coin/quantisation-ecology-chain
代币简称：QEC
合约地址：0xdd62b07841cad953e2ab6dafc798f9f75f6582c2
Etherscan 链接：https://etherscan.io/token/0xdd62b07841cad953e2ab6dafc798f9f75f6582c2

**Comment by sfsy520** [comment]
已添加，请查看。
