### ISSUE TITLE
Update profile to imtoken

### ISSUE THREAD

**Issue by erold012** [consenlabs/token-profile#5383]
token symbol - MTCX
contract address - 0x74658fB5f7fF3Bc7d70f7F792d53fd74f89dC055
etherscan link - https://etherscan.io/token/0x74658fB5f7fF3Bc7d70f7F792d53fd74f89dC055?a=0x137c10041bacf5e058e371fe8cd2ad6980e6a4db

**Comment by sfsy520** [comment]
请参考教程提交PR
