### ISSUE TITLE
ERC-20: 添加UCT价格显示

### ISSUE THREAD

**Issue by UCOT** [consenlabs/token-profile#5397]
block.cc 链接：https://mifengcha.com/coin/ubique-chain-of-things
代币简称：UCT
合约地址：0x3c4bEa627039F0B7e7d21E34bB9C9FE962977518
Etherscan 链接: https://etherscan.io/address/0x3c4bEa627039F0B7e7d21E34bB9C9FE962977518

**Comment by sfsy520** [comment]
已添加，请确认

**Comment by UCOT** [comment]
@sfsy520 检查发现点开UCT显示的仍是暂无此token档案
