### ISSUE TITLE
代币Logo不能正常显示，请求帮助

### ISSUE THREAD

**Issue by ipweb-group** [consenlabs/token-profile#5411]
追加IPOS代币的时候由于在地址前面混入了空格导致Token Profile不能正常显示。（Add IPOS TOKEN #5401）
后来提交了更新PR，消除了空格（Update IPOS Token #5410）
现在显示如下图，用关键字检索以后，正确的Token Profile不能正常显示Logo，错误的代币地址依旧显示。效果如下图。
<img width="409" alt="image" src="https://user-images.githubusercontent.com/46769994/71398923-5d793b80-2665-11ea-8dbc-8fc585ffa5ea.png">

请问我应该怎么对应这个问题，谢谢。

**Comment by sfsy520** [comment]
已处理，请查看。
