### ISSUE TITLE
ERC-20 ： 添加 ZT 价格显示

### ISSUE THREAD

**Issue by YeongAe** [consenlabs/token-profile#5441]
block.cc 链接：https://block.cc/coin/ztcoin
代币简称：ZT
合约地址：0xFE39e6a32AcD2aF7955Cb3D406Ba2B55C901f247
Etherscan 链接：https://etherscan.io/token/0xFE39e6a32AcD2aF7955Cb3D406Ba2B55C901f247

**Comment by sfsy520** [comment]
已添加，请确认。
