### ISSUE TITLE
ERC-20: 添加UCT价格显示

### ISSUE THREAD

**Issue by UCOT** [consenlabs/token-profile#5540]
block.cc 链接：https://mifengcha.com/coin/ubique-chain-of-things
代币简称：UCT
合约地址：0x3c4bEa627039F0B7e7d21E34bB9C9FE962977518
Etherscan 链接: https://etherscan.io/address/0x3c4bEa627039F0B7e7d21E34bB9C9FE962977518

之前并未上传成功，所以创建这个新的issue，希望排查。

**Comment by sfsy520** [comment]
已经更新，请再次查看

**Comment by UCOT** [comment]
@sfsy520 仍然没有显示
