### ISSUE TITLE
错误信息显示这不是一个邮箱，合并失败，但这确实是一个邮箱啊

### ISSUE THREAD

**Issue by TepletonIO** [consenlabs/token-profile#5542]
https://github.com/consenlabs/token-profile/commit/b752337b7a4731111ffe2dc6aeb9a536283499fd

请问我需要换个邮箱重新提交么

**Comment by sfsy520** [comment]
请问在哪看到的错误信息，截图看下。

**Comment by TepletonIO** [comment]
![image](https://user-images.githubusercontent.com/54060469/75308877-8054e580-588a-11ea-9e52-d06e98742f75.png)这里点进去 。 
![image](https://user-images.githubusercontent.com/54060469/75308995-c0b46380-588a-11ea-8617-c3094ec59c14.png) 这里有ge个  红 x 点进去 ，然后看detail
![Uploading image.png…]()

**Comment by TepletonIO** [comment]
https://github.com/consenlabs/token-profile/commit/b752337b7a4731111ffe2dc6aeb9a536283499fd
这个链接

**Comment by TepletonIO** [comment]
json file 0x137CF4D658e3d6D3fb857Da68182519D4Ac8a778.json's email field  must be an email
刚发现我没有提交过这个文件，不知道怎么的就躺枪了

**Comment by sfsy520** [comment]
已合并，请查看。
