### ISSUE TITLE
Add ETY price

### ISSUE THREAD

**Issue by ety369** [consenlabs/token-profile#5590]
block.cc Link: https://mifengcha.com/coin/ethereum-cloud
Token Symbol: ETY
Token Contract Address: 0x37DB56E0FbA0BE2cbf96e3de3BFF8096b6D59179
Etherscan Link: https://etherscan.io/token/0x37DB56E0FbA0BE2cbf96e3de3BFF8096b6D59179

**Comment by sfsy520** [comment]
已添加，请确认。
