### ISSUE TITLE
 添加 GPO 价格显示

### ISSUE THREAD

**Issue by moonbeamwang** [consenlabs/token-profile#5608]
ERC-20 ： 添加 GPO 价格显示
block.cc 链接：https://mifengcha.com/coin/galaxy-pool-coin
代币简称：GPO
合约地址：0x5cf501e64786444e025c5b24025f98399538ea5d
Etherscan 链接：https://etherscan.io/token/0x5cf501e64786444e025c5b24025f98399538ea5d

**Comment by sfsy520** [comment]
已添加，请确认。
