### ISSUE TITLE
ERC-20 ： 添加 WXB 价格显示

### ISSUE THREAD

**Issue by wxbdev20** [consenlabs/token-profile#5639]
block.cc 链接：https://mifengcha.com/coin/wuxingbi
代币简称：WXB
合约地址：0x572328202d37b031b490f6659d8549e7bd712324
Etherscan 链接：https://etherscan.io/token/0x572328202d37b031b490f6659d8549e7bd712324

**Comment by sfsy520** [comment]
已添加，请确认。
