### ISSUE TITLE
ERC-20 ： 添加 TRB 价格显示

### ISSUE THREAD

**Issue by yokosogithub** [consenlabs/token-profile#5659]
ERC-20 ： 添加 TRB 价格显示
TELLOR链接：https://tellor.io/
代币简称：trb
合约地址：0x0ba45a8b5d5575935b8158a88c631e9f9c95a2e5
Etherscan 链接：https://etherscan.io/token/0x0ba45a8b5d5575935b8158a88c631e9f9c95a2e5

**Comment by sfsy520** [comment]
请参考教程提交Issue，附上blockcc相关链接。
