### ISSUE TITLE
ERC-20 ： 添加 TRB 价格显示

### ISSUE THREAD

**Issue by yokosogithub** [consenlabs/token-profile#5660]
block.cc 链接：https://mifengcha.com/coin/tellor
代币简称：TRB
合约地址：0x0ba45a8b5d5575935b8158a88c631e9f9c95a2e5
Etherscan 链接：https://etherscan.io/token/0x0ba45a8b5d5575935b8158a88c631e9f9c95a2e5

**Comment by sfsy520** [comment]
已添加，请确认、
