### ISSUE TITLE
ERC-20 - Add Jobchain (JOB) Price

### ISSUE THREAD

**Issue by JobchainOfficial** [consenlabs/token-profile#5670]
block.cc ：https://mifengcha.com/coin/jobchain
Token：JOB
Contract ：0xdfbc9050f5b01df53512dcc39b4f2b2bbacd517a
Etherscan ：https://etherscan.io/token/0xdfbc9050f5b01df53512dcc39b4f2b2bbacd517a

**Comment by sfsy520** [comment]
已添加，请确认。
