### ISSUE TITLE
ERC-20 ： 添加 UTI 价格显示

### ISSUE THREAD

**Issue by markwork02** [consenlabs/token-profile#5674]
block.cc 链接：https://mifengcha.com/coin/utiop
代币简称：UTI
合约地址：0xfb2c3b20307807c9703b3ee41a3d142cfb5bb162
Etherscan 链接：https://cn.etherscan.com/token/0xfb2c3b20307807c9703b3ee41a3d142cfb5bb162

**Comment by sfsy520** [comment]
已添加，请确认。
