### ISSUE TITLE
ERC-20 ： 添加 UENC 价格显示

### ISSUE THREAD

**Issue by cyh036** [consenlabs/token-profile#5679]
ERC-20 ： 添加 UENC 价格显示
block.cc 链接：https://mifengcha.com/coin/universalenergychain
代币简称：UENC
合约地址：0xf46df22b35d0f56c90241c362db892ddf62da60b
Etherscan 链接：https://etherscan.io/token/0xf46df22b35d0f56c90241c362db892ddf62da60b

**Comment by sfsy520** [comment]
已添加，请确认。
