### ISSUE TITLE
#5681 99X token 无法在Imtoken搜索 以及无法显示

### ISSUE THREAD

**Issue by Xinshu1314** [consenlabs/token-profile#5749]
----------ch----------
99X token 无法在 Imtoken 中显示 
合约地址：0xe8684d50f7784377aE15Cad936F263f348aaA6Ab
----------en----------
99x token cannot be displayed in imtoken
Contract address: 0xe8684d50f7784377ae15cad936f263f348aaa6ab

**Comment by Xinshu1314** [comment]
@sfsy520 麻烦 处理下 在App内无法显示头像 也无法搜索到

**Comment by IPCM** [comment]
#5730# Contract address: 0xECf1624E155b022d36602b384402DfF439D4D6AF

**Comment by IPCM** [comment]
The IPCM token logo is not displayed in the application; Search contract address not shown

**Comment by IPCM** [comment]
#5730# Contract address: 0xECf1624E155b022d36602b384402DfF439D4D6AF
The IPCM token logo is not displayed in the application; Search contract address not shown
@sfsy520  thanks~

**Comment by sfsy520** [comment]
已修复，请查看。
