### ISSUE TITLE
ERC-20 添加海伯利安 HYN 价格显示

### ISSUE THREAD

**Issue by moyaying** [consenlabs/token-profile#5796]
ERC-20 ： 添加 HYN 价格显示
block.cc 链接：https://www.mifengcha.com/coin/hyperion
代币简称：hyn
合约地址：0xe99a894a69d7c2e3c92e61b64c505a6a57d2bc07
Etherscan 链接：https://etherscan.io/token/0xe99a894a69d7c2e3c92e61b64c505a6a57d2bc07

**Comment by sfsy520** [comment]
已添加，请确认。
