### ISSUE TITLE
Add USDE token profile

### ISSUE THREAD

**Issue by cuhao191616** [consenlabs/token-profile#5833]
官方網站：https://excoin.io/

团队背景：
EXcoin是一家根据伯利兹国家相关法律在伯利兹国家注册成立的公司，该公司运营网站https://www.excoin.io，该网站是一个专门供用户进行数字期权交易和提供相关服务的平台。EXcoin是全球首家推出数字期权交易的区块链衍生品交易所。EXcoin向全球用户提供各种创新型区块链资产衍生品，由EXcoin Limited.负责运营。EXcoin公司研发了证券、期货、国际金融衍生品的交易系统、结算清算系统、风控系统、行情系统、量化交易系统、用户CRM系统、社交系统等完整的交易生态系统。其开发的平台承载国际金融衍生品成交额就达数千亿美元。EXcoin公司具备近十年的衍生品交易平台技术实力和运营能力，能够让交易所快速稳定增长，EXcoin团队将致力于成为全球最专业的数字期权衍生品交易所，为庞大的传统金融衍生品投资者提供更为熟悉的数字期权衍生品交易服务，给予所有客户最优质的一站式全方位金融理财教育与投资平台。EXcoin数字期权衍生品交易平台是合法持有牌照的专业交易平台-虚拟货币电子钱包、加密对加密交易、法币对加密货币的双向交易、法币对法币交易、外汇交易、欧元/美元、英镑/日元等。
EXcoin Limited 运营公司受伯利兹国际金融服务委员会监管，执照号:171708。
EXcoin Limited 获得了美国合法运营的MSB牌照，由美国Fincen监管，执照号:409415。
EXcoin Limited 获得了美国合法运营的NFA牌照，执照号: 0529638。
EXcoin Limited 获得了加拿大合法运营的MSB牌照，执照号：M20254181

媒体报道：https://kknews.cc/zh-tw/finance/8q2qjln.html
收录的交易所：無
转账所需 Gas Limit（对 ERC-20 项目方）：默认（默认为 60000）
合約地址：0xf7ec11db22bd76f9e1f9485ed42f4118836d35bd

**Comment by sfsy520** [comment]
请提交PR

**Comment by cuhao191616** [comment]
[0xf7ec11db22bd76f9e1f9485ed42f4118836d35bd.zip](https://github.com/consenlabs/token-profile/files/4745096/0xf7ec11db22bd76f9e1f9485ed42f4118836d35bd.zip)
