### ISSUE TITLE
ERC-20 ： 添加 NEST 价格显示

### ISSUE THREAD

**Issue by NestProtocol** [consenlabs/token-profile#5834]
ERC-20 ： 添加 NEST 价格显示
block.cc 链接：https://www.mifengcha.com/coin/nest
代币简称：NEST
合约地址：0x04abeda201850ac0124161f037efd70c74ddc74c
Etherscan 链接：https://etherscan.io/token/0x04abeda201850ac0124161f037efd70c74ddc74c

**Comment by sfsy520** [comment]
已添加，请确认
