### ISSUE TITLE
添加USDE令牌配置文件

### ISSUE THREAD

**Issue by cuhao191616** [consenlabs/token-profile#5852]
官方網站：https : //excoin.io/

團隊背景：
EXcoin是一家根據伯利茲國家相關法律在伯利茲國家註冊成立的公司，該公司運營網站https://www.excoin.io，該網站是一個專門供用戶進行數字預算交易和提供相關服務的公司EXcoin向全球用戶提供各種創新型區塊鏈資產衍生品，由EXcoin Limited。負責運營。EXcoin公司研發了證券，期貨，國際金融衍生品的交易系統，結算清算系統，風控系統，行情系統，量化交易系統，用戶CRM系統，社交系統等完整的交易生態系統。 EXcoin公司超過近十年的衍生品交易平台技術實力和運營能力，能夠讓交易所快速穩定增長，EXcoin團隊將致力於成為全球最專業的數字預算衍生品交易所，為龐大的傳統金融衍生品投資者提供更為熟悉的數字預算衍生品交易服務，給予所有客戶最優質的一站式全方位金融理財教育與投資平台。專業交易平台-虛擬貨幣電子錢包，加密對加密交易，法幣對加密貨幣的雙向交易，法幣對法幣交易，外匯交易，歐元/美元，英鎊/日元等
。EXcoin Limited運營公司受伯利茲國際金融服務委員會監管，執照號：171708。EXcoin
Limited獲得了美國合法運營的MSB許可證，由美國Fincen監管，執照號：
409415。EXcoin Limited獲得了美國合法運營的NFA許可，
執照號：0529638。EXcoin Limited獲得了加拿大合法運營的MSB牌照，執照號：M20254181

媒體報導：https
:
//kknews.cc/zh-tw/finance/8q2qjln.html 收錄的交易所：無轉賬所需瓦斯限值（對ERC-20項目方）：其他（總計為60000）
合約地址：0xf7ec11db22bd76f9e1f9485ed42f4118836d35bd
[0xf7ec11db22bd76f9e1f9485ed42f4118836d35bd.zip](https://github.com/consenlabs/token-profile/files/4768273/0xf7ec11db22bd76f9e1f9485ed42f4118836d35bd.zip)

**Comment by sfsy520** [comment]
请提交PR

**Comment by cuhao191616** [comment]
https://excoin.io/ch/news-data.php?id=294
