### ISSUE TITLE
ERC-20: Add token price display for TWEE

### ISSUE THREAD

**Issue by tweebaa** [consenlabs/token-profile#5860]
block.cc Link: https://www.mifengcha.com/coin/tweebaa
Token Symbol: TWEE
Token Contract Address: 0x2b6ff53fc2493ccd5202d80a6c439741414c5ff2
Etherscan Link: https://etherscan.io/token/0x2b6ff53fc2493ccd5202d80a6c439741414c5ff2

**Comment by sfsy520** [comment]
已添加，请确认。
