### ISSUE TITLE
ERC-20添加DMG价格显示

### ISSUE THREAD

**Issue by hulongjun** [consenlabs/token-profile#5918]
block.cc 链接：https://www.mifengcha.com/coin/dmmgovernance
代币简称：DMG
合约地址：0xEd91879919B71bB6905f23af0A68d231EcF87b14
Etherscan 链接：https://cn.etherscan.com/token/0xEd91879919B71bB6905f23af0A68d231EcF87b14

**Comment by sfsy520** [comment]
已添加，请确认。
