### ISSUE TITLE
ERC-20 ： 添加 UENC 价格显示

### ISSUE THREAD

**Issue by cyh036** [consenlabs/token-profile#5924]
ERC-20 ： 添加 UENC 价格显示
block.cc 链接：https://www.mifengcha.com/coin/universalenergychain
代币简称：UENC
合约地址：0xf46dF22B35d0F56c90241C362db892dDf62da60B
Etherscan 链接：https://etherscan.io/token/0xf46dF22B35d0F56c90241C362db892dDf62da60B

**Comment by cyh036** [comment]
以前提交过，现在突然不显示价格了。

**Comment by cyh036** [comment]
麻烦帮我解决一下这个问题，感谢！

**Comment by sfsy520** [comment]
由于blockcc查询不到交易对，故无价格显示。
