### ISSUE TITLE
ERC-20 ： 添加 AMPL 价格显示

### ISSUE THREAD

**Issue by hulongjun** [consenlabs/token-profile#5926]
block.cc 链接：https://www.mifengcha.com/coin/ampleforth
代币简称：AMPL
合约地址：0xd46ba6d942050d489dbd938a2c909a5d5039a161
Etherscan 链接：https://etherscan.io/token/0xd46ba6d942050d489dbd938a2c909a5d5039a161

**Comment by sfsy520** [comment]
已添加，请确认。
