### ISSUE TITLE
添加AMPL价格信息

### ISSUE THREAD

**Issue by hulongjun** [consenlabs/token-profile#5931]
block.cc链接：https://www.mifengcha.com/coin/ampleforth
代币缩写：AMPL
合约地址：0xd46ba6d942050d489dbd938a2c909a5d5039a161
Etherscan链接：https://cn.etherscan.com/token/0xd46ba6d942050d489dbd938a2c909a5d5039a161

**Comment by sfsy520** [comment]
已添加，请确认。
