### ISSUE TITLE
ERC-20 ：添加MCB价格显示

### ISSUE THREAD

**Issue by realmeh** [consenlabs/token-profile#5950]
block.cc 链接：https://www.mifengcha.com/coin/mcdex
代币简称：MCB
合约地址：0x4e352cF164E64ADCBad318C3a1e222E9EBa4Ce42
Etherscan 链接：https://etherscan.io/token/0x4e352cF164E64ADCBad318C3a1e222E9EBa4Ce42

**Comment by sfsy520** [comment]
已添加，请确认。

**Comment by realmeh** [comment]
非常感谢，还有一个添加图标和token的pull request， 帮忙也合一下，不少用户反馈使用imtoken还不能识别
