### ISSUE TITLE
添加代币收到邮件回复已添加，而实际在imtoken上面搜索不到

### ISSUE THREAD

**Issue by MrLiuYong** [consenlabs/token-profile#601]
我已经在Imtoken上面提交了代币信息，一直未通过。收到邮件回复已添加代币，但是在Imtoken上面却搜索不到，请问是什么原因？代币名称是：ex，合约地址是：0xA5a15631Eb0aa1D178cf2D2C6BEc7732A80eAB03

**Comment by wenyanwang** [comment]
你好，已经显示了EX(Exchange），谢谢。

**Comment by MrLiuYong** [comment]
我想请问是显示在哪里了？为什么我再Imtoken上面搜索不到啊
