### ISSUE TITLE
ERC-20: Add token price display for YFII

### ISSUE THREAD

**Issue by Lavande** [consenlabs/token-profile#6058]
block.cc Link: https://www.mifengcha.com/coin/yfii-finance
Token Symbol: YFII
Token Contract Address: 0xa1d0E215a23d7030842FC67cE582a6aFa3CCaB83
Etherscan Link: https://etherscan.io/token/0xa1d0e215a23d7030842fc67ce582a6afa3ccab83

**Comment by sfsy520** [comment]
已添加，请确认

**Comment by Lavande** [comment]
看到了，感谢
