### ISSUE TITLE
ERC-20: Add token price display for NIRX

### ISSUE THREAD

**Issue by NairaX** [consenlabs/token-profile#6091]
block.cc Link: https://block.cc/coin/nairax
Token Symbol: NIRX
Token Contract Address: 0xf0cCCa32cd300356629216EB301Ec6649c7C6AdB
Etherscan Link: https://etherscan.io/token/0xf0ccca32cd300356629216eb301ec6649c7c6adb

**Comment by sfsy520** [comment]
非常抱歉，没有看到有效交易对。
