### ISSUE TITLE
ERC-20: Add token price display for Libfx

### ISSUE THREAD

**Issue by libermx** [consenlabs/token-profile#6100]
block.cc Link: https://www.mifengcha.com/coin/libfx
Token Symbol: Libfx
Token Contract Address: 0xc0ea83113038987d974FE667831a36E442e661E7
Etherscan Link: https://etherscan.io/token/0xc0ea83113038987d974FE667831a36E442e661E7

**Comment by sfsy520** [comment]
已添加，请确认
