### ISSUE TITLE
Token information was merged, but has not been shown in imToken app

### ISSUE THREAD

**Issue by libermx** [consenlabs/token-profile#6102]
The Libfx's token information was merged at the pull request #6043. However, we can not find it by name or can not see the information submited in the imToken app. What's wrong with it?

**Comment by sfsy520** [comment]
已经Revert，请重新提交一次，注意字体格式
https://github.com/consenlabs/token-profile/pull/6104

**Comment by libermx** [comment]
Once again, the information has been merged, but we can not find it in imToken app.
Related pull request: #6134
