### ISSUE TITLE
ERC-20 ： 添加 ASAM 价格显示

### ISSUE THREAD

**Issue by asam-dev** [consenlabs/token-profile#6111]
block.cc 链接：https://www.mifengcha.com/coin/a-stabilization-agreement
代币简称：ASAM
合约地址：0x7aee312e115493a510144348769681340e2bdfff
Etherscan 链接：https://etherscan.io/token/0x7aee312e115493a510144348769681340e2bdfff

**Comment by sfsy520** [comment]
已添加，请确认。
