### ISSUE TITLE
ERC-20: Add token price display for MTV

### ISSUE THREAD

**Issue by Goya-** [consenlabs/token-profile#6128]
block.cc Link: https://block.cc/coin/multivac
Token Symbol: MTV
Token Contract Address: 0x8aa688ab789d1848d131c65d98ceaa8875d97ef1
Etherscan Link: https://etherscan.io/token/0x8aa688ab789d1848d131c65d98ceaa8875d97ef1

**Comment by sfsy520** [comment]
已添加，请确认

**Comment by Goya-** [comment]
@sfsy520  MTV 1:1 swap was completed, need update.   https://medium.com/@MultiVAC_Global/multivac-issues-1-1-token-swap-in-response-to-kucoin-security-breach-ensuring-no-loss-to-mtv-4f70d9de4b51

new info is:
block.cc Link: https://block.cc/coin/multivac
Token Symbol: MTV
Token Contract Address: 0x6226e00bCAc68b0Fe55583B90A1d727C14fAB77f
Etherscan Link: https://etherscan.io/token/0x6226e00bCAc68b0Fe55583B90A1d727C14fAB77f
