### ISSUE TITLE
ERC-20 ： 添加 YAA 价格显示 

### ISSUE THREAD

**Issue by pumatus** [consenlabs/token-profile#6160]
ERC-20 ： 添加 YAA 价格显示
block.cc 链接：https://www.mifengcha.com/coin/young-animation-artist
代币简称：YAA
合约地址：0xD00b89DF33a794725C369C82E5c20BE783f7B4aE
Etherscan 链接：https://etherscan.io/address/0xD00b89DF33a794725C369C82E5c20BE783f7B4aE

**Comment by pumatus** [comment]
@sfsy520 pls check it~ thks!

**Comment by sfsy520** [comment]
已添加，请确认。
