### ISSUE TITLE
Add Yetoken (YEBR)

### ISSUE THREAD

**Issue by yetoken** [consenlabs/token-profile#6165]
Yetoken Link: http://yetoken.io/
Token Symbol: YEBR
Token Contract Address: 0x0eDB69169fCf878235c0922e0e1b2519e278ae2A
Etherscan: https://etherscan.io/token/0x0eDB69169fCf878235c0922e0e1b2519e278ae2A
Whitepaper:https://www.yetoken.io/wp-tr.pdf
Exchange:https://app.uniswap.org/#/swap?outputCurrency=0x0edb69169fcf878235c0922e0e1b2519e278ae2a

Logo:https://ibb.co/DVnD41Q

**Comment by sfsy520** [comment]
请参考教程提交PR：https://github.com/consenlabs/token-profile#token-profile-guideline
