### ISSUE TITLE
REC20-MSK的合并请求

### ISSUE THREAD

**Issue by fuyundian** [consenlabs/token-profile#6175]
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

**官方公告** 

http://maskdao.finance/

**团队背景**

 MaskDAO 金融生态是由美国金融公司打造的全球数字资产多元化金融生态，利用区块链打造公链生态，同时基于 Ripple 协议即将发布的一个 DeFi&DAO 的去中心化金融借贷自治平台协议，既能有效解决中小企业融资难题，帮助供应链企业提升整体竞争力，又能延伸银行的纵深服务，银行清算、跨国转账、金融交易等，为银行提供切入和稳定高端客户的新渠道，专注于为中小企业融资和金融机构清算提供新的解决方案

**项目基本情况**

MaskDAO是一个完全去中心化社区治理协议，MSK作为生态治理币，打造一个深层次多生态DEX（去中心化交易所）Maskswap(面具交易所)。Mask是面具的意思，寓意匿名者协议，即Defi去中心化金融。DAO是一个完全自治的组织，它不由个体管理，而是通过代码进行管理。代码是基于智能合约运行的，使得DAO能够取代传统机构的典型运作模式.

 更多关于 imToken 的信息

- MaskDAO官方网站：http://maskdao.finance/
- twitter: https://twitter.com/DaoMask
- telegram: https://t.me/MaskDAO
- facebook : https://www.facebook.com/Maskdao-103180304867592

MSK价格

- MSK初始价格：0.5 USD

**转账所需 Gas Limit（默认为 60000）**

**收录的交易所**

**Comment by fuyundian** [comment]
帮忙指点一下谢谢

**Comment by sfsy520** [comment]
请参考教程提交PR：https://github.com/consenlabs/token-profile#token-profile-guideline

**Comment by fuyundian** [comment]
可以清晰的描述一下错误吗？1.是官方公告发布错误吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "consenlabs/token-profile"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 下午3:42
收件人:&nbsp;"consenlabs/token-profile"<token-profile@noreply.github.com&gt;;
抄送:&nbsp;"曼翔的哥哥"<985928112@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [consenlabs/token-profile] REC20-MSK的合并请求 (#6175)





 
请参考教程提交PR：https://github.com/consenlabs/token-profile#token-profile-guideline

**Comment by fuyundian** [comment]
你好，我是ERC20代币申请MSK人员，申请编号为：#6167，申请流程中的资料还缺陷吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "consenlabs/token-profile"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 下午3:42
收件人:&nbsp;"consenlabs/token-profile"<token-profile@noreply.github.com&gt;;
抄送:&nbsp;"曼翔的哥哥"<985928112@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [consenlabs/token-profile] REC20-MSK的合并请求 (#6175)





 
请参考教程提交PR：https://github.com/consenlabs/token-profile#token-profile-guideline
