### ISSUE TITLE
add US Artbank (UAB) logo to imtoken wallet

### ISSUE THREAD

**Issue by jessenng** [consenlabs/token-profile#6188]
Token Name: US Artbank
Token Symbol: UAB
Token Supply: 66,900,000
Token Contract: 0xb19501f5a1c4623fe150134925ae339463b258f3

Company Overview:
US Artbank International Limited (USABI) is an investment holding company at the apex of traditional and digital art industry. USABI has a vision to represent and share the treasures of unique artists that continue to extend the limits and create new boundaries in the art world. We are the exclusive owners and invested in the renowned Gold Art of Kim Il Tae. USABI have established presence in Malaysia, Indonesia, Taiwan, China, Middle East and Russia. USABI is to issued Gold Art backed Initial Coin Offering (ICO) for artist, owners of art and new investors in art objects. Retail investors，museums, galleries, global funds and art-lovers will be the participants and market players in this eco-system.

Gold Art by Kim Il Tae:
Since 2017, we have been exclusively promoting and marketing all of Kim Il Tae works worldwide. Currently amounting 1000 pieces, these gold arts has been publicly auctioned at USD 14,000 per ho, making the total valuation of this artwork alone amount to $364,000,000.

Project Owner:
All started in 2013, Serena Chiam, a skilled businesswoman from Malaysia was introduced to Mr. Kim at his private gallery in Seoul, where Kim was just starting to gain recognition for his pioneering form of gold art. Through her determination and network, she successfully brought back the first series of Kim's paintings into Malaysia.

Email: info@aureo.co

ICO Website: https://uabcoin.com

Company Website: https://aureo.co

Etherscan Contract: https://etherscan.io/token/0xb19501f5a1c4623fe150134925ae339463b258f3

Supported Exchanges: Coming Dec 2020

Articles: https://aureo.co/articles/

Events: https://aureo.co/gold-art-event-and-exhibitions/

Facebook： https://www.facebook.com/AUREOGallery/

Instagram: https://www.instagram.com/aureogallery/

Youtube： https://www.youtube.com/watch?v=hK666f5zti8

Saatchi Gallery: https://www.saatchigallery.com/art/korean_gold_art.php

Media Links:
https://firstclasse.com.my/aureo-gallery-kim-il-tae-gold-art/
https://www.prestigeonline.com/my/pursuits/kim-il-tae-guru-things-gold/
http://thebrandlaureate.net/2018/04/19/gold-art-kim-il-tae/
https://my.asiatatler.com/life/meet-the-south-korean-artist-who-paints-with-24k-gold-and-has-obama-and-madonna-as-clients
https://www.thestar.com.my/news/nation/2017/12/02/art-with-a-golden-touch-s-korean-artists-24carat-gold-paintings-set-to-go-on-display-here
https://thegridasia.com/videos/the-world-s-only-gold-painting-artist-kim-il-tae

![0xb19501f5a1c4623fe150134925ae339463b258f3](https://user-images.githubusercontent.com/71230245/93503993-797ce580-f936-11ea-8d80-07c167764b38.png)

**Comment by jessenng** [comment]
Searching Uab and Us artbank .please update sir

**Comment by sfsy520** [comment]
This is guideline about update token info：
https://github.com/consenlabs/token-profile#token-profile-guideline
