### ISSUE TITLE
ERC-20: Add token price and amount display for ELF

### ISSUE THREAD

**Issue by moadrahal** [consenlabs/token-profile#6215]
block.cc Link: https://www.mifengcha.com/coin/aelf
Token Symbol: ELF
Token Contract Address: 0xbf2179859fc6d5bee9bf9158632dc51678a4100e
Etherscan Link: https://etherscan.io/token/0xbf2179859fc6D5BEE9Bf9158632Dc51678a4100e

**Comment by sfsy520** [comment]
该代币已添加价格行情，请确认。

**Comment by moadrahal** [comment]
Hi there,
Nothing showing, the total balance of RSR is not real, as shown in the attached screenshot.



ELF also not showing, the transaction is there but not showing in the balance.





    On Tuesday, 22 September 2020, 10:50:50 GMT+4, sfsy520 <notifications@github.com> wrote:  
 
 


该代币已添加价格行情，请确认。
