### ISSUE TITLE
ERC-20: Add token price display for RSR

### ISSUE THREAD

**Issue by moadrahal** [consenlabs/token-profile#6217]
block.cc Link: https://www.mifengcha.com/coin/reserve-protocol
Token Symbol: RSR
Token Contract Address: 0x8762db106b2c2a0bccb3a80d1ed41273552616e8
Etherscan Link: https://etherscan.io/token/0x8762db106b2c2a0bccb3a80d1ed41273552616e8

**Comment by sfsy520** [comment]
该代币已经添加价格行情，请确认。
