### ISSUE TITLE
小数位显示问题.

### ISSUE THREAD

**Issue by zizhilong** [consenlabs/token-profile#622]
按照ERC20标准发行了代币.存在decimals属性.设置为8.但是在IMTOKEN中现实转账金额.并未应用到此属性.结果金额基础上乘了100000000.
(发行代币的时候.decimals属性是在代码中固定.并未用构造函数)

**Comment by wenyanwang** [comment]
你好，请提供合约地址，谢谢。

**Comment by zizhilong** [comment]
0x04300d191c66A617A26ED97370f919e4D258995C
