### ISSUE TITLE
ERC-20 ： 添加 SFG 价格显示

### ISSUE THREAD

**Issue by s-finance** [consenlabs/token-profile#6271]
block.cc 链接：https://block.cc/coin/s-finance
代币简称：SFG
合约地址：0x8a6ACA71A218301c7081d4e96D64292D3B275ce0
Etherscan 链接：https://etherscan.io/token/0x8a6ACA71A218301c7081d4e96D64292D3B275ce0

**Comment by sfsy520** [comment]
已添加，请确认
