### ISSUE TITLE
All details  are correct sir please approve ieo coming through exchanges we givinen iam token for the wallet for can holding https://p2pb2b.io/token-sale/CAN/1 all details are correct and trust please help

### ISSUE THREAD

**Issue by coinwaycan** [consenlabs/token-profile#6274]
All details  are correct sir please approve ieo coming through exchanges we givinen iam token for the wallet for can holding https://p2pb2b.io/token-sale/CAN/1 all details are correct and trust please help
    "symbol": "CAN",
    "address":"0x46EE7D0E5080B0FE3D16701c0dbBC6916E3C77C5 ",
    "overview": {
        "en": "Coinwaycoin(CAN) is an ERC20 Crypto for the marketing industrial purpose with well known ideas & business development management teams IEO coming on p2pb2b exchange .",
        "zh": "Coinwaycoin（CAN）是一种ERC20加密货币，用于工业营销目的，拥有知名的想法和业务开发管理团队，IEO即将在p2pb2b交易平台上进行交易"
    },
      "email": "founder@coinwaycan.com",
       "website":"https://www.coinwaycan.com ",
      "website2":"https://www.coinwaygroups.com",
      "whitepaper":"https://coinwaycan.com/wp-content/uploads/2020/09/coinwaycan.pdf",
      "state": "Normal",
      "published_on": "2020-09-11",
      "initial_price": {
         "USD": "0.03"
         "ETH""0001"
        },
         "links": 
         {

      "Telegram": 

"https://t.me/CANOFFICIALGROUP", 
  
"P2pb2b":

"https://p2pb2b.io/token-sale/CAN/1",
 
"twitter": "https://twitter.com/COINWAYCAN",         
        
"github": 
"https://github.com/coinwaycan",

"bitcointalk":

"https://bitcointalk.org/index.php?topic=5278712",

"Instagram": 

"https://instagram.com/coinwaycan ",

_Originally posted by @coinwaycan in https://github.com/consenlabs/token-profile/pull/6236#issuecomment-700607854_

**Comment by coinwaycan** [comment]
![0x46EE7D0E5080B0FE3D16701c0dbBC6916E3C77C5](https://user-images.githubusercontent.com/71204887/94581117-51777580-0298-11eb-8ff7-4a7d9df96ae4.png)

**Comment by coinwaycan** [comment]
https://github.com/consenlabs/token-profile/pull/6276

**Comment by sfsy520** [comment]
PR相关会跟进时间进度审核
