### ISSUE TITLE
ERC-20 ： 添加 WSCOIN 价格显示

### ISSUE THREAD

**Issue by dacelee** [consenlabs/token-profile#6325]
block.cc 链接：https://block.cc/coin/wscoin
代币简称：WSCOIN
合约地址：0x988dadd0b82fa7d94d9e6f084a08755bfd4da860
Etherscan 链接：https://cn.etherscan.com/token/0x988dadd0b82fa7d94d9e6f084a08755bfd4da860

**Comment by sfsy520** [comment]
非常抱歉，该代币无交易对，无法添加行情。
