### ISSUE TITLE
ERC-20: 添加 BEL 价格显示

### ISSUE THREAD

**Issue by neptune-v** [consenlabs/token-profile#6328]
**ERC-20**: 添加 BEL 价格显示
**block.cc 链接**：https://www.mifengcha.com/coin/bella-protocol
**代币简称**：bel
**合约地址**：0xA91ac63D040dEB1b7A5E4d4134aD23eb0ba07e14
**Etherscan 链接**：https://etherscan.io/token/0xA91ac63D040dEB1b7A5E4d4134aD23eb0ba07e14

**Comment by sfsy520** [comment]
已添加，请确认。
