### ISSUE TITLE
ERC-20 ： 添加 LCS 价格显示

### ISSUE THREAD

**Issue by sz1001** [consenlabs/token-profile#6329]
block.cc 链接：https://www.mifengcha.com/coin/liberty-cash
代币简称：LCS
合约地址：0x6102407f07029892eb5ff02164adfafb85f4d222
Etherscan 链接：https://cn.etherscan.com/token/0x6102407f07029892eb5ff02164adfafb85f4d222

**Comment by sfsy520** [comment]
已添加，请确认。
