### ISSUE TITLE
ERC-20 代币显示问题

### ISSUE THREAD

**Issue by laocaidegit** [consenlabs/token-profile#6335]
DOGZ代币logo搜索显示问题，0xCe5fb6503558357deA6DdC5B840007888F9dBac9为旧合约地址更换为新合约地址0x82A77710495A35549D2aDD797412b4a4497D33eF之后，logo去色png也已经提交。目前搜索还是只显示旧合约logo的彩色版，新合约地址的logo无显示

**Comment by sfsy520** [comment]
已修复
