### ISSUE TITLE
ERC-20 ： 添加 DOGZ 价格显示

### ISSUE THREAD

**Issue by dogzcoin** [consenlabs/token-profile#6343]
block.cc 链接：https://block.cc/coin/dogz
代币简称：DOGZ
合约地址：0x82A77710495A35549D2aDD797412b4a4497D33eF
Etherscan 链接：https://cn.etherscan.com/token/0x82A77710495A35549D2aDD797412b4a4497D33eF

**Comment by sfsy520** [comment]
该代币暂无交易对，无法添加。
