### ISSUE TITLE
 ERC-20 ： 添加 Chips 价格显示

### ISSUE THREAD

**Issue by Chips-swap** [consenlabs/token-profile#6353]
block.cc 链接：https://www.mifengcha.com/coin/chipswap
代币简称：Chips
合约地址：0xc4574701ed4676Cc556E811fD2F142cb2Ca57Fea
Etherscan 链接：https://etherscan.io/token/0xc4574701ed4676Cc556E811fD2F142cb2Ca57Fea

**Comment by sfsy520** [comment]
非常抱歉，该代币暂无交易对行情
