### ISSUE TITLE
Logo & details  wont showing 

### ISSUE THREAD

**Issue by coinwaycan** [consenlabs/token-profile#6366]
https://github.com/consenlabs/token-profile/pull/6321/commits/134eaae6aa9cd73b16da7f2a9063207a2bbf6034

Please check

https://etherscan.io/token/0x917FD2f7378FF479419dCB56C5cbB445fBbF902A

**Comment by sfsy520** [comment]
该PR已Reverted，请检查json字体是否包含特殊字符后，再次提交，谢谢。
