### ISSUE TITLE
ERC-20: Add token price display for CVP

### ISSUE THREAD

**Issue by vanphandinh** [consenlabs/token-profile#6367]
- block.cc Link: https://www.mifengcha.com/coin/concentrated-voting-power
- Token Symbol: CVP
- Token Contract Address: 0x38e4adB44ef08F22F5B5b76A8f0c2d0dCbE7DcA1
- Etherscan Link: https://etherscan.io/token/0x38e4adB44ef08F22F5B5b76A8f0c2d0dCbE7DcA1

**Comment by sfsy520** [comment]
已添加，请确认。
