### ISSUE TITLE
ERC-20: Update token info display for MTV

### ISSUE THREAD

**Issue by Goya-** [consenlabs/token-profile#6377]
MTV 1:1 swap was completed, need update.   https://medium.com/@MultiVAC_Global/multivac-issues-1-1-token-swap-in-response-to-kucoin-security-breach-ensuring-no-loss-to-mtv-4f70d9de4b51

new info is:
block.cc Link: https://block.cc/coin/multivac
Token Symbol: MTV
Token Contract Address: 0x6226e00bCAc68b0Fe55583B90A1d727C14fAB77f
Etherscan Link: https://etherscan.io/token/0x6226e00bCAc68b0Fe55583B90A1d727C14fAB77f

_Originally posted by @Goya- in https://github.com/consenlabs/token-profile/issues/6128#issuecomment-712268458_

**Comment by sfsy520** [comment]
非常抱歉，该代币暂无交易对，无法添加。
