### ISSUE TITLE
ERC-20: Add token price display for MAP

### ISSUE THREAD

**Issue by Philasande-map** [consenlabs/token-profile#6384]
block.cc Link: https://block.cc/coin/marcopolo
Token Symbol: MAP
Token Contract Address: 0x9E976F211daea0D652912AB99b0Dc21a7fD728e4
Etherscan Link: https://etherscan.io/token/0x9E976F211daea0D652912AB99b0Dc21a7fD728e4

**Comment by sfsy520** [comment]
非常抱歉，该代币暂无交易行情，无法添加。
