### ISSUE TITLE
收到邮件回复已添加代币，而实际在Imtoken却无法搜索到！

### ISSUE THREAD

**Issue by MrLiuYong** [consenlabs/token-profile#641]
我已经在Imtoken上面提交了代币信息，一直未通过。收到邮件回复已添加代币，但是在Imtoken上面却搜索不到，请问是什么原因？代币名称是：ex，合约地址是：0xA5a15631Eb0aa1D178cf2D2C6BEc7732A80eAB03

**Comment by makoshan** [comment]
请搜索添加 

EX(Exchange）
--
