### ISSUE TITLE
PR #6405

### ISSUE THREAD

**Issue by ttetokt** [consenlabs/token-profile#6410]
Could you please merge our PR #6405 before October 30th? 
https://github.com/consenlabs/token-profile/pull/6405

Previously we have already sent our PR #6305 and you merged it October 19th.
https://github.com/consenlabs/token-profile/pull/6305

But our PR was reverted with below message on October 28th. so we sent new PR #6405 again.
`Json格式不正确导致merge后未显示，请重新提交。`

We believed that there is no problem in our PR as you mentioned in the  below link and you merged our PR.
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md
```
How it works
9. We will review your PR as soon as possible. If there is no problem with your PR, we will merge it into our master branch. And then your token profile will display in the current imToken App

```

**Comment by sfsy520** [comment]
已合并，请查看。
