### ISSUE TITLE
19天前就已经 merged 了，还是搜索不到 ARP

### ISSUE THREAD

**Issue by wellsqiu** [consenlabs/token-profile#642]
19天前就已经 merged 了，还是搜索不到 ARP。
PR地址：[https://github.com/consenlabs/token-profile/pull/206](https://github.com/consenlabs/token-profile/pull/206)
合约地址：0xbeb6fdf4ef6ceb975157be43cbe0047b248a8922

**Comment by makoshan** [comment]
请搜索添加 ARP

**Comment by wellsqiu** [comment]
还是搜索不到 ARP
