### ISSUE TITLE
ERC-20 ： 添加BOR价格显示

### ISSUE THREAD

**Issue by Enki-y** [consenlabs/token-profile#6445]
ERC-20 ： 添加BOR价格显示
block.cc 链接：https://block.cc/coin/boringdao
代币简称：BOR
合约地址：0x3c9d6c1c73b31c837832c72e04d3152f051fc1a9
Etherscan 链接：https://etherscan.io/token/0x3c9d6c1c73b31c837832c72e04d3152f051fc1a9

**Comment by sfsy520** [comment]
非常抱歉，该代币暂无交易对，无法添加。
