### ISSUE TITLE
Imtoken v1怎么去掉名字后面的数字啊

### ISSUE THREAD

**Issue by cserror** [consenlabs/token-profile#646]
麻烦问下Imtoken v1版本怎么去掉代币名字后面的数字啊

**Comment by wenyanwang** [comment]
代币名称重复，在代币名称后有数字编号来区分
imToken 目前已经支持由项目方自主提交或修改 Token 信息，无论是初次提交项目资料，还是修改代币简称、LOGO 等信息，你都可以通过 Github 自主提交。



注：系统会自动抓取 Etherscan 记录，如果代币名称重复，会在代币名称后添加数字编号来区分。



imToken Github : 

https://github.com/consenlabs/token-profile 



具体教程请参考:

https://github.com/consenlabs/token-profile/blob/master/README.md 



中文教程：https://shimo.im/docs/nKTCMRUhfyAEu2Su 



如有疑问，勿回复此邮件，请在 github PR 下留言与我们联系。
