### ISSUE TITLE
When will the camp token-profile update be available on the imtoken?

### ISSUE THREAD

**Issue by JoshepJang** [consenlabs/token-profile#6504]
#imToken #6482 We are providing Camp token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.

https://github.com/JoshepJang/token-profile

It's been five days. When can I register? Is there anything you need?

**Comment by sfsy520** [comment]
已merge

**Comment by JoshepJang** [comment]
> 已merge

When will the token image be registered?
0xE9E73E1aE76D17A16cC53E3e87a9a7dA78834d37.png
