### ISSUE TITLE
ERC-20: Add token price display for ARNX

### ISSUE THREAD

**Issue by aeronaero** [consenlabs/token-profile#6517]
block.cc Link: https://www.mifengcha.com/coin/aeron
Token Symbol: ARNX
Token Contract Address: 0x0C37Bcf456bC661C14D596683325623076D7e283
Etherscan Link: https://etherscan.io/token/0x0C37Bcf456bC661C14D596683325623076D7e283

**Comment by sfsy520** [comment]
已添加，请确认。
