### ISSUE TITLE
添加 DOGZ 价格显示

### ISSUE THREAD

**Issue by dogzcoin** [consenlabs/token-profile#6569]
block.cc 价格 API链接：https://data.block.cc/api/v3/price?slug=dogz&api_key=2ZJAP2GMK021PMSGWTNU68GFLPRBBVJFKA2CLEXI
block.cc API交易对 API链接：https://data.block.cc/api/v3/tickers?market=digifinex&slug=dogz&api_key=2ZJAP2GMK021PMSGWTNU68GFLPRBBVJFKA2CLEXI
代币简称：DOGZ
合约地址：0x82A77710495A35549D2aDD797412b4a4497D33eF
Etherscan 链接：https://cn.etherscan.com/token/0x82A77710495A35549D2aDD797412b4a4497D33eF

**Comment by dogzcoin** [comment]
补充项目API：https://data.block.cc/api/v3/symbols/dogz?api_key=2ZJAP2GMK021PMSGWTNU68GFLPRBBVJFKA2CLEXI

**Comment by sfsy520** [comment]
非常抱歉，该代币暂无价格行情。
