### ISSUE TITLE
Add token price display for INJ

### ISSUE THREAD

**Issue by Synthacon** [consenlabs/token-profile#6574]
block.cc Link: https://www.mifengcha.com/coin/injective-protocol
Token Symbol: INJ
Token Contract Address: 0xe28b3b32b6c345a34ff64674606124dd5aceca30
Etherscan Link: https://etherscan.io/token/0xe28b3b32b6c345a34ff64674606124dd5aceca30

**Comment by sfsy520** [comment]
已添加，请确认。
