### ISSUE TITLE
Imtoken 

### ISSUE THREAD

**Issue by brugtje** [consenlabs/token-profile#6629]
Hi, I'm trying to transfer my LYM coin to KUCOIN, but this doesn't work. I get the message that the amount is insufficient. The coin is marked as "KICK-_UNKNOWN" and the amount is 1. How can I transfer this ? I need to get rid of the "unknown", I suppose. Thanks in advance. Kind regards

**Comment by sfsy520** [comment]
pls contact：https://support.token.im

**Comment by brugtje** [comment]
Hi,

They told me to contact you.
Pls help.

Thanks

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: sfsy520<mailto:notifications@github.com>
Verzonden: maandag 4 januari 2021 2:59
Aan: consenlabs/token-profile<mailto:token-profile@noreply.github.com>
CC: brugtje<mailto:brecht_vyncke@hotmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [consenlabs/token-profile] Imtoken (#6629)


pls contact：https://support.token.im
