### ISSUE TITLE
Imtoken issue

### ISSUE THREAD

**Issue by brugtje** [consenlabs/token-profile#6639]
Dear,
IMTOKEN sent me to you. They can not solve the problem.
I'm trying to transfer my LYM coin from IMTOKEN to KUCOIN, but this doesn't work. I get the message that the amount is insufficient. The coin is marked as "KICK-_UNKNOWN" and the amount is 1. How can I transfer this ? How do I get rid of the unknown ? Thanks in advance. Kind regards, Brecht

**Comment by sfsy520** [comment]
you can contact https://support.token.im for help.
