### ISSUE TITLE
The DOTC token logo is not displayed on the imtoken homepage, and the token information of DOTC cannot be found in the imtoken app.

### ISSUE THREAD

**Issue by dotc-pro** [consenlabs/token-profile#6671]
The DOTC token logo is not displayed on the imtoken homepage, and the token information of DOTC cannot be found in the imtoken app.

**Comment by sfsy520** [comment]
由于之前的json格式不正确，导致merge后没有成功现实，现已revert旧的PR，需要你们修改格式后，重新提交。
