### ISSUE TITLE
about Add PROT token #6663

### ISSUE THREAD

**Issue by brand1313** [consenlabs/token-profile#6693]
Hi, sfsy520 : )

Very thank you for your kindness.
We confirmed registration of our PROT info in imtoken App.

However, we found out a problem.
We can search our token by input contract address, but token name and symbol is impossible. Also, token image is not visible..
Could you please check it once?

have a nice day! :-)

Token address is 0x734bDFC240F03dF761FF012fA78Eb2e2e07515E9

have a nice day!

**Comment by sfsy520** [comment]
Hi brand1313, please check you json format and resubmit new PR.
