### ISSUE TITLE
BSS新旧合约显示需求

### ISSUE THREAD

**Issue by bitstd** [consenlabs/token-profile#670]
你好，我在imToken钱包1.4.5版本中看到BSS新旧合约同步已经完成，但是我方还有以下需求：
1、BSS-Old为旧合约币，我方已经停止使用，请贵方下架。旧合约地址0xeeeec8542dec1993c76873524aca8ea9af9e2447
2、imToken钱包2.0还没有同步。

**Comment by wenyanwang** [comment]
2.0需要提交github
imToken 目前已经支持由项目方自主提交或修改 Token 信息，无论是初次提交项目资料，还是修改代币简称、LOGO 等信息，你都可以通过 Github 自主提交。



注：系统会自动抓取 Etherscan 记录，如果代币名称重复，会在代币名称后添加数字编号来区分。



imToken Github : 

https://github.com/consenlabs/token-profile 



具体教程请参考:

https://github.com/consenlabs/token-profile/blob/master/README.md 



中文教程：https://shimo.im/docs/nKTCMRUhfyAEu2Su 



如有疑问，勿回复此邮件，请在 github PR 下留言与我们联系。
