### ISSUE TITLE
添加BOR价格显示

### ISSUE THREAD

**Issue by Enki-y** [consenlabs/token-profile#6708]
block.cc 链接：https://block.cc/coin/boringdao
代币简称：BOR
合约地址：0x3c9d6c1c73b31c837832c72e04d3152f051fc1a9
Etherscan 链接：https://etherscan.io/token/0x3c9d6c1c73b31c837832c72e04d3152f051fc1a9

**Comment by sfsy520** [comment]
已添加，请确认。

**Comment by Enki-y** [comment]
确认，多谢！辛苦了。


sfsy520 <notifications@github.com>于2021年2月2日 周二11:08写道：
