### ISSUE TITLE
ERC20: add token price display for SRK

### ISSUE THREAD

**Issue by Rickymcfire** [consenlabs/token-profile#6741]
block.cc Link: https://block.cc/coin/sparkpoint
Token Symbol: SRK
Token Contract Address: 0x0488401c3f535193fa8df029d9ffe615a06e74e6
Etherscan Link: https://etherscan.io/token/0x0488401c3f535193fa8df029d9ffe615a06e74e6

**Comment by sfsy520** [comment]
已更新，请确认。
