### ISSUE TITLE
ADD PROTOCOL FINANCE INFO AND LOGO

### ISSUE THREAD

**Issue by protocolfinance** [consenlabs/token-profile#6758]
Protocol Finance can also be defined as a decentralized venture capital that empowers a decentralized interest-free financial ecosystem by building Defi products invested in by its community to distribute revenue as profit stakeholders.

Protocol Finance is powering open finance through our ecosystem of cross-chain protocols, exchanges, and applications that are the legos to build the next-generation of Defi

✅ Total supply: 11,700 PFI tokens 
✅ Circulating  : 9000 PFI tokens
✅ Token contract: 
https://etherscan.io/token/0x7b69d465c0f9fb22affae56aa86149973e9b0966

⭐️ CoinMarketCap: https://coinmarketcap.com/currencies/protocol-finance/

⭐️ CoinGecko: https://www.coingecko.com/en/coins/protocol-finance

⭐️ CoinCodex: https://coincodex.com/crypto/protocol-finance/

⭐️ LiveCoinWatch: https://www.livecoinwatch.com/price/ProtocolFinance-_PFI

⭐️ CoinPaprika: https://coinpaprika.com/coin/pfi-protocol-finance/

PROTOCOL FINANCE IS LISTED AT
Uniswap 
https://app.uniswap.org/#/swap?inputCurrency=0x7b69d465c0f9fb22affae56aa86149973e9b0966

Cointiger Exchange
https://www.cointiger.com/en-us/#/trade_center?coin=pfi_eth

Digifinex Exchange
https://www.digifinex.com/en-ww/trade/ETH/PFI

Dextool
https://www.dextools.io/app/uniswap/pair-explorer/0x8582de88bb2fc8bcd5dd3b38f44d8440e51685ed

Astrotools
https://app.astrotools.io/pair-explorer/0x8582de88bb2fc8bcd5dd3b38f44d8440e51685ed

Liquidity locked for one year
https://v2.unicrypt.network/pair/0x8582de88bb2fc8bcd5dd3b38f44d8440e51685ed

🔵 WEBSITE: https://protocolfinance.com

🔵 WALLET: https://wallet.protocolfinance.com

⚫️WHITEPAPER: https://protocolfinance.com/ProtocolFinanceWhitepaper.pdf

⚫️ AUDIT REPORT: https://solidity.finance/audits/ProtocolFinance

⚫️ TOKEN ADDRESS: 
0x7b69d465c0f9fb22affae56aa86149973e9b0966

Follow us on
Telegram 🌎: https://t.me/protocolfinancechat
Telegram chinese : http://t.me/protocolfinancechina
Telegram channel : https://t.me/protocolfinance
Twitter: https://twitter.com/protocolfinance
GitHub: https://github.com/protocolfinance
Medium: https://protocolfinance.medium.com/

**Comment by sfsy520** [comment]
请提交PR。
