### ISSUE TITLE
PalletOne token请求merge

### ISSUE THREAD

**Issue by ccbupt** [consenlabs/token-profile#676]
PR链接： #586

**Comment by ccbupt** [comment]
@wenyanwang

**Comment by ccbupt** [comment]
您好，图片已经修改为透明背景，还麻烦帮忙merge，时间紧急，多谢多谢
PR #755  @wenyanwang

**Comment by wenyanwang** [comment]
你好，代币名称重复，已经修改为PTN(PalletOne)，请向用户说明需要重新搜索添加打开代币开关按钮才会显示。
