### ISSUE TITLE
ERC-20: Add token price display for CWT

### ISSUE THREAD

**Issue by victor55511** [consenlabs/token-profile#6783]
block.cc Link: https://block.cc/coin/clone-winner-token
Token Symbol: CWT
Token Contract Address: 0x374155FC5bEF18827e209002906c1BF5FaC6bF0F
Etherscan Link: https://etherscan.io/token/0x374155FC5bEF18827e209002906c1BF5FaC6bF0F

**Comment by sfsy520** [comment]
已添加，请确认。
