### ISSUE TITLE
ERC20: Wrong info (description and twitter link) displayed.

### ISSUE THREAD

**Issue by nnnggel** [consenlabs/token-profile#6818]
CNHC token is approved, but it displays wrong info in imtoken app.
Please update the link by follow PR: https://github.com/consenlabs/token-profile/pull/6798

**Comment by sfsy520** [comment]
what's wrong？

**Comment by nnnggel** [comment]
According to the PR: https://github.com/consenlabs/token-profile/pull/6798

-----------------------
## "Project basic information" should be:
CNHC is a crypto currency that is CNH-pegged. Each CNHC is backed by 1 offshore RMB (CNH), in compliance with regulated U.S. trust and banks for fund custody. Audit reports will be published by an independent audit firm on a regular basis. CNHC is supported by top international investment institutions and Internet giants, and will be promoted globally, including but not limited to application scenarios such as international payment, global trade, and decentralized finance.

## "Twitter link" should be:
Twitter: https://twitter.com/CNHC_TO
-----------------------

But in imtoken app, it's now:
![image](https://user-images.githubusercontent.com/17697169/111243938-da168200-863c-11eb-9d90-5e5d05252cba.png)
![image](https://user-images.githubusercontent.com/17697169/111243946-dedb3600-863c-11eb-8076-b233a4f0676f.png)

**Comment by sfsy520** [comment]
you can resubmit a new pr to change it.
