### ISSUE TITLE
添加 PIGX 价格显示

### ISSUE THREAD

**Issue by pigx666** [consenlabs/token-profile#6819]
block.cc 链接：https://block.cc/coin/pigx
代币简称：PIGX
合约地址：0x47e820df943170b0e31f9e18ecd5bdd67b77ff1f
Etherscan 链接：https://cn.etherscan.com/token/0x47e820df943170b0e31f9e18ecd5bdd67b77ff1f

**Comment by sfsy520** [comment]
已添加，请确认

**Comment by pigx666** [comment]
你好 在我帮确认下 目前还没有显示
