### ISSUE TITLE
添加 PIGX 价格显示

### ISSUE THREAD

**Issue by pigx666** [consenlabs/token-profile#6822]
block.cc 链接：https://block.cc/coin/pigx
代币简称：Pigx
合约地址：0x47e820df943170b0e31f9e18ecd5bdd67b77ff1f
Etherscan 链接：https://cn.etherscan.com/token/0x47e820df943170b0e31f9e18ecd5bdd67b77ff1f
#6819 提交已确认 没有显示

**Comment by sfsy520** [comment]
确认已经添加上，看一下是不是缓存原因
