### ISSUE TITLE
ERC-20: Add token price display for BT

### ISSUE THREAD

**Issue by btdotfinance** [consenlabs/token-profile#6860]
block.cc link: https://www.mifengcha.com/coin/bt-finance
Token symbol : https://bt.finance/static/media/BT-logo.324f553c.png
contract address :  0x76c5449F4950f6338A393F53CdA8b53B0cd3Ca3a
etherscan link : https://etherscan.io/address/0xAD2598c2aDC9d966b5349BaBD30FB28C437Fb363

**Comment by sfsy520** [comment]
已添加，请确认。
