### ISSUE TITLE
ERC-20 ： 添加 EBC价格显示

### ISSUE THREAD

**Issue by dapp021** [consenlabs/token-profile#6898]
ERC-20 ： 添加 EBC价格显示
block.cc 链接：https://block.cc/coin/ebaycoin
代币简称：EBC
合约地址：0xd87cc98de50cd7391a8fa1a415def9ff65ff9718
Etherscan 链接：https://cn.etherscan.com/token/0xd87cc98de50cd7391a8fa1a415def9ff65ff9718

**Comment by sfsy520** [comment]
已添加，请确认。
