### ISSUE TITLE
提交代币信息

### ISSUE THREAD

**Issue by yiyi1025-SRIT** [consenlabs/token-profile#7060]
SRIT(Star Rrver)属于匿名币项目，由一批隐私币爱好者创建，基于MW协议，使用的是X17算法。目前处于最早期，POW友好型矿币，SRIT是一项无边界的项目，旨在保护我们的隐私。同时，SRIT是一个匿名的区块链协议，由世界各地开发人员透明地构建。
logo:image

**Comment by Leo2021zzz** [comment]
你好，提交代币信息的流程：https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md
