### ISSUE TITLE
添加价格显示

### ISSUE THREAD

**Issue by yiyi1025-SRIT** [consenlabs/token-profile#7061]
ERC-20 ： 添加 SRIT 价格显示
block.cc 链接：http://www.bitc.cn.com
代币简称：SRIT
合约地址：0xBec66B0ab8e6a321C39560F6F4B509a5b50be681
Etherscan 链接：https://etherscan.io/token/0xBec66B0ab8e6a321C39560F6F4B509a5b50be681

**Comment by Leo2021zzz** [comment]
你好，请先提交 TokenProfile PR 信息，在提交价格显示的 issues。
