### ISSUE TITLE
关于添加新token

### ISSUE THREAD

**Issue by BugBang** [consenlabs/token-profile#713]
我有一些疑惑, 希望帮忙解答一下
1.  $template.json 模板里的所有参数都必须填写吗? 如果不是所有参数都要填写 那么哪些参数是必须填写的?
2. 我想给我的token 添加一个默认gas limit 的参数(你们默认是的60000,我想改成80000),$template.json 模板里面没有相关的参数 , 需要怎么添加?
3. 我们的token 锁定了一部分  释放了一部分, 那么 "state": "LOCKED | NORMAL"  这个字段应该填写LOCKED 还是 NORMAL?

**Comment by makoshan** [comment]
1. 尽量补完整的信息，没有的信息可以不填写
2. 可以在 PR 评论下给我吗留言 gas limit
3. 用户可以转账为 NORMAL，不可以转账，锁币为 LOCKED
