### ISSUE TITLE
智能合约升级 需要给已经拥有的用户重新发币 如何进行更换

### ISSUE THREAD

**Issue by tokenbookdapp** [consenlabs/token-profile#716]
你好，我是TokenBook项目方
智能合约地址为：0x69dfcf370c5ba8959acebd0bfa229a0608961a6d
由于升级智能合约，需要重新发币，新币名字与老币名字保持不变，请问需要如何操作来进行更换。

**Comment by qingqicheng** [comment]
重新发啊。做好快照，然后空投给就合约的持有者就行了。还有不懂的给我发邮件qi.cheng.qing.mr@gmail.com

**Comment by qingqicheng** [comment]
是修改imtoken上面的信息？

**Comment by wenyanwang** [comment]
你好，

需要提供资料给我们，修改后会造成用户代币不显示，请见谅，我们将不会修改旧合约名字，新的合约名称重复会用数字区别，会显示logo。
