### ISSUE TITLE
TRC-20 ： 添加 PLC 价格显示

### ISSUE THREAD

**Issue by jctinius** [consenlabs/token-profile#7172]
TRC-20 ： 添加 PLC 价格显示
JUSTSWAP 链接：已经上线JUSTSWAP去中心化交易所，请收录价格，谢谢
代币简称：PLC
合约地址：TRmmhEYAB2dsGcm9kcnom9UmM22AfCRQE3
波场 链接：https://tronscan.io/#/token20/TRmmhEYAB2dsGcm9kcnom9UmM22AfCRQE3

**Comment by mqhammer94** [comment]
TNEzcj7Gkeso5W62TMNpCveu9q7ATBPSu7

**Comment by Leo2021zzz** [comment]
价格来源为 CoinGecko/CoimMarketCap/Block.cc
