### ISSUE TITLE
TRC-20 ： 添加 YZZ 价格显示

### ISSUE THREAD

**Issue by jctinius** [consenlabs/token-profile#7173]
JUSTSWAP 链接：已经上线JUSTSWAP去中心化交易所，请收录价格，谢谢
代币简称：YZZ
合约地址：TWZAM7HVnyedDuVNP9TKgSCHZ2Gt8XsGGE
波场 链接：https://tronscan.io/#/token20/TWZAM7HVnyedDuVNP9TKgSCHZ2Gt8XsGGE

**Comment by Leo2021zzz** [comment]
价格来源为 CoinGecko/CoimMarketCap/Block.cc
