### ISSUE TITLE
Add PFY token price 0x69083b64988933e8b4783e8302b9bbf90163280e

### ISSUE THREAD

**Issue by ShaniaLee** [consenlabs/token-profile#7267]
Portify token 
Binance smart chain 
0x69083b64988933e8b4783e8302b9bbf90163280e

**Comment by skinshuaan1** [comment]
The BSC chain token currently only supports debank data

**Comment by Arcomyala** [comment]
> โอนโทเค็น Binance สมาร์ทเชน 0x69083b64988933e8b4783e8302b9bbf90163280e
