### ISSUE TITLE
> โอนโทเค็น Binance สมาร์ทเชน 0x69083b64988933e8b4783e8302b9bbf90163280e

### ISSUE THREAD

**Issue by Arcomyala** [consenlabs/token-profile#7269]
> โอนโทเค็น Binance สมาร์ทเชน 0x69083b64988933e8b4783e8302b9bbf90163280e

_Originally posted by @Arcomyala in https://github.com/consenlabs/token-profile/issues/7267#issuecomment-975484741_

**Comment by skinshuaan1** [comment]
We do not support BSC token configuration
