### ISSUE TITLE
请问支持BSC链的token信息提交吗

### ISSUE THREAD

**Issue by bishangshuo** [consenlabs/token-profile#7335]
智能合约在币安智能链上部署，我在imtoken钱包app将节点设置为Binance Samrt Chain, 然后可以通过添加智能合约地址的方式管理我的bsc 代币。
我的意思是， imtoken支持BSC链的token信息的搜索、logo图标的显示吗？如果可以，怎么提交信息给imtoken团队。
谢谢！

**Comment by kaiko1203** [comment]
Please follow our template to submit token information

**Comment by kaiko1203** [comment]
支持的，https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md 有详细的提交介绍
