### ISSUE TITLE
token contract已经可以被imtoken钱包搜索到， 但是logo显示不正确

### ISSUE THREAD

**Issue by ArtChainGlobal** [consenlabs/token-profile#735]
如题，

contract 地址： 0x984c134a8809571993fd1573fb99f06dc61e216f

0x984c134a8809571993fd1573fb99f06dc61e216f.png 正确保存于 images 文件夹内

commit 32811dfdeed1dfe03b569bbaecebeecdbdcfb56a 

pull request: https://github.com/consenlabs/token-profile/pull/230

**Comment by wenyanwang** [comment]
imToken 目前已经支持由项目方自主提交或修改 Token 信息，无论是初次提交项目资料，还是修改代币简称、LOGO 等信息，你都可以通过 Github 自主提交。



注：系统会自动抓取 Etherscan 记录，如果代币名称重复，会在代币名称后添加数字编号来区分。



imToken Github : 

https://github.com/consenlabs/token-profile 



具体教程请参考:

https://github.com/consenlabs/token-profile/blob/master/README.md 



中文教程：https://shimo.im/docs/nKTCMRUhfyAEu2Su
