### ISSUE TITLE
imtoken不支持ropsten网络的uniswap V2添加流动性

### ISSUE THREAD

**Issue by CryptoCoinLab** [consenlabs/token-profile#7368]
imtoken不支持ropsten网络的uniswap V2添加流动性交易签名，
最新版本2.10.2.1693 cp67，选择ropsten网络，用walletconnect扫描网页连接ropsten网络的uniswap V2，添加流动性时，无法弹出添加流动性交易。

**Comment by izayl** [comment]
应该是 ropsten rpc 的问题，建议更换 rpc 先在网页端用 metamask 测试没问题之后再连 WalletConnect

**Comment by CryptoCoinLab** [comment]
metamask 也一样，是否是Ropsten网络费用过高问题 ？ 43491 GWei

**Comment by Tochipeter** [comment]
> imtoken不支持ropsten网络的uniswap V2添加流动性交易签名，
> 最新版本2.10.2.1693 cp67，选择ropsten网络，用walletconnect扫描网页连接ropsten网络的uniswap V2，添加流动性时，无法弹出添加流动性交易。

**Comment by Tochipeter** [comment]
> imtoken不支持ropsten网络的uniswap V2添加流动性交易签名，
> 最新版本2.10.2.1693 cp67，选择ropsten网络，用walletconnect扫描网页连接ropsten网络的uniswap V2，添加流动性时，无法弹出添加流动性交易。

**Comment by CryptoCoinLab** [comment]
网络问题，gas下来就好了。
