### ISSUE TITLE
How can I submit this token

### ISSUE THREAD

**Issue by CHRISNERO17** [consenlabs/token-profile#7391]
How to sumbimit a token on imToken?

**Comment by newbein123** [comment]
> 0x01e799ebd5d11ddeea11e30466ce117b86726458

crack the logos and trade mark

**Comment by zengbing15** [comment]
Commit Pull Request: Please click "New Pull requests" and you can follow the PR template.

**Comment by CHRISNERO17** [comment]
Thanks.
