### ISSUE TITLE
半个多月了国际版搜不到，邮件发了不回，国内版图标也不显示logo，啥情况？

### ISSUE THREAD

**Issue by plusor** [consenlabs/token-profile#741]
https://github.com/consenlabs/token-profile/issues/145

https://github.com/consenlabs/token-profile/issues/135

**Comment by ArtChainGlobal** [comment]
一样的状况， 等好久了， logo 不显示， 也没解决

**Comment by wenyanwang** [comment]
imToken 目前已经支持由项目方自主提交或修改 Token 信息，无论是初次提交项目资料，还是修改代币简称、LOGO 等信息，你都可以通过 Github 自主提交。



注：系统会自动抓取 Etherscan 记录，如果代币名称重复，会在代币名称后添加数字编号来区分。



imToken Github : 

https://github.com/consenlabs/token-profile 



具体教程请参考:

https://github.com/consenlabs/token-profile/blob/master/README.md 



中文教程：https://shimo.im/docs/nKTCMRUhfyAEu2Su
