### ISSUE TITLE
Polygon wallet

### ISSUE THREAD

**Issue by CHRISNERO17** [consenlabs/token-profile#7437]
Update PECO price 0xa9536b9c75a9e0fae3b56a96ac8edf76abc91978

**Comment by Hsenaai** [comment]
> 0xa9536b9c75a9e0fae3b56a96ac8edf76abc91978

**Comment by newbein123** [comment]
What is the issue?

**Comment by Hsenaai** [comment]
Verify polygon

**Comment by Hsenaai** [comment]
#7501

**Comment by 50hz-whale** [comment]
Regarding the token on Polygon, imToken pulls data from Debank. If you want the price of this token to be displayed, you can submit the token information to Debank.
