### ISSUE TITLE
代币已经添加，但是不显示 logo

### ISSUE THREAD

**Issue by dily3825002** [consenlabs/token-profile#763]
![image](https://user-images.githubusercontent.com/3363028/42421399-85fb681a-8307-11e8-9fcf-8416c94d93f1.png)
EGT 已经可以搜索到并添加，名称显示应该是 EGT，但是现在主界面显示 EGT（Egretia），logo 不显示，麻烦检查一下
https://github.com/consenlabs/token-profile/pull/127

**Comment by wenyanwang** [comment]
你好，已经显示，请搜索添加查看。
