### ISSUE TITLE
名字后缀

### ISSUE THREAD

**Issue by freefairchain** [consenlabs/token-profile#765]
https://etherscan.io/token/0xb941ef1f4f9593e211e4ca47b11cb5c2de43ba38
请问以前的合约变更为
https://etherscan.io/token/0xd64129ac9ec6307b9625869e817b6c45eaee80a9 
现在有个后缀 FFC10 要怎么改 ，谢谢

**Comment by wenyanwang** [comment]
代币名称重复，在代币名称后有数字编号来区分
imToken 目前已经支持由项目方自主提交或修改 Token 信息，无论是初次提交项目资料，还是修改代币简称、LOGO 等信息，你都可以通过 Github 自主提交。



注：系统会自动抓取 Etherscan 记录，如果代币名称重复，会在代币名称后添加数字编号来区分。



imToken Github : 

https://github.com/consenlabs/token-profile 



具体教程请参考:

https://github.com/consenlabs/token-profile/blob/master/README.md 



中文教程：https://shimo.im/docs/nKTCMRUhfyAEu2Su

**Comment by freefairchain** [comment]
我们已经上btk 交易所了，现在代币显示有后缀，代币名称相同的etherscan 肯定有很多。我们只是不希望显示后缀，请问怎么才能做到


-------- Original Message --------
Subject: Re:_[consenlabs/token-profile] _名字后缀_(#765)
