### ISSUE TITLE
代币名称后有数字的问题

### ISSUE THREAD

**Issue by ccbupt** [consenlabs/token-profile#767]
PTN代币已经可以搜索到，但是目前名称后还有数字，烦请帮忙把数字取消，多谢啦！
PR #755 
@wenyanwang

**Comment by wenyanwang** [comment]
代币名称重复，在代币名称后有数字编号来区分

**Comment by ccbupt** [comment]
麻烦帮忙去掉数字，我们会通过跟社区公布智能合约地址来区分（这一点跟etherscan一样），不然后面加数字很难跟社区解释。而且目前Imtoken中只能搜索到这个PTN3，没有PTN。多谢！
@makoshan @wenyanwang
