### ISSUE TITLE
imtoken钱包中 logo 显示问题

### ISSUE THREAD

**Issue by ArtChainGlobal** [consenlabs/token-profile#832]
contract 地址： 0x984C134A8809571993Fd1573fB99F06Dc61E216f

0x984C134A8809571993Fd1573fB99F06Dc61E216f.png  正确在 images 文件夹中

在 wallet 界面 logo 无法显示

点进去 token profile 里 logo 可以显示

请问是什么问题呢？

**Comment by likeqin86** [comment]
这个问题很多啊，我们的被官网合并了一个多月了，还没显示出LOGO，问下怎么回事

**Comment by handerek** [comment]
我们的也是，

**Comment by wenyanwang** [comment]
请查看回复给你们的信息，谢谢。
