### ISSUE TITLE
HCT显示不正确

### ISSUE THREAD

**Issue by Shmily1995** [consenlabs/token-profile#845]
HCT
0x26d00D339B22Db44A4a057B39513c1e12D140594
v1 版 TOKEN名称后有数字 ,
v2 版 logo不显示

**Comment by wenyanwang** [comment]
你好,



imToken 目前已经支持由项目方自主提交或修改 Token 信息，无论是初次提交项目资料，还是修改代币简称、LOGO 等信息，你都可以通过 Github 自主提交。



注：

1. 系统会自动抓取 Etherscan 记录，如果代币名称重复，会在代币名称后添加数字编号来区分，请在提交资料的同时建议在区块链上有一笔成功的转账记录。

2. 由于以太坊代币种类多，我们暂时只添加在 Etherscan 有超过 200 txns 或者 100 holders 代币的显示，我们暂时不显示贵团队的代币完全不影响代币的转账，只要贵方的代币是基于以太坊的 ERC 20 标准代币，imToken 就支持搜索合约地址进行显示。

3. 为了不影响 Token 审核进度，请认准阅读操作教程，提交有误的 Token 会提示错误，请注意查看系统审核结果，如果 Token 资料提交有误，再次审核需等待一周。



imToken Github : 

https://github.com/consenlabs/token-profile 



具体教程请参考:

https://github.com/consenlabs/token-profile/blob/master/README.md 



中文教程：https://shimo.im/docs/nKTCMRUhfyAEu2Su 



如有疑问，勿回复此邮件，请在 github PR 下留言与我们联系。



imToken.
