### ISSUE TITLE
有一个错误的json文件导致大家所有的提交都无法完成自动构建

### ISSUE THREAD

**Issue by Joyeye** [consenlabs/token-profile#916]
具体如下，

ERROR! json file name 0x378903a03FB2C3AC76BB52773e3CE11340377A32.json parse error, please check first (maybe has some unnecessary space or comma symbol like ",")
npm ERR! Test failed.  See above for more details.

我查了一下，所有开发者的提交都因为这个文件失败。

**Comment by Eiminyang** [comment]
你是用了中文的逗号吗？

**Comment by parasolzhang** [comment]
我也遇到这个问题了，怎么解决？

**Comment by Bingo821227** [comment]
同样问题，不知道如何解决

**Comment by Joyeye** [comment]
这个文件不是我的，而且我的 erc20 目录下也没有这个文件。

**Comment by ForBTM** [comment]
你们把那个文件修改下就行了，，，我微信 LALALA199814490

**Comment by makoshan** [comment]
已经解决
